[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 921600

; Flash DIO 80MHz, partitions 16MB (app0/app1 6.4MB chacun)
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

; Mesh = ESP-NOW uniquement (pas de WiFi). Logs + donnees JSON sur Serial (USB).
; Niveau logs : LOG_LOCAL_LEVEL 3=Info 4=Debug 5=Verbose (obligatoire pour voir ESP_LOGI sur série)
build_flags =
    -I src
    -I include
    -I include/sensors
    -Wno-deprecated-declarations
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D CORE_DEBUG_LEVEL=3
    -D LOG_LOCAL_LEVEL=4

; ESP-NOW Tree Mesh
build_src_filter = +<*>
lib_deps =
    bblanchon/ArduinoJson@^6.21.0
    adafruit/Adafruit NeoPixel @ ^1.12.0
