components/sensor_acq/include/bme280_driver.h File Reference
Driver Bosch BME280 — Température, Pression, Humidité.
#include "driver/i2c_master.h"
#include "esp_err.h"
Macros
#define BME280_I2C_ADDR_DEFAULT 0x76
Capteur environnemental BME280 (pression/température/humidité).
#define BME280_I2C_ADDR_ALT 0x77
Functions
esp_err_t bme280_init (i2c_master_bus_handle_t bus, uint8_t i2c_addr)
esp_err_t bme280_read (float *temp_c, float *pressure_hpa, float *humidity_pct)
Detailed Description
Driver Bosch BME280 — Température, Pression, Humidité.
Interface I2C via driver/i2c_master.h (ESP-IDF v5+). Adresse I2C 7 bits : 0x76 (SDO=GND) ou 0x77 (SDO=VDD).
Caractéristiques :
Température : −40 °C → +85 °C, résolution 0.01 °C
Pression : 300 hPa → 1100 hPa, résolution 0.18 Pa
Humidité : 0 % → 100 % RH, résolution 0.008 %
Mode utilisé : Forced mode (single-shot) + filtre IIR × 4
Definition in file bme280_driver.h.
Macro Definition Documentation
BME280_I2C_ADDR_ALT
#define BME280_I2C_ADDR_ALT 0x77
SDO reliée à VDD
Definition at line 30 of file bme280_driver.h.
Referenced by app_main().
Function Documentation
bme280_init()
esp_err_t bme280_init (i2c_master_bus_handle_t bus, uint8_t i2c_addr)
Definition at line 155 of file bme280_driver.c.
{
    const i2c_device_config_t dev_cfg = {
        .dev_addr_length = I2C_ADDR_BIT_LEN_7,
        .device_address = i2c_addr,
        .scl_speed_hz = 400000,
    };
    esp_err_t ret = i2c_master_bus_add_device(bus, &dev_cfg, &s_dev);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Ajout device I2C 0x%02X échoué : %s",
                 i2c_addr, esp_err_to_name(ret));
        return ret;
    }
    /* Vérification chip ID */
    uint8_t chip_id = 0;
    ret = read_regs(REG_CHIP_ID, &chip_id, 1);
    if (ret != ESP_OK || chip_id != BME280_CHIP_ID) {
        ESP_LOGW(TAG, "BME280 non détecté (chip_id=0x%02X)", chip_id);
        return (ret == ESP_OK) ? ESP_ERR_NOT_FOUND : ret;
    }
    /* Reset logiciel */
    write_reg(REG_RESET, 0xB6);
    vTaskDelay(pdMS_TO_TICKS(5));
    /* Lecture calibration */
    ret = read_calibration();
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Lecture calibration échouée");
        return ret;
    }
    /* Configuration :
     * ctrl_hum : osrs_h = ×4 (101b = 5)
     * ctrl_meas : osrs_t = ×2 (010b), osrs_p = ×4 (011b), mode = sleep (00b)
     * config : filtre IIR = ×4 (010b), t_sb = 0.5 ms (000b)
     */
    write_reg(REG_CTRL_HUM, 0x05); /* osrs_h ×4 */
    write_reg(REG_CONFIG, 0x10); /* filtre ×4 */
    write_reg(REG_CTRL_MEAS, 0x54); /* osrs_t ×2, osrs_p ×4, sleep mode */
    ESP_LOGI(TAG, "BME280 initialisé (@0x%02X, chip_id=0x60)", i2c_addr);
    return ESP_OK;
}
References BME280_CHIP_ID, read_calibration(), read_regs(), REG_CHIP_ID, REG_CONFIG, REG_CTRL_HUM, REG_CTRL_MEAS, REG_RESET, s_dev, TAG, and write_reg().
Referenced by app_main().
bme280_read()
esp_err_t bme280_read (float * temp_c, float * pressure_hpa, float * humidity_pct)
Definition at line 201 of file bme280_driver.c.
{
    if (!s_dev) return ESP_ERR_INVALID_STATE;
    /* Déclencher une mesure forced (mode = 01b → écriture de ctrl_meas) */
    uint8_t ctrl;
    esp_err_t ret = read_regs(REG_CTRL_MEAS, &ctrl, 1);
    if (ret != ESP_OK) return ret;
    /* Set mode = forced (01) en conservant l'oversampling */
    ctrl = (ctrl & 0xFC) | 0x01;
    ret = write_reg(REG_CTRL_MEAS, ctrl);
    if (ret != ESP_OK) return ret;
    /* Attente fin de conversion */
    vTaskDelay(pdMS_TO_TICKS(MEAS_DELAY_MS));
    /* Lecture de 8 octets : P (3), T (3), H (2) */
    uint8_t data[8] = {0};
    ret = read_regs(REG_DATA_START, data, sizeof(data));
    if (ret != ESP_OK) {
        ESP_LOGW(TAG, "Lecture données échouée : %s", esp_err_to_name(ret));
        return ret;
    }
    int32_t raw_p = ((int32_t)data[0] << 12) | ((int32_t)data[1] << 4) | (data[2] >> 4);
    int32_t raw_t = ((int32_t)data[3] << 12) | ((int32_t)data[4] << 4) | (data[5] >> 4);
    int32_t raw_h = ((int32_t)data[6] << 8) | data[7];
    /* Compensation (ordre obligatoire : T en premier pour s_t_fine) */
    *temp_c = compensate_temperature(raw_t);
    *pressure_hpa = compensate_pressure(raw_p);
    *humidity_pct = compensate_humidity(raw_h);
    return ESP_OK;
}
References compensate_humidity(), compensate_pressure(), compensate_temperature(), MEAS_DELAY_MS, read_regs(), REG_CTRL_MEAS, REG_DATA_START, s_dev, TAG, and write_reg().
Referenced by task_sensor_acq().