Stockage & Logs
Gestion du stockage local (SPIFFS) et mécanismes de log/panic.
Files
file littlefs_manager.c
Gestion du montage SPIFFS sur la partition "storage".
file log_writer.c
Log circulaire sur LittleFS — rotation automatique à 900 Ko.
file panic_handler.c
Capture des paniques système et écriture dans LittleFS.
Macros
#define STORAGE_MOUNT_POINT "/spiffs"
#define STORAGE_PARTITION "storage"
#define LOG_FILE_PATH STORAGE_MOUNT_POINT "/app.log"
#define PANIC_FILE_PATH STORAGE_MOUNT_POINT "/panic.log"
#define LOG_MAX_SIZE_BYTES (900UL * 1024UL)
#define LOG_TRIM_PERCENT 10
#define LITTLEFS_MOUNT_POINT STORAGE_MOUNT_POINT
#define LITTLEFS_PARTITION STORAGE_PARTITION
Functions
esp_err_t littlefs_manager_init (void)
esp_err_t log_write (const char *msg)
esp_err_t panic_handler_install (void)
void panic_handler_check_on_boot (void)
Detailed Description
Gestion du stockage local (SPIFFS) et mécanismes de log/panic.
Pourquoi ce module existe :
conserver des traces (logs) même si le PC n'est pas connecté
aider au diagnostic après un redémarrage inattendu (panic handler)
Macro Definition Documentation
LITTLEFS_MOUNT_POINT
#define LITTLEFS_MOUNT_POINT STORAGE_MOUNT_POINT
Definition at line 42 of file sys_storage.h.
LITTLEFS_PARTITION
#define LITTLEFS_PARTITION STORAGE_PARTITION
Definition at line 43 of file sys_storage.h.
LOG_FILE_PATH
#define LOG_FILE_PATH STORAGE_MOUNT_POINT "/app.log"
Definition at line 36 of file sys_storage.h.
Referenced by cmd_clear_logs(), cmd_download_logs(), log_trim_file(), and log_write().
LOG_MAX_SIZE_BYTES
#define LOG_MAX_SIZE_BYTES (900UL * 1024UL)
Seuil de rotation
Definition at line 38 of file sys_storage.h.
Referenced by log_write().
LOG_TRIM_PERCENT
#define LOG_TRIM_PERCENT 10
% d'entrées à supprimer
Definition at line 39 of file sys_storage.h.
Referenced by log_trim_file().
PANIC_FILE_PATH
#define PANIC_FILE_PATH STORAGE_MOUNT_POINT "/panic.log"
Definition at line 37 of file sys_storage.h.
Referenced by panic_handler_check_on_boot().
STORAGE_MOUNT_POINT
#define STORAGE_MOUNT_POINT "/spiffs"
Definition at line 34 of file sys_storage.h.
Referenced by littlefs_manager_init().
STORAGE_PARTITION
#define STORAGE_PARTITION "storage"
Definition at line 35 of file sys_storage.h.
Referenced by littlefs_manager_init().
Function Documentation
littlefs_manager_init()
esp_err_t littlefs_manager_init (void)
Definition at line 36 of file littlefs_manager.c.
{
    /* Configuration complète du montage SPIFFS */
    const esp_vfs_spiffs_conf_t conf = {
        .base_path = STORAGE_MOUNT_POINT,
        .partition_label = STORAGE_PARTITION,
        .max_files = 8,
        .format_if_mount_failed = true,
    };
    esp_err_t ret = esp_vfs_spiffs_register(&conf);
    if (ret != ESP_OK) {
        if (ret == ESP_FAIL) {
            ESP_LOGE(TAG, "Échec du montage ou du formatage de SPIFFS");
        } else if (ret == ESP_ERR_NOT_FOUND) {
            ESP_LOGE(TAG, "Partition '%s' introuvable dans la table de partitions",
                     STORAGE_PARTITION);
        } else {
            ESP_LOGE(TAG, "Erreur montage SPIFFS : %s", esp_err_to_name(ret));
        }
        return ret;
    }
    /* Vérification post-montage de l'espace disponible */
    size_t total_bytes = 0;
    size_t used_bytes = 0;
    ESP_ERROR_CHECK(esp_spiffs_info(STORAGE_PARTITION, &total_bytes, &used_bytes));
    ESP_LOGI(TAG, "SPIFFS monté sur '%s' — %u Ko total, %u Ko utilisés, %u Ko libres",
             STORAGE_MOUNT_POINT,
             (unsigned)(total_bytes / 1024),
             (unsigned)(used_bytes / 1024),
             (unsigned)((total_bytes - used_bytes) / 1024));
    return ESP_OK;
}
References STORAGE_MOUNT_POINT, STORAGE_PARTITION, and TAG.
Referenced by app_main().
log_write()
esp_err_t log_write (const char * msg)
Definition at line 103 of file log_writer.c.
{
    if (!msg) {
        return ESP_ERR_INVALID_ARG;
    }
    /* Création du mutex lors du premier appel (init paresseuse) */
    if (!s_mutex) {
        s_mutex = xSemaphoreCreateMutex();
        if (!s_mutex) {
            return ESP_ERR_NO_MEM;
        }
    }
    if (xSemaphoreTake(s_mutex, pdMS_TO_TICKS(200)) != pdTRUE) {
        return ESP_ERR_TIMEOUT;
    }
    /* Horodatage en secondes depuis le boot */
    int64_t us = esp_timer_get_time();
    double secs = (double)us / 1e6;
    FILE *f = fopen(LOG_FILE_PATH, "a");
    if (!f) {
        xSemaphoreGive(s_mutex);
        return ESP_FAIL;
    }
    fprintf(f, "[%10.3f] %s\n", secs, msg);
    long current_pos = ftell(f);
    fclose(f);
    /* Déclenchement de la rotation si le seuil est dépassé */
    if (current_pos >= (long)LOG_MAX_SIZE_BYTES) {
        log_trim_file(current_pos);
    }
    xSemaphoreGive(s_mutex);
    return ESP_OK;
}
References LOG_FILE_PATH, LOG_MAX_SIZE_BYTES, log_trim_file(), and s_mutex.
panic_handler_check_on_boot()
void panic_handler_check_on_boot (void)
Definition at line 80 of file panic_handler.c.
{
    if (s_panic_magic != PANIC_MAGIC_VALUE) {
        /* Aucun crash précédent détecté */
        return;
    }
    ESP_LOGW(TAG, "Crash détecté lors du précédent boot — écriture dans panic.log");
    /* Formatage du message avec horodatage */
    char entry[256];
    double secs = (double)s_panic_time_us / 1e6;
    snprintf(entry, sizeof(entry),
             "[%10.3f] PANIC: %s\n",
             secs, s_panic_msg);
    /* Écriture bloquante/synchrone dans panic.log */
    FILE *f = fopen(PANIC_FILE_PATH, "a");
    if (f) {
        fwrite(entry, 1, strlen(entry), f);
        fflush(f);
        fclose(f);
        ESP_LOGI(TAG, "Entrée de panique écrite dans %s", PANIC_FILE_PATH);
    } else {
        ESP_LOGE(TAG, "Impossible d'ouvrir %s", PANIC_FILE_PATH);
    }
    /* Effacement du flag pour ne pas réécrire au prochain boot */
    s_panic_magic = 0;
    memset(s_panic_msg, 0, sizeof(s_panic_msg));
}
References PANIC_FILE_PATH, PANIC_MAGIC_VALUE, s_panic_magic, s_panic_msg, s_panic_time_us, and TAG.
Referenced by app_main().
panic_handler_install()
esp_err_t panic_handler_install (void)
Definition at line 66 of file panic_handler.c.
{
    ESP_ERROR_CHECK(esp_register_shutdown_handler(shutdown_handler));
    ESP_LOGI(TAG, "Shutdown handler installé");
    return ESP_OK;
}
References shutdown_handler(), and TAG.
Referenced by app_main().