Acquisition Capteurs
Lecture capteurs, fusion des données, et production de trames prêtes pour l'IA.
Files
file bme280_driver.c
Driver Bosch BME280 — Température, Pression, Humidité.
file hdc1080_driver.c
Driver HDC1080 — Température et Humidité (TI).
file lidar_driver.c
Acquisition LIDAR VL53L8CX — fusion 8×32 sur double bus I2C.
file mic_driver.c
Driver microphone MEMS I2S — Amplitude RMS et crête.
file radar_driver.c
Driver UART HLK-LD6002 — protocole TinyFrame, ring buffer UART.
file vl53l8cx_platform.c
Couche plateforme VL53L8CX — implémentation SPI via ESP-IDF.
Data Structures
struct VL53L8CX_Platform
Couche “adaptateur” SPI requise par l'ULD ST (VL53L8CX).
Macros
#define BME280_I2C_ADDR_DEFAULT 0x76
Capteur environnemental BME280 (pression/température/humidité).
#define HDC1080_I2C_ADDR 0x40
Capteur environnemental HDC1080 (température/humidité).
Functions
esp_err_t lidar_driver_start (sys_context_t *ctx)
esp_err_t mic_driver_init (void)
Acquisition audio simple (RMS + pic) pour diagnostic et indicateurs.
esp_err_t radar_driver_init (void)
Driver radar HLK-LD6002 (UART + TinyFrame) — optionnel selon la configuration.
Detailed Description
Lecture capteurs, fusion des données, et production de trames prêtes pour l'IA.
Ce module existe pour “isoler le monde matériel” :
la partie IA reçoit une trame stable et cohérente (mêmes unités, mêmes dimensions)
la partie diagnostic PC reçoit des mesures prêtes à afficher
Macro Definition Documentation
BME280_I2C_ADDR_DEFAULT
#define BME280_I2C_ADDR_DEFAULT 0x76
Capteur environnemental BME280 (pression/température/humidité).
SDO reliée à GND
Definition at line 29 of file bme280_driver.h.
Referenced by app_main().
HDC1080_I2C_ADDR
#define HDC1080_I2C_ADDR 0x40
Capteur environnemental HDC1080 (température/humidité).
Adresse I2C 7 bits du HDC1080
Definition at line 28 of file hdc1080_driver.h.
Referenced by hdc1080_init().
Function Documentation
lidar_driver_start()
esp_err_t lidar_driver_start (sys_context_t * ctx)
Definition at line 379 of file lidar_driver.c.
{
    lidar_task_ctx_t *task_ctx = calloc(1, sizeof(lidar_task_ctx_t));
    if (!task_ctx) {
        return ESP_ERR_NO_MEM;
    }
    task_ctx->sys_ctx = ctx;
    /* Création de la tâche épinglée sur Core 1 */
    BaseType_t ret = xTaskCreatePinnedToCore(
        task_sensor_acq,
        "Task_Sensor_Acq",
        TASK_STACK_SIZE,
        task_ctx,
        TASK_PRIORITY,
        NULL,
        TASK_CORE);
    if (ret != pdPASS) {
        free(task_ctx);
        ESP_LOGE(TAG, "Échec création Task_Sensor_Acq");
        return ESP_FAIL;
    }
    ESP_LOGI(TAG, "Task_Sensor_Acq créée (Core %d, priorité %d, %d Hz)",
             TASK_CORE, TASK_PRIORITY, 1000 / TASK_PERIOD_MS);
    return ESP_OK;
}
References lidar_task_ctx_t::sys_ctx, TAG, TASK_CORE, TASK_PERIOD_MS, TASK_PRIORITY, task_sensor_acq(), and TASK_STACK_SIZE.
Referenced by app_main().
mic_driver_init()
esp_err_t mic_driver_init (void)
Acquisition audio simple (RMS + pic) pour diagnostic et indicateurs.
Definition at line 36 of file mic_driver.c.
{
    /* Création du canal I2S RX */
    const i2s_chan_config_t chan_cfg = {
        .id = I2S_NUM_AUTO,
        .role = I2S_ROLE_MASTER,
        .dma_desc_num = 4,
        .dma_frame_num = 256,
        .auto_clear = true,
    };
    esp_err_t ret = i2s_new_channel(&chan_cfg, NULL, &s_rx_chan);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Création canal I2S échouée : %s", esp_err_to_name(ret));
        return ret;
    }
    /* Configuration standard I2S */
    i2s_std_config_t std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(MIC_SAMPLE_RATE),
        .slot_cfg = I2S_STD_MSB_SLOT_DEFAULT_CONFIG(
                        I2S_DATA_BIT_WIDTH_32BIT,
                        I2S_SLOT_MODE_STEREO), /* Stéréo pour lire LRCK */
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED,
            .bclk = PIN_MIC_SCK,
            .ws = PIN_MIC_WS,
            .dout = I2S_GPIO_UNUSED,
            .din = PIN_MIC_SD,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };
    ret = i2s_channel_init_std_mode(s_rx_chan, &std_cfg);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Init mode standard échoué : %s", esp_err_to_name(ret));
        i2s_del_channel(s_rx_chan);
        s_rx_chan = NULL;
        return ret;
    }
    ret = i2s_channel_enable(s_rx_chan);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Activation canal I2S échouée : %s", esp_err_to_name(ret));
        i2s_del_channel(s_rx_chan);
        s_rx_chan = NULL;
        return ret;
    }
    ESP_LOGI(TAG, "Microphone I2S initialisé (%d Hz, %d samples/burst)",
             MIC_SAMPLE_RATE, MIC_BURST_SAMPLES);
    return ESP_OK;
}
References MIC_BURST_SAMPLES, MIC_SAMPLE_RATE, PIN_MIC_SCK, PIN_MIC_SD, PIN_MIC_WS, s_rx_chan, and TAG.
Referenced by app_main().
radar_driver_init()
esp_err_t radar_driver_init (void)
Driver radar HLK-LD6002 (UART + TinyFrame) — optionnel selon la configuration.
Definition at line 169 of file radar_driver.c.
{
    memset(&s_parser, 0, sizeof(s_parser));
    ESP_LOGI(TAG, "Parser TinyFrame LD6002 initialisé (UART%d, %d bauds)",
             UART_PORT, 1382400);
    return ESP_OK;
}
References s_parser, TAG, and UART_PORT.
Referenced by task_sensor_acq().