Réseau maillé & OTA
Communication entre nœuds (ESP-NOW), chiffrement applicatif, et mise à jour OTA.
Files
file mesh_manager.c
Gestionnaire réseau maillé ESP-NOW — topologie arborescente + AES-128.
file ota_node.c
OTA nœud-à-nœud via ESP-NOW — fragments 200 octets.
Functions
esp_err_t mesh_manager_init (sys_context_t *ctx)
esp_err_t mesh_task_start (sys_context_t *ctx)
esp_err_t ota_node_init (void)
Module OTA “nœud-à-nœud” utilisé par le réseau maillé.
Detailed Description
Communication entre nœuds (ESP-NOW), chiffrement applicatif, et mise à jour OTA.
Idée simple :
le Wi‑Fi sert ici de transport local (ESP‑NOW) pour relier des nœuds sans infrastructure
la sécurité est renforcée par un chiffrement applicatif (AES) en plus d'ESP‑NOW
Function Documentation
mesh_manager_init()
esp_err_t mesh_manager_init (sys_context_t * ctx)
Definition at line 379 of file mesh_manager.c.
{
    memset(&s_mesh, 0, sizeof(s_mesh));
    s_mesh.sys_ctx = ctx;
    s_mesh.hop_to_root = ctx->is_root_node ? 0 : 0xFF;
    /* Chargement de la clé AES */
    mesh_load_aes_key();
    /* Initialisation réseau */
    ESP_ERROR_CHECK(esp_netif_init());
    esp_netif_create_default_wifi_sta();
    const wifi_init_config_t wifi_cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&wifi_cfg));
    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));
    ESP_ERROR_CHECK(esp_wifi_start());
    /* set_channel doit être appelé APRÈS esp_wifi_start() */
    ESP_ERROR_CHECK(esp_wifi_set_channel(ESPNOW_CHANNEL, WIFI_SECOND_CHAN_NONE));
    /* Récupération de l'adresse MAC propre */
    ESP_ERROR_CHECK(esp_wifi_get_mac(WIFI_IF_STA, s_mesh.own_mac));
    ESP_LOGI(TAG, "MAC propre : " MACSTR, MAC2STR(s_mesh.own_mac));
    /* Initialisation ESP-NOW */
    ESP_ERROR_CHECK(esp_now_init());
    ESP_ERROR_CHECK(esp_now_set_pmk(k_pmk));
    ESP_ERROR_CHECK(esp_now_register_recv_cb(espnow_rx_callback));
    ESP_ERROR_CHECK(esp_now_register_send_cb(espnow_tx_callback));
    /* Initialisation du module OTA */
    ESP_ERROR_CHECK(ota_node_init());
    ESP_LOGI(TAG, "Mesh ESP-NOW initialisé (canal %d, rôle : %s)",
             ESPNOW_CHANNEL,
             ctx->is_root_node ? "ROOT" : "NODE");
    return ESP_OK;
}
References ESPNOW_CHANNEL, espnow_rx_callback(), espnow_tx_callback(), sys_context_t::is_root_node, k_pmk, mesh_load_aes_key(), ota_node_init(), s_mesh, and TAG.
Referenced by app_main().
mesh_task_start()
esp_err_t mesh_task_start (sys_context_t * ctx)
Definition at line 426 of file mesh_manager.c.
{
    (void)ctx; /* s_mesh.sys_ctx déjà rempli par mesh_manager_init */
    BaseType_t ret = xTaskCreatePinnedToCore(
        task_mesh_com,
        "Task_Mesh_Com",
        MESH_TASK_STACK,
        &s_mesh,
        MESH_TASK_PRIORITY,
        NULL,
        MESH_TASK_CORE);
    if (ret != pdPASS) {
        ESP_LOGE(TAG, "Échec création Task_Mesh_Com");
        return ESP_FAIL;
    }
    ESP_LOGI(TAG, "Task_Mesh_Com créée (Core %d, priorité %d)",
             MESH_TASK_CORE, MESH_TASK_PRIORITY);
    return ESP_OK;
}
References MESH_TASK_CORE, MESH_TASK_PRIORITY, MESH_TASK_STACK, s_mesh, TAG, and task_mesh_com().
Referenced by app_main().
ota_node_init()
esp_err_t ota_node_init (void)
Module OTA “nœud-à-nœud” utilisé par le réseau maillé.
Definition at line 45 of file ota_node.c.
{
    memset(&s_ota, 0, sizeof(s_ota));
    /* Identification de la partition de mise à jour */
    s_ota.ota_partition = esp_ota_get_next_update_partition(NULL);
    if (!s_ota.ota_partition) {
        ESP_LOGW(TAG, "Aucune partition OTA disponible");
    } else {
        ESP_LOGI(TAG, "Partition OTA cible : %s (offset 0x%08lX, taille %lu Ko)",
                 s_ota.ota_partition->label,
                 s_ota.ota_partition->address,
                 s_ota.ota_partition->size / 1024);
    }
    return ESP_OK;
}
References s_ota, and TAG.
Referenced by mesh_manager_init().