Diagnostic Matériel
Vérifications au démarrage : bus, capteurs, et expandeur PCA9555.
Files
file hw_diag.c
Diagnostic matériel au démarrage — I2C LIDAR + UART Radar.
Enumerations
enum hw_diag_result_t { HW_DIAG_OK = 0x00
, HW_DIAG_LIDAR_PARTIAL = 0x01
, HW_DIAG_LIDAR_ALL = 0x02
, HW_DIAG_RADAR_MISSING = 0x04
 }
Functions
hw_diag_result_t hw_diag_run (sys_context_t *ctx)
esp_err_t hw_diag_init_sensor_bus (i2c_master_bus_handle_t *out_handle)
esp_err_t hw_diag_pca9555_set_power (uint8_t port1_bit, bool enable)
Detailed Description
Vérifications au démarrage : bus, capteurs, et expandeur PCA9555.
Raison d'être :
détecter tôt les problèmes de câblage ou d'alimentation
éviter de lancer des tâches qui bloqueraient si un périphérique est absent
produire un rapport lisible (JSON) pour accélérer le diagnostic côté PC
Enumeration Type Documentation
hw_diag_result_t
enum hw_diag_result_t
Enumerator
HW_DIAG_OK
HW_DIAG_LIDAR_PARTIAL Au moins un LIDAR absent
HW_DIAG_LIDAR_ALL Aucun LIDAR détecté
HW_DIAG_RADAR_MISSING Radar LD6002 non détecté
Definition at line 33 of file hw_diag.h.
             {
    HW_DIAG_OK = 0x00,
    HW_DIAG_LIDAR_PARTIAL = 0x01, /**< Au moins un LIDAR absent */
    HW_DIAG_LIDAR_ALL = 0x02, /**< Aucun LIDAR détecté */
    HW_DIAG_RADAR_MISSING = 0x04, /**< Radar LD6002 non détecté */
} hw_diag_result_t;
Function Documentation
hw_diag_init_sensor_bus()
esp_err_t hw_diag_init_sensor_bus (i2c_master_bus_handle_t * out_handle)
Definition at line 575 of file hw_diag.c.
{
    return diag_init_i2c_bus(I2C_NUM_1,
                              PIN_I2C1_SDA, PIN_I2C1_SCL,
                              out_handle);
}
References diag_init_i2c_bus(), PIN_I2C1_SCL, and PIN_I2C1_SDA.
Referenced by app_main().
hw_diag_pca9555_set_power()
esp_err_t hw_diag_pca9555_set_power (uint8_t port1_bit, bool enable)
Definition at line 585 of file hw_diag.c.
{
    if (!s_pca_bus) {
        ESP_LOGE(TAG, "pca9555_set_power : bus PCA9555 non initialisé");
        return ESP_ERR_INVALID_STATE;
    }
    if (enable) {
        s_pca1_out |= port1_bit;
    } else {
        s_pca1_out &= ~port1_bit;
    }
    esp_err_t ret = pca9555_write_reg(s_pca_bus, PCA9555_REG_OUTPUT_1, s_pca1_out);
    if (ret == ESP_OK) {
        ESP_LOGI(TAG, "PCA9555 Port1 → 0x%02X (%s bit 0x%02X)",
                 s_pca1_out, enable ? "SET" : "CLR", port1_bit);
    } else {
        ESP_LOGE(TAG, "PCA9555 Port1 écriture échouée : %s", esp_err_to_name(ret));
    }
    return ret;
}
References PCA9555_REG_OUTPUT_1, pca9555_write_reg(), s_pca1_out, s_pca_bus, and TAG.
Referenced by app_main().
hw_diag_run()
hw_diag_result_t hw_diag_run (sys_context_t * ctx)
Definition at line 508 of file hw_diag.c.
{
    ESP_LOGI(TAG, "=== Démarrage du diagnostic matériel ===");
    /* --- Bus SPI LIDAR : initialise le bus + 4 devices NCS dédiés --- */
    ESP_ERROR_CHECK(diag_init_spi_lidars(ctx));
    /* --- Bus I2C PCA9555 : PERSISTANT (contrôle LPn + alimentation) ---
     * Ne pas détruire ce bus — il est réutilisé par hw_diag_pca9555_set_power()
     * pour piloter les alimentations (POWER_MIC, POWER_RADAR, etc.) */
    esp_err_t pca_ret = diag_init_i2c_bus(I2C_NUM_0,
                                            PIN_I2C0_SDA, PIN_I2C0_SCL,
                                            &s_pca_bus);
    if (pca_ret != ESP_OK) {
        ESP_LOGW(TAG, "PCA9555 I2C init échoué — LPn et alimentations non contrôlables");
    }
    i2c_master_bus_handle_t pca_bus = s_pca_bus; /* alias local pour lisibilité */
    /* --- Lecture du sélecteur ROOT/NODE --- */
    gpio_set_pull_mode(PIN_ROOT_SEL, GPIO_PULLUP_ONLY);
    gpio_set_direction(PIN_ROOT_SEL, GPIO_MODE_INPUT);
    ctx->is_root_node = (gpio_get_level(PIN_ROOT_SEL) == 0);
    ESP_LOGI(TAG, "Rôle nœud : %s", ctx->is_root_node ? "ROOT (passerelle)" : "NODE");
    /* --- Scan des LIDARs via SPI --- */
    memset(ctx->lidar_ok, 0, sizeof(ctx->lidar_ok));
    diag_scan_lidars(ctx, pca_bus);
    /* Bus PCA9555 conservé dans s_pca_bus — réutilisé par hw_diag_pca9555_set_power() */
    /* --- Test du radar (uniquement si connecté) --- */
#if LEXACARE_ENABLE_RADAR
    diag_test_radar(ctx);
#else
    ctx->radar_ok = false;
    ESP_LOGI(TAG, "Radar LD6002 ignoré (LEXACARE_ENABLE_RADAR=0) — boot +2 s économisés");
#endif
    /* --- Calcul du masque de résultat --- */
    hw_diag_result_t result = HW_DIAG_OK;
    int lidar_count = 0;
    for (int i = 0; i < LIDAR_NUM_FRONT; i++) {
        if (ctx->lidar_ok[i]) lidar_count++;
    }
    if (lidar_count == 0) {
        result |= HW_DIAG_LIDAR_ALL;
    } else if (lidar_count < LIDAR_NUM_FRONT) {
        result |= HW_DIAG_LIDAR_PARTIAL;
    }
#if LEXACARE_ENABLE_RADAR
    if (!ctx->radar_ok) {
        result |= HW_DIAG_RADAR_MISSING;
    }
#endif
    /* Rapport JSON sur la console */
    diag_print_json_report(ctx, result);
    ESP_LOGI(TAG, "=== Diagnostic terminé (mask=0x%02X) ===", result);
    return result;
}
References diag_init_i2c_bus(), diag_init_spi_lidars(), diag_print_json_report(), diag_scan_lidars(), diag_test_radar(), HW_DIAG_LIDAR_ALL, HW_DIAG_LIDAR_PARTIAL, HW_DIAG_OK, HW_DIAG_RADAR_MISSING, sys_context_t::is_root_node, LIDAR_NUM_FRONT, sys_context_t::lidar_ok, PIN_I2C0_SCL, PIN_I2C0_SDA, PIN_ROOT_SEL, sys_context_t::radar_ok, s_pca_bus, and TAG.
Referenced by app_main().