components/sensor_acq/include/hdc1080_driver.h File Reference
Driver Texas Instruments HDC1080 — Température et Humidité relative.
#include "driver/i2c_master.h"
#include "esp_err.h"
Macros
#define HDC1080_I2C_ADDR 0x40
Capteur environnemental HDC1080 (température/humidité).
Functions
esp_err_t hdc1080_init (i2c_master_bus_handle_t bus)
esp_err_t hdc1080_read (float *temp_c, float *humidity_pct)
Detailed Description
Driver Texas Instruments HDC1080 — Température et Humidité relative.
Interface I2C via driver/i2c_master.h (ESP-IDF v5+). Adresse I2C 7 bits : 0x40 (fixe sur HDC1080).
Caractéristiques :
Température : −40 °C → +125 °C, résolution 14 bits (±0.2 °C typ.)
Humidité : 0 % → 100 % RH, résolution 14 bits (±2 % typ.)
Temps d'acquisition : ~15 ms (mode 14 bits)
Definition in file hdc1080_driver.h.
Function Documentation
hdc1080_init()
esp_err_t hdc1080_init (i2c_master_bus_handle_t bus)
Definition at line 72 of file hdc1080_driver.c.
{
    const i2c_device_config_t dev_cfg = {
        .dev_addr_length = I2C_ADDR_BIT_LEN_7,
        .device_address = HDC1080_I2C_ADDR,
        .scl_speed_hz = 400000,
    };
    esp_err_t ret = i2c_master_bus_add_device(bus, &dev_cfg, &s_dev);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Ajout device I2C échoué : %s", esp_err_to_name(ret));
        return ret;
    }
    /* Vérification Device ID */
    uint8_t id_buf[2] = {0};
    uint8_t reg = REG_DEVICE_ID;
    ret = i2c_master_transmit(s_dev, &reg, 1, pdMS_TO_TICKS(I2C_TIMEOUT_MS));
    if (ret == ESP_OK) {
        vTaskDelay(pdMS_TO_TICKS(5));
        ret = i2c_master_receive(s_dev, id_buf, 2, pdMS_TO_TICKS(I2C_TIMEOUT_MS));
    }
    if (ret != ESP_OK) {
        ESP_LOGW(TAG, "HDC1080 non détecté sur bus I2C");
        return ret;
    }
    uint16_t device_id = ((uint16_t)id_buf[0] << 8) | id_buf[1];
    if (device_id != HDC1080_DEVICE_ID) {
        ESP_LOGW(TAG, "Device ID inattendu : 0x%04X (attendu 0x%04X)",
                 device_id, HDC1080_DEVICE_ID);
    }
    /* Configuration :
     * Bit 13 = 1 : Acquisition température + humidité simultanée
     * Bit 10 = 0 : Résolution température 14 bits
     * Bit 9 = 0 : Résolution humidité 14 bits
     */
    const uint16_t config = (1u << 13);
    ret = write_register(REG_CONFIG, config);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Écriture config échouée : %s", esp_err_to_name(ret));
        return ret;
    }
    ESP_LOGI(TAG, "HDC1080 initialisé (Device ID=0x%04X, config=0x%04X)",
             device_id, config);
    return ESP_OK;
}
References HDC1080_DEVICE_ID, HDC1080_I2C_ADDR, I2C_TIMEOUT_MS, REG_CONFIG, REG_DEVICE_ID, s_dev, TAG, and write_register().
Referenced by app_main().
hdc1080_read()
esp_err_t hdc1080_read (float * temp_c, float * humidity_pct)
Definition at line 124 of file hdc1080_driver.c.
{
    if (!s_dev) {
        return ESP_ERR_INVALID_STATE;
    }
    /* Déclenchement acquisition séquentielle (écriture REG_TEMPERATURE) */
    uint8_t raw[4] = {0};
    esp_err_t ret = read_bytes(REG_TEMPERATURE, raw, sizeof(raw));
    if (ret != ESP_OK) {
        ESP_LOGW(TAG, "Lecture échouée : %s", esp_err_to_name(ret));
        return ret;
    }
    uint16_t raw_t = ((uint16_t)raw[0] << 8) | raw[1];
    uint16_t raw_h = ((uint16_t)raw[2] << 8) | raw[3];
    *temp_c = (raw_t / 65536.0f) * 165.0f - 40.0f;
    *humidity_pct = (raw_h / 65536.0f) * 100.0f;
    /* Clamp physique */
    if (*humidity_pct < 0.0f) *humidity_pct = 0.0f;
    if (*humidity_pct > 100.0f) *humidity_pct = 100.0f;
    return ESP_OK;
}
References read_bytes(), REG_TEMPERATURE, s_dev, and TAG.
Referenced by task_sensor_acq().