components/hw_diag/hw_diag.c File Reference
Diagnostic matériel au démarrage — I2C LIDAR + UART Radar.
#include "hw_diag.h"
#include "lexacare_config.h"
#include "pins_config.h"
#include "esp_log.h"
#include "esp_err.h"
#include "driver/i2c_master.h"
#include "driver/spi_master.h"
#include "driver/uart.h"
#include "driver/gpio.h"
#include "cJSON.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <string.h>
#include <stdio.h>
Macros
#define I2C_BUS_FREQ_HZ 400000
#define I2C_TIMEOUT_MS 10
#define LIDAR_LPN_DELAY_MS 5
#define LIDAR_SPI_FREQ_HZ (8 * 1000 * 1000)
#define LIDAR_SPI_MAX_XFER (4096 + 2)
#define VL53L8CX_REG_MODEL_ID 0x7FFF
#define VL53L8CX_MODEL_ID 0xF0
#define RADAR_UART_PORT UART_NUM_2
#define RADAR_BAUD_RATE 1382400
#define RADAR_RX_BUF_SIZE 512
#define RADAR_DETECT_TIMEOUT_MS 2000
#define TF_SOF 0x01
Functions
static esp_err_t diag_init_i2c_bus (i2c_port_num_t port, int sda_pin, int scl_pin, i2c_master_bus_handle_t *handle)
static esp_err_t diag_init_spi_lidars (sys_context_t *ctx)
static bool diag_spi_ping_lidar (spi_device_handle_t spi)
static esp_err_t pca9555_write_reg (i2c_master_bus_handle_t bus, uint8_t reg, uint8_t val)
static esp_err_t pca9555_init (i2c_master_bus_handle_t bus)
static esp_err_t pca9555_set_lpn (i2c_master_bus_handle_t bus, int idx, bool active)
static void diag_scan_lidars (sys_context_t *ctx, i2c_master_bus_handle_t pca_bus)
static void diag_test_radar (sys_context_t *ctx)
static void diag_print_json_report (const sys_context_t *ctx, hw_diag_result_t result)
hw_diag_result_t hw_diag_run (sys_context_t *ctx)
esp_err_t hw_diag_init_sensor_bus (i2c_master_bus_handle_t *out_handle)
esp_err_t hw_diag_pca9555_set_power (uint8_t port1_bit, bool enable)
Variables
static const char * TAG = "hw_diag"
static const int s_ncs_pins [LIDAR_NUM_FRONT]
static const uint8_t s_pca_lpn_bit [LIDAR_NUM_FRONT]
static uint8_t s_pca_out = 0x00
static uint8_t s_pca1_out = 0x00
static i2c_master_bus_handle_t s_pca_bus = NULL
static i2c_master_dev_handle_t s_pca_dev = NULL
Detailed Description
Diagnostic matériel au démarrage — I2C LIDAR + UART Radar.
Exécuté avant les tâches FreeRTOS dans app_main(). Initialise les bus I2C partagés et les stocke dans sys_context_t pour réutilisation par sensor_acq sans réinitialisation.
Definition in file hw_diag.c.
Macro Definition Documentation
I2C_BUS_FREQ_HZ
#define I2C_BUS_FREQ_HZ 400000
400 kHz pour le PCA9555
Definition at line 31 of file hw_diag.c.
Referenced by diag_init_i2c_bus(), and pca9555_init().
I2C_TIMEOUT_MS
#define I2C_TIMEOUT_MS 10
Definition at line 32 of file hw_diag.c.
Referenced by hdc1080_init(), pca9555_write_reg(), read_bytes(), read_regs(), write_reg(), and write_register().
LIDAR_LPN_DELAY_MS
#define LIDAR_LPN_DELAY_MS 5
Délai après LPn=1 avant test SPI
Definition at line 33 of file hw_diag.c.
Referenced by diag_scan_lidars().
LIDAR_SPI_FREQ_HZ
#define LIDAR_SPI_FREQ_HZ (8 * 1000 * 1000)
8 MHz (max 10 MHz VL53L8CX)
Definition at line 38 of file hw_diag.c.
Referenced by diag_init_spi_lidars().
LIDAR_SPI_MAX_XFER
#define LIDAR_SPI_MAX_XFER (4096 + 2)
Definition at line 39 of file hw_diag.c.
Referenced by diag_init_spi_lidars().
RADAR_BAUD_RATE
#define RADAR_BAUD_RATE 1382400
Definition at line 57 of file hw_diag.c.
Referenced by diag_test_radar().
RADAR_DETECT_TIMEOUT_MS
#define RADAR_DETECT_TIMEOUT_MS 2000
Definition at line 59 of file hw_diag.c.
Referenced by diag_test_radar().
RADAR_RX_BUF_SIZE
#define RADAR_RX_BUF_SIZE 512
Definition at line 58 of file hw_diag.c.
Referenced by diag_test_radar().
RADAR_UART_PORT
#define RADAR_UART_PORT UART_NUM_2
Definition at line 56 of file hw_diag.c.
Referenced by diag_test_radar().
TF_SOF
#define TF_SOF 0x01
TinyFrame Start Of Frame
Definition at line 60 of file hw_diag.c.
Referenced by diag_test_radar(), and parse_tinyframe().
VL53L8CX_MODEL_ID
#define VL53L8CX_MODEL_ID 0xF0
Definition at line 43 of file hw_diag.c.
VL53L8CX_REG_MODEL_ID
#define VL53L8CX_REG_MODEL_ID 0x7FFF
Definition at line 42 of file hw_diag.c.
Function Documentation
diag_init_i2c_bus()
esp_err_t diag_init_i2c_bus (i2c_port_num_t port, int sda_pin, int scl_pin, i2c_master_bus_handle_t * handle) [static]
Definition at line 96 of file hw_diag.c.
{
    const i2c_master_bus_config_t cfg = {
        .clk_source = I2C_CLK_SRC_DEFAULT,
        .i2c_port = port,
        .sda_io_num = sda_pin,
        .scl_io_num = scl_pin,
        .glitch_ignore_cnt = 7,
        .flags.enable_internal_pullup = true,
    };
    esp_err_t ret = i2c_new_master_bus(&cfg, handle);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Échec création bus I2C%d : %s", port, esp_err_to_name(ret));
    } else {
        ESP_LOGI(TAG, "Bus I2C%d initialisé (SDA=%d, SCL=%d, %d Hz)",
                 port, sda_pin, scl_pin, I2C_BUS_FREQ_HZ);
    }
    return ret;
}
References I2C_BUS_FREQ_HZ, and TAG.
Referenced by hw_diag_init_sensor_bus(), and hw_diag_run().
diag_init_spi_lidars()
esp_err_t diag_init_spi_lidars (sys_context_t * ctx) [static]
Definition at line 129 of file hw_diag.c.
{
    const spi_bus_config_t bus_cfg = {
        .mosi_io_num = PIN_LIDAR_MOSI,
        .miso_io_num = PIN_LIDAR_MISO,
        .sclk_io_num = PIN_LIDAR_CLK,
        .quadwp_io_num = -1,
        .quadhd_io_num = -1,
        .max_transfer_sz = LIDAR_SPI_MAX_XFER,
    };
    esp_err_t ret = spi_bus_initialize(LIDAR_SPI_HOST, &bus_cfg, SPI_DMA_CH_AUTO);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "SPI bus init échoué : %s", esp_err_to_name(ret));
        return ret;
    }
    ESP_LOGI(TAG, "Bus SPI LIDAR initialisé (CLK=%d, MOSI=%d, MISO=%d, %d MHz)",
             PIN_LIDAR_CLK, PIN_LIDAR_MOSI, PIN_LIDAR_MISO,
             LIDAR_SPI_FREQ_HZ / 1000000);
    for (int i = 0; i < LIDAR_NUM_FRONT; i++) {
        const spi_device_interface_config_t dev_cfg = {
            .mode = 3, /* CPOL=1, CPHA=1 (VL53L8CX SPI) */
            .clock_speed_hz = LIDAR_SPI_FREQ_HZ,
            .spics_io_num = s_ncs_pins[i], /* NCS dédié par capteur */
            .queue_size = 1,
        };
        ret = spi_bus_add_device(LIDAR_SPI_HOST, &dev_cfg, &ctx->lidar_spi[i]);
        if (ret != ESP_OK) {
            ESP_LOGE(TAG, "SPI add device LIDAR[%d] (NCS=GPIO%d) échoué : %s",
                     i, s_ncs_pins[i], esp_err_to_name(ret));
            return ret;
        }
        ESP_LOGI(TAG, "LIDAR[%d] SPI device ajouté (NCS=GPIO%d)",
                 i, s_ncs_pins[i]);
    }
    return ESP_OK;
}
References LIDAR_NUM_FRONT, sys_context_t::lidar_spi, LIDAR_SPI_FREQ_HZ, LIDAR_SPI_HOST, LIDAR_SPI_MAX_XFER, PIN_LIDAR_CLK, PIN_LIDAR_MISO, PIN_LIDAR_MOSI, s_ncs_pins, and TAG.
Referenced by hw_diag_run().
diag_print_json_report()
void diag_print_json_report (const sys_context_t * ctx, hw_diag_result_t result) [static]
Definition at line 475 of file hw_diag.c.
{
    cJSON *root = cJSON_CreateObject();
    cJSON *lidars = cJSON_CreateArray();
    for (int i = 0; i < LIDAR_NUM_FRONT; i++) {
        cJSON *lidar = cJSON_CreateObject();
        cJSON_AddNumberToObject(lidar, "id", i);
        cJSON_AddBoolToObject(lidar, "ok", ctx->lidar_ok[i]);
        cJSON_AddNumberToObject(lidar, "ncs_gpio", s_ncs_pins[i]);
        cJSON_AddItemToArray(lidars, lidar);
    }
    cJSON_AddItemToObject(root, "lidars", lidars);
    cJSON_AddBoolToObject(root, "radar_ok", ctx->radar_ok);
    cJSON_AddNumberToObject(root, "result_mask", (double)result);
    char *json_str = cJSON_Print(root);
    if (json_str) {
        ESP_LOGI(TAG, "Rapport diagnostic matériel :\n%s", json_str);
        cJSON_free(json_str);
    }
    cJSON_Delete(root);
}
References LIDAR_NUM_FRONT, sys_context_t::lidar_ok, sys_context_t::radar_ok, s_ncs_pins, and TAG.
Referenced by hw_diag_run().
diag_scan_lidars()
void diag_scan_lidars (sys_context_t * ctx, i2c_master_bus_handle_t pca_bus) [static]
Definition at line 340 of file hw_diag.c.
{
    /* Initialisation PCA9555 : Port 0 + Port 1 en sortie, tout à 0 */
    if (pca_bus) {
        esp_err_t ret = pca9555_init(pca_bus);
        if (ret != ESP_OK) {
            ESP_LOGE(TAG, "PCA9555 inaccessible — LPn non contrôlables");
            pca_bus = NULL;
        }
    }
    /* --- Validation bus SPI AVANT toute manipulation LPN ─────────────────
     * Envoie une trame de test sur NCS0 (LIDAR 1) pour confirmer que
     * GPIO17 (CLK) est bien piloté par le contrôleur SPI.
     * Le VL53L8CX ne répondra pas (LPN=0, pas de firmware ULD chargé)
     * mais le CLK doit impérativement bouger. ----------------------------*/
    {
        const uint8_t tx_test[3] = {0xFF, 0xFF, 0x00};
        uint8_t rx_test[3] = {0};
        spi_transaction_t t_test = {
            .length = sizeof(tx_test) * 8,
            .tx_buffer = tx_test,
            .rx_buffer = rx_test,
        };
        esp_err_t spi_test = spi_device_polling_transmit(ctx->lidar_spi[0], &t_test);
        if (spi_test == ESP_OK) {
            ESP_LOGI(TAG, "Bus SPI LIDAR validé — GPIO%d (CLK) fonctionne",
                     PIN_LIDAR_CLK);
        } else {
            ESP_LOGE(TAG, "Bus SPI LIDAR ERREUR : %s — vérifier GPIO%d",
                     esp_err_to_name(spi_test), PIN_LIDAR_CLK);
        }
    }
    vTaskDelay(pdMS_TO_TICKS(10)); /* Stabilisation après reset global */
    /* --- Scan séquentiel des 4 LIDARs (index 0–3 = LIDAR 1–4 hardware) ---
     *
     * RÈGLE : le ping SPI est TOUJOURS exécuté, même si LPN échoue.
     * La CLK (GPIO17) doit bouger à chaque itération quelle que soit
     * l'état du PCA9555. Le LIDAR ne répondra que si LPN=1 ET ULD chargé.
     * -------------------------------------------------------------------*/
    for (int i = 0; i < LIDAR_NUM_FRONT; i++) {
        /* Activation LPn via PCA9555 — non bloquante pour le SPI */
        bool lpn_ok = false;
        if (pca_bus) {
            esp_err_t lpn_ret = pca9555_set_lpn(pca_bus, i, true);
            if (lpn_ret == ESP_OK) {
                lpn_ok = true;
            } else {
                ESP_LOGW(TAG, "LIDAR%d : PCA9555 LPn échoué (%s) — SPI testé quand même",
                         i + 1, esp_err_to_name(lpn_ret));
            }
        }
        vTaskDelay(pdMS_TO_TICKS(LIDAR_LPN_DELAY_MS));
        /* Test SPI inconditionnnel — génère toujours des impulsions sur CLK */
        ctx->lidar_ok[i] = diag_spi_ping_lidar(ctx->lidar_spi[i]);
        ESP_LOGI(TAG, "LIDAR%d SPI %-6s | NCS=GPIO%-2d | LPn=IO0.%d (%s)",
                 i + 1,
                 ctx->lidar_ok[i] ? "OK" : "absent",
                 s_ncs_pins[i],
                 6 - i, /* LPn1=IO0.6, LPn2=IO0.5, LPn3=IO0.4, LPn4=IO0.3 */
                 lpn_ok ? "actif" : "échec");
    }
}
References diag_spi_ping_lidar(), LIDAR_LPN_DELAY_MS, LIDAR_NUM_FRONT, sys_context_t::lidar_ok, sys_context_t::lidar_spi, pca9555_init(), pca9555_set_lpn(), PIN_LIDAR_CLK, s_ncs_pins, and TAG.
Referenced by hw_diag_run().
diag_spi_ping_lidar()
bool diag_spi_ping_lidar (spi_device_handle_t spi) [static]
Definition at line 183 of file hw_diag.c.
{
    /* Lecture registre 0x7FFF : TX=[0xFF][0xFF][dummy], RX=[xx][xx][model_id]
     * (bit15=1 → lecture, adresse 0x7FFF → addr_hi=0x7F|0x80=0xFF, addr_lo=0xFF) */
    const uint8_t tx[3] = {0xFF, 0xFF, 0x00};
    uint8_t rx[3] = {0x00, 0x00, 0x00};
    spi_transaction_t t = {
        .length = sizeof(tx) * 8,
        .tx_buffer = tx,
        .rx_buffer = rx,
    };
    esp_err_t ret = spi_device_polling_transmit(spi, &t);
    if (ret != ESP_OK) {
        return false;
    }
    /* 0xFF = MISO flottant (absent) ; 0xF0 = Model ID VL53L8CX */
    return (rx[2] != 0xFF);
}
Referenced by diag_scan_lidars().
diag_test_radar()
void diag_test_radar (sys_context_t * ctx) [static]
Definition at line 417 of file hw_diag.c.
{
    const uart_config_t uart_cfg = {
        .baud_rate = RADAR_BAUD_RATE,
        .data_bits = UART_DATA_8_BITS,
        .parity = UART_PARITY_DISABLE,
        .stop_bits = UART_STOP_BITS_1,
        .flow_ctrl = UART_HW_FLOWCTRL_DISABLE,
        .source_clk = UART_SCLK_DEFAULT,
    };
    ESP_ERROR_CHECK(uart_driver_install(RADAR_UART_PORT,
                                         RADAR_RX_BUF_SIZE, 0, 0, NULL, 0));
    ESP_ERROR_CHECK(uart_param_config(RADAR_UART_PORT, &uart_cfg));
    ESP_ERROR_CHECK(uart_set_pin(RADAR_UART_PORT,
                                  PIN_RADAR_TX, PIN_RADAR_RX,
                                  UART_PIN_NO_CHANGE, UART_PIN_NO_CHANGE));
    ESP_LOGI(TAG, "Attente trame LD6002 (%d ms, %d bauds)...",
             RADAR_DETECT_TIMEOUT_MS, RADAR_BAUD_RATE);
    uint8_t buf[RADAR_RX_BUF_SIZE];
    TickType_t deadline = xTaskGetTickCount() +
                          pdMS_TO_TICKS(RADAR_DETECT_TIMEOUT_MS);
    ctx->radar_ok = false;
    while (xTaskGetTickCount() < deadline) {
        int len = uart_read_bytes(RADAR_UART_PORT, buf, sizeof(buf),
                                   pdMS_TO_TICKS(100));
        if (len <= 0) {
            continue;
        }
        /* Recherche du SOF TinyFrame (0x01) dans les données reçues */
        for (int i = 0; i < len; i++) {
            if (buf[i] == TF_SOF && (len - i) >= 5) {
                ctx->radar_ok = true;
                ESP_LOGI(TAG, "Radar LD6002 : trame TinyFrame détectée (%d octets reçus)",
                         len);
                goto radar_done;
            }
        }
    }
radar_done:
    if (!ctx->radar_ok) {
        ESP_LOGW(TAG, "Radar LD6002 : aucune trame reçue dans le délai imparti");
    }
    /* Le driver UART reste installé (réutilisé par radar_driver dans sensor_acq) */
}
References PIN_RADAR_RX, PIN_RADAR_TX, RADAR_BAUD_RATE, RADAR_DETECT_TIMEOUT_MS, sys_context_t::radar_ok, RADAR_RX_BUF_SIZE, RADAR_UART_PORT, TAG, and TF_SOF.
Referenced by hw_diag_run().
pca9555_init()
esp_err_t pca9555_init (i2c_master_bus_handle_t bus) [static]
Definition at line 242 of file hw_diag.c.
{
    /* Création du device handle PCA9555 — UNE SEULE FOIS.
     * Alloué ici (avant WiFi) pour éviter tout problème de heap après.
     * Réutilisé par pca9555_write_reg() sans nouvelle allocation. */
    if (!s_pca_dev) {
        const i2c_device_config_t dev_cfg = {
            .dev_addr_length = I2C_ADDR_BIT_LEN_7,
            .device_address = PCA9555_I2C_ADDR,
            .scl_speed_hz = I2C_BUS_FREQ_HZ,
        };
        esp_err_t ret_dev = i2c_master_bus_add_device(bus, &dev_cfg, &s_pca_dev);
        if (ret_dev != ESP_OK) {
            ESP_LOGE(TAG, "PCA9555 add_device échoué : %s", esp_err_to_name(ret_dev));
            return ret_dev;
        }
    }
    /* --- Port 0 ---
     * IO0.0 = sortie (DIST_SHUTDOWN)
     * IO0.1, IO0.2 = entrée Hi-Z (GPIO radar LD6002, non utilisés)
     * IO0.3 – IO0.7 = sorties (LPn_4, LPn_3, LPn_2, LPn_1, RADAR_LPN)
     * Config : 0 = sortie → PCA9555_CFG0_MASK = 0x06 (bits 1 et 2 en entrée) */
    esp_err_t ret = pca9555_write_reg(bus, PCA9555_REG_CONFIG_0, PCA9555_CFG0_MASK);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "PCA9555 config Port0 échoué : %s", esp_err_to_name(ret));
        return ret;
    }
    /* Valeur initiale Port 0 :
     * IO0.0 (DIST_SHUTDOWN) = 0 → VL53L0X actif (non mis en veille)
     * IO0.3–IO0.7 (LPn + RADAR_LPN) = 0 → tous les LIDARs en reset */
    s_pca_out = 0x00;
    ret = pca9555_write_reg(bus, PCA9555_REG_OUTPUT_0, s_pca_out);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "PCA9555 output Port0 échoué : %s", esp_err_to_name(ret));
        return ret;
    }
    /* --- Port 1 ---
     * IO1.0–IO1.3 = entrée Hi-Z (non utilisés)
     * IO1.4–IO1.7 = sorties (POWER_FAN, POWER_RADAR, POWER_MIC, POWER_MLX)
     * Config : PCA9555_CFG1_MASK = 0x0F (bits 0–3 en entrée, bits 4–7 en sortie) */
    ret = pca9555_write_reg(bus, PCA9555_REG_CONFIG_1, PCA9555_CFG1_MASK);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "PCA9555 config Port1 échoué : %s", esp_err_to_name(ret));
        return ret;
    }
    /* Valeur initiale Port 1 : toutes alimentations éteintes */
    ret = pca9555_write_reg(bus, PCA9555_REG_OUTPUT_1, 0x00);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "PCA9555 output Port1 échoué : %s", esp_err_to_name(ret));
        return ret;
    }
    ESP_LOGI(TAG, "PCA9555 initialisé (@0x%02X, SDA=%d, SCL=%d) — Port0/1 configurés",
             PCA9555_I2C_ADDR, PIN_I2C0_SDA, PIN_I2C0_SCL);
    return ESP_OK;
}
References I2C_BUS_FREQ_HZ, PCA9555_CFG0_MASK, PCA9555_CFG1_MASK, PCA9555_I2C_ADDR, PCA9555_REG_CONFIG_0, PCA9555_REG_CONFIG_1, PCA9555_REG_OUTPUT_0, PCA9555_REG_OUTPUT_1, pca9555_write_reg(), PIN_I2C0_SCL, PIN_I2C0_SDA, s_pca_dev, s_pca_out, and TAG.
Referenced by diag_scan_lidars().
pca9555_set_lpn()
esp_err_t pca9555_set_lpn (i2c_master_bus_handle_t bus, int idx, bool active) [static]
Definition at line 312 of file hw_diag.c.
{
    /* idx est un index tableau (0 = LIDAR 1 hardware, 3 = LIDAR 4 hardware) */
    if (idx < 0 || idx >= LIDAR_NUM_FRONT) {
        return ESP_ERR_INVALID_ARG;
    }
    if (active) {
        s_pca_out |= s_pca_lpn_bit[idx];
    } else {
        s_pca_out &= ~s_pca_lpn_bit[idx];
    }
    return pca9555_write_reg(bus, PCA9555_REG_OUTPUT_0, s_pca_out);
}
References LIDAR_NUM_FRONT, PCA9555_REG_OUTPUT_0, pca9555_write_reg(), s_pca_lpn_bit, and s_pca_out.
Referenced by diag_scan_lidars().
pca9555_write_reg()
esp_err_t pca9555_write_reg (i2c_master_bus_handle_t bus, uint8_t reg, uint8_t val) [static]
Definition at line 217 of file hw_diag.c.
{
    (void)bus; /* s_pca_dev est utilisé directement */
    if (!s_pca_dev) {
        ESP_LOGE(TAG, "pca9555_write_reg : device non initialisé");
        return ESP_ERR_INVALID_STATE;
    }
    const uint8_t tx[2] = {reg, val};
    return i2c_master_transmit(s_pca_dev, tx, sizeof(tx),
                               pdMS_TO_TICKS(I2C_TIMEOUT_MS));
}
References I2C_TIMEOUT_MS, s_pca_dev, and TAG.
Referenced by hw_diag_pca9555_set_power(), pca9555_init(), and pca9555_set_lpn().
Variable Documentation
s_ncs_pins
const int s_ncs_pins[LIDAR_NUM_FRONT] [static]
Initial value:
= {
    PIN_LIDAR_NCS0,
    PIN_LIDAR_NCS1,
    PIN_LIDAR_NCS2,
    PIN_LIDAR_NCS3,
}
Definition at line 46 of file hw_diag.c.
                                               {
    PIN_LIDAR_NCS0,
    PIN_LIDAR_NCS1,
    PIN_LIDAR_NCS2,
    PIN_LIDAR_NCS3,
};
Referenced by diag_init_spi_lidars(), diag_print_json_report(), and diag_scan_lidars().
s_pca1_out
uint8_t s_pca1_out = 0x00 [static]
Definition at line 76 of file hw_diag.c.
Referenced by hw_diag_pca9555_set_power().
s_pca_bus
i2c_master_bus_handle_t s_pca_bus = NULL [static]
Definition at line 79 of file hw_diag.c.
Referenced by hw_diag_pca9555_set_power(), and hw_diag_run().
s_pca_dev
i2c_master_dev_handle_t s_pca_dev = NULL [static]
Definition at line 84 of file hw_diag.c.
Referenced by pca9555_init(), and pca9555_write_reg().
s_pca_lpn_bit
const uint8_t s_pca_lpn_bit[LIDAR_NUM_FRONT] [static]
Initial value:
= {
    PCA9555_BIT_LPN1,
    PCA9555_BIT_LPN2,
    PCA9555_BIT_LPN3,
    PCA9555_BIT_LPN4,
}
Definition at line 67 of file hw_diag.c.
                                                      {
    PCA9555_BIT_LPN1, /* index 0 → LIDAR 1 → IO0.6 */
    PCA9555_BIT_LPN2, /* index 1 → LIDAR 2 → IO0.5 */
    PCA9555_BIT_LPN3, /* index 2 → LIDAR 3 → IO0.4 */
    PCA9555_BIT_LPN4, /* index 3 → LIDAR 4 → IO0.3 */
};
Referenced by pca9555_set_lpn().
s_pca_out
uint8_t s_pca_out = 0x00 [static]
Definition at line 75 of file hw_diag.c.
Referenced by pca9555_init(), and pca9555_set_lpn().
TAG
const char* TAG = "hw_diag" [static]
Definition at line 26 of file hw_diag.c.