components/sensor_acq/lidar_driver.c File Reference
Acquisition LIDAR VL53L8CX — fusion 8×32 sur double bus I2C.
#include "lidar_driver.h"
#include "radar_driver.h"
#include "vl53l8cx_platform.h"
#include "hdc1080_driver.h"
#include "bme280_driver.h"
#include "mic_driver.h"
#include "lexacare_config.h"
#include "pins_config.h"
#include "esp_log.h"
#include "esp_err.h"
#include "esp_timer.h"
#include "esp_task_wdt.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <math.h>
#include <string.h>
#include <stdlib.h>
Data Structures
struct lidar_dev_t
struct lidar_task_ctx_t
Macros
#define ENVIRO_READ_PERIOD_FRAMES 15
#define LEXA_LIDAR_STUB 1
#define TASK_STACK_SIZE (8192)
#define TASK_PRIORITY (10)
#define TASK_CORE (1)
#define TASK_PERIOD_MS (200)
#define LIDAR_FREQ_HZ (5)
Functions
static bool lidar_init_sensor (lidar_dev_t *dev, spi_device_handle_t spi_dev, int idx)
static void lidar_read_sensor (lidar_dev_t *dev, lidar_matrix_t *matrix, int col_offset)
static void task_sensor_acq (void *pvParam)
esp_err_t lidar_driver_start (sys_context_t *ctx)
Variables
static const char * TAG = "lidar_driver"
Detailed Description
Acquisition LIDAR VL53L8CX — fusion 8×32 sur double bus I2C.
Architecture dual-bus (contrainte débit) : I2C_NUM_0 → capteurs 0 & 1 (lus en parallèle avec bus 1) I2C_NUM_1 → capteurs 2, 3 & 4
Fusion : capteur N → colonnes [N*8 .. N*8+7] de lidar_matrix_t. Cadence : 15 Hz via vTaskDelayUntil (période 66 ms). TWDT : esp_task_wdt_reset() à chaque itération.
Dépendance ULD : Les appels vl53l8cx_*() nécessitent l'ULD VL53L8CX de ST. Voir instructions dans vl53l8cx_platform.h. Sans l'ULD, compiler avec -DLIDAR_STUB_MODE pour utiliser des données simulées (développement sans matériel).
Definition in file lidar_driver.c.
Macro Definition Documentation
ENVIRO_READ_PERIOD_FRAMES
#define ENVIRO_READ_PERIOD_FRAMES 15
Definition at line 40 of file lidar_driver.c.
Referenced by task_sensor_acq().
LEXA_LIDAR_STUB
#define LEXA_LIDAR_STUB 1
Definition at line 50 of file lidar_driver.c.
LIDAR_FREQ_HZ
#define LIDAR_FREQ_HZ (5)
Fréquence ULD à configurer (voir init)
Definition at line 75 of file lidar_driver.c.
Referenced by lidar_init_sensor().
TASK_CORE
#define TASK_CORE (1)
Definition at line 73 of file lidar_driver.c.
TASK_PERIOD_MS
#define TASK_PERIOD_MS (200)
5 Hz — précision maximale VL53L8CX
Definition at line 74 of file lidar_driver.c.
Referenced by lidar_driver_start(), and task_sensor_acq().
TASK_PRIORITY
#define TASK_PRIORITY (10)
Definition at line 72 of file lidar_driver.c.
TASK_STACK_SIZE
#define TASK_STACK_SIZE (8192)
Definition at line 71 of file lidar_driver.c.
Function Documentation
lidar_init_sensor()
bool lidar_init_sensor (lidar_dev_t * dev, spi_device_handle_t spi_dev, int idx) [static]
Definition at line 111 of file lidar_driver.c.
{
    dev->platform.spi_dev = spi_dev;
    if (VL53L8CX_PlatformInit(&dev->platform) != 0) {
        ESP_LOGE(TAG, "LIDAR[%d] : échec PlatformInit SPI", idx);
        return false;
    }
#if !LEXA_LIDAR_STUB
    memset(&dev->uld, 0, sizeof(dev->uld));
    dev->uld.platform = dev->platform;
    if (vl53l8cx_init(&dev->uld) != VL53L8CX_STATUS_OK) {
        ESP_LOGE(TAG, "LIDAR[%d] : vl53l8cx_init échoué", idx);
        return false;
    }
    if (vl53l8cx_set_resolution(&dev->uld, VL53L8CX_RESOLUTION_8X8) != VL53L8CX_STATUS_OK) {
        ESP_LOGE(TAG, "LIDAR[%d] : set_resolution échoué", idx);
        return false;
    }
    if (vl53l8cx_set_ranging_frequency_hz(&dev->uld, LIDAR_FREQ_HZ) != VL53L8CX_STATUS_OK) {
        ESP_LOGE(TAG, "LIDAR[%d] : set_ranging_frequency(%d Hz) échoué", idx, LIDAR_FREQ_HZ);
        return false;
    }
    if (vl53l8cx_set_ranging_mode(&dev->uld, VL53L8CX_RANGING_MODE_AUTONOMOUS) != VL53L8CX_STATUS_OK) {
        ESP_LOGE(TAG, "LIDAR[%d] : set_ranging_mode échoué", idx);
        return false;
    }
    if (vl53l8cx_start_ranging(&dev->uld) != VL53L8CX_STATUS_OK) {
        ESP_LOGE(TAG, "LIDAR[%d] : start_ranging échoué", idx);
        return false;
    }
    ESP_LOGI(TAG, "LIDAR[%d] SPI : ULD ST actif (8×8, %d Hz)", idx, LIDAR_FREQ_HZ);
#else
    ESP_LOGW(TAG, "LIDAR[%d] SPI : STUB actif (LEXACARE_LIDAR_USE_ST_ULD=0)", idx);
#endif
    dev->active = true;
    return true;
}
References lidar_dev_t::active, LIDAR_FREQ_HZ, lidar_dev_t::platform, VL53L8CX_Platform::spi_dev, TAG, vl53l8cx_init(), VL53L8CX_PlatformInit(), VL53L8CX_RANGING_MODE_AUTONOMOUS, VL53L8CX_RESOLUTION_8X8, vl53l8cx_set_ranging_frequency_hz(), vl53l8cx_set_ranging_mode(), vl53l8cx_set_resolution(), vl53l8cx_start_ranging(), and VL53L8CX_STATUS_OK.
Referenced by task_sensor_acq().
lidar_read_sensor()
void lidar_read_sensor (lidar_dev_t * dev, lidar_matrix_t * matrix, int col_offset) [static]
Definition at line 170 of file lidar_driver.c.
{
    if (!dev->active) return;
#if !LEXA_LIDAR_STUB
    uint8_t ready = 0;
    if (vl53l8cx_check_data_ready(&dev->uld, &ready) != VL53L8CX_STATUS_OK || !ready) {
        return;
    }
    if (vl53l8cx_get_ranging_data(&dev->uld, &dev->results) != VL53L8CX_STATUS_OK) {
        return;
    }
    for (int zone = 0; zone < 64; zone++) {
        int row = zone / 8;
        int col = zone % 8;
        /* ULD ST : distance_mm est un tableau 1D de int16_t.
         * Si NB_TARGET_PER_ZONE > 1, on prend la cible 0 (la plus proche). */
        const int idx = zone * (int)VL53L8CX_NB_TARGET_PER_ZONE;
        uint16_t dist = (uint16_t)(dev->results.distance_mm[idx]);
        if (dist == 0 || dist > 4000) dist = 0;
        matrix->data[row][col_offset + col] = dist;
    }
#else
    /* ── Mode STUB : scan 8×8 réaliste pour validation visuelle ──────────
     *
     * Simule un arc 180° vu depuis un capteur plafond/mur :
     * · Fond (murs/sol) à 2500–4000 mm selon l'angle et la hauteur
     * · Distance plus courte aux rangées basses (sol plus proche)
     * · Variation angulaire cohérente sur 32 colonnes
     * · Bruit de mesure réaliste ±30 mm
     *
     * Valeurs dans la plage exploitable par la heatmap inferno :
     * 100 mm (très proche / chute) → 4000 mm (max portée)
     */
    static int32_t s_stub_seed = 0;
    s_stub_seed++; /* Compteur pour variation temporelle légère */
    for (int row = 0; row < LIDAR_ROWS; row++) {
        for (int col = 0; col < 8; col++) {
            /* Position angulaire dans l'arc 180°
             * col_offset + col ∈ [0..31] → angle ∈ [0°..180°] */
            float angle_deg = (float)(col_offset + col) * (180.0f / (LIDAR_COLS - 1));
            float angle_rad = angle_deg * 3.14159f / 180.0f;
            /* Distance de fond : mur à ~3500 mm en face (90°),
             * murs latéraux plus proches (0° et 180°) ≈ 2000 mm */
            float bg_mm = 2000.0f + 1500.0f * sinf(angle_rad);
            /* Facteur hauteur : rangées basses (7) = sol, plus proche */
            float height_factor = 1.0f - (float)row / (float)(LIDAR_ROWS - 1) * 0.25f;
            bg_mm *= height_factor;
            /* Bruit de mesure réaliste ±25 mm */
            int32_t noise = ((s_stub_seed * 1103515245 + 12345) & 0x7FFF) % 50 - 25;
            s_stub_seed = s_stub_seed * 6364136223846793005LL + 1;
            uint16_t dist = (uint16_t)(bg_mm + (float)noise);
            if (dist < 100) dist = 100;
            if (dist > 4000) dist = 4000;
            matrix->data[row][col_offset + col] = dist;
        }
    }
#endif /* LEXA_LIDAR_STUB */
}
References lidar_dev_t::active, lidar_matrix_t::data, LIDAR_COLS, LIDAR_ROWS, vl53l8cx_check_data_ready(), vl53l8cx_get_ranging_data(), VL53L8CX_NB_TARGET_PER_ZONE, and VL53L8CX_STATUS_OK.
Referenced by task_sensor_acq().
task_sensor_acq()
void task_sensor_acq (void * pvParam) [static]
Definition at line 250 of file lidar_driver.c.
{
    lidar_task_ctx_t *ctx = (lidar_task_ctx_t *)pvParam;
    /* Abonnement au Task Watchdog Timer (TWDT) */
    ESP_ERROR_CHECK(esp_task_wdt_add(NULL));
    ESP_LOGI(TAG, "Task_Sensor_Acq démarrée sur Core %d", xPortGetCoreID());
    /* ================================================================
     * Initialisation capteurs (déplacée ici pour éviter de bloquer app_main)
     * ================================================================ */
    ESP_LOGI(TAG, "Initialisation LIDARs (ULD) dans la tâche capteurs…");
    for (int i = 0; i < LIDAR_NUM_FRONT; i++) {
        ctx->devs[i].sensor_idx = i;
        if (!ctx->sys_ctx->lidar_ok[i]) {
            ctx->devs[i].active = false;
            ESP_LOGW(TAG, "LIDAR[%d] absent (hw_diag) — ignoré", i);
            continue;
        }
        /* Nourrir le watchdog entre capteurs */
        ESP_ERROR_CHECK(esp_task_wdt_reset());
        vTaskDelay(pdMS_TO_TICKS(10));
        if (!lidar_init_sensor(&ctx->devs[i], ctx->sys_ctx->lidar_spi[i], i)) {
            ESP_LOGW(TAG, "LIDAR[%d] : initialisation SPI/ULD échouée", i);
            ctx->devs[i].active = false;
        }
    }
    /* Radar : uniquement si connecté */
#if LEXACARE_ENABLE_RADAR
    ESP_ERROR_CHECK(radar_driver_init());
#else
    ESP_LOGI(TAG, "Radar LD6002 désactivé (LEXACARE_ENABLE_RADAR=0)");
#endif
    TickType_t last_wake = xTaskGetTickCount();
    uint32_t frame_idx = 0;
    while (true) {
        /* Reset du watchdog avant toute opération bloquante */
        ESP_ERROR_CHECK(esp_task_wdt_reset());
        sensor_frame_t frame;
        memset(&frame, 0, sizeof(frame));
        frame.lidar.timestamp_us = esp_timer_get_time();
        /* Lecture des 4 capteurs frontaux (fusion dans la matrice) */
        for (int i = 0; i < LIDAR_NUM_FRONT; i++) {
            lidar_read_sensor(&ctx->devs[i], &frame.lidar, i * 8);
        }
        frame.lidar.valid = true;
        frame.lidar_valid = true;
        /* Lecture du radar (non bloquant) — uniquement si connecté */
#if LEXACARE_ENABLE_RADAR
        frame.radar_valid = radar_driver_poll(&frame.radar);
#else
        frame.radar_valid = false;
#endif
        /* Envoi dans la queue AI (non bloquant) */
        if (xQueueSend(ctx->sys_ctx->sensor_to_ai_queue, &frame, 0) != pdTRUE) {
            ESP_LOGD(TAG, "sensor_to_ai_queue pleine — trame abandonnée");
        }
        /* ── Mise à jour du snapshot partagé (protégé par mutex) ─────── */
        if (ctx->sys_ctx->data_mutex &&
            xSemaphoreTake(ctx->sys_ctx->data_mutex, pdMS_TO_TICKS(5)) == pdTRUE) {
            ctx->sys_ctx->latest_sensor = frame;
            ctx->sys_ctx->sensor_valid = true;
            xSemaphoreGive(ctx->sys_ctx->data_mutex);
        }
        /* ── Lecture capteurs environnementaux (1 Hz) ─────────────────── */
        frame_idx++;
        if (frame_idx >= ENVIRO_READ_PERIOD_FRAMES) {
            frame_idx = 0;
            enviro_data_t env = {
                .temp_hdc_c = NAN, .humidity_hdc = NAN,
                .temp_bme_c = NAN, .pressure_hpa = NAN,
                .humidity_bme = NAN,
            };
            /* HDC1080 */
            float t_hdc = 0.0f, h_hdc = 0.0f;
            if (hdc1080_read(&t_hdc, &h_hdc) == ESP_OK) {
                env.temp_hdc_c = t_hdc;
                env.humidity_hdc = h_hdc;
            }
            /* BME280 */
            float t_bme = 0.0f, p_bme = 0.0f, h_bme = 0.0f;
            if (bme280_read(&t_bme, &p_bme, &h_bme) == ESP_OK) {
                env.temp_bme_c = t_bme;
                env.pressure_hpa = p_bme;
                env.humidity_bme = h_bme;
            }
            /* Microphone — burst rapide */
            uint32_t rms = 0, peak = 0;
            bool mic_ok = (mic_driver_read(&rms, &peak) == ESP_OK);
            /* Mise à jour sys_context_t */
            if (ctx->sys_ctx->data_mutex &&
                xSemaphoreTake(ctx->sys_ctx->data_mutex, pdMS_TO_TICKS(10)) == pdTRUE) {
                ctx->sys_ctx->enviro = env;
                ctx->sys_ctx->mic.rms = rms;
                ctx->sys_ctx->mic.peak = peak;
                ctx->sys_ctx->mic.valid = mic_ok;
                xSemaphoreGive(ctx->sys_ctx->data_mutex);
            }
        }
        /* Cadence 15 Hz via vTaskDelayUntil (drift-free) */
        vTaskDelayUntil(&last_wake, pdMS_TO_TICKS(TASK_PERIOD_MS));
    }
}
References lidar_dev_t::active, bme280_read(), sys_context_t::data_mutex, lidar_task_ctx_t::devs, sys_context_t::enviro, ENVIRO_READ_PERIOD_FRAMES, hdc1080_read(), enviro_data_t::humidity_bme, enviro_data_t::humidity_hdc, sys_context_t::latest_sensor, sensor_frame_t::lidar, lidar_init_sensor(), LIDAR_NUM_FRONT, sys_context_t::lidar_ok, lidar_read_sensor(), sys_context_t::lidar_spi, sensor_frame_t::lidar_valid, sys_context_t::mic, mic_driver_read(), mic_data_t::peak, enviro_data_t::pressure_hpa, sensor_frame_t::radar, radar_driver_init(), radar_driver_poll(), sensor_frame_t::radar_valid, mic_data_t::rms, lidar_dev_t::sensor_idx, sys_context_t::sensor_to_ai_queue, sys_context_t::sensor_valid, lidar_task_ctx_t::sys_ctx, TAG, TASK_PERIOD_MS, enviro_data_t::temp_bme_c, enviro_data_t::temp_hdc_c, lidar_matrix_t::timestamp_us, lidar_matrix_t::valid, and mic_data_t::valid.
Referenced by lidar_driver_start().
Variable Documentation
TAG
const char* TAG = "lidar_driver" [static]
Definition at line 53 of file lidar_driver.c.