components/mesh_network/mesh_manager.c File Reference
Gestionnaire réseau maillé ESP-NOW — topologie arborescente + AES-128.
#include "mesh_manager.h"
#include "ota_node.h"
#include "pins_config.h"
#include "esp_log.h"
#include "esp_err.h"
#include "esp_wifi.h"
#include "esp_now.h"
#include "esp_mac.h"
#include "esp_netif.h"
#include "esp_random.h"
#include "nvs_flash.h"
#include "nvs.h"
#include "esp_timer.h"
#include "esp_idf_version.h"
#include "mbedtls/aes.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include <string.h>
#include <stdlib.h>
Data Structures
struct peer_info_t
struct mesh_state_t
Macros
#define aes_compat_init(c)
#define aes_compat_free(c)
#define aes_compat_setkey(c, k, b)
#define aes_compat_crypt_cbc(c, m, l, iv, i, o)
#define AES_COMPAT_ENCRYPT MBEDTLS_AES_ENCRYPT
#define ESPNOW_CHANNEL 1
#define ESPNOW_MAX_PEERS 20
#define MESH_TASK_STACK (6144)
#define MESH_TASK_PRIORITY (8)
#define MESH_TASK_CORE (0)
#define BEACON_INTERVAL_MS 5000
Typedefs
typedef mbedtls_aes_context aes_compat_ctx_t
Functions
static uint16_t crc16_ccitt (const uint8_t *data, size_t length)
static size_t aes_encrypt_payload (const uint8_t *plain, size_t plain_len, uint8_t *cipher, uint8_t *iv)
static bool mesh_build_ai_frame (const ai_event_t *event, lexacare_frame_t *frame)
static void espnow_rx_callback (const esp_now_recv_info_t *recv_info, const uint8_t *data, int data_len)
static void espnow_tx_callback (const uint8_t *mac_addr, esp_now_send_status_t status)
static void mesh_load_aes_key (void)
static void task_mesh_com (void *pvParam)
esp_err_t mesh_manager_init (sys_context_t *ctx)
esp_err_t mesh_task_start (sys_context_t *ctx)
Variables
static const uint8_t k_broadcast_mac [ESP_NOW_ETH_ALEN]
static const char * TAG = "mesh_mgr"
static const uint8_t k_pmk [16]
static const uint8_t k_aes_default [LEXACARE_AES_KEY_LEN]
static mesh_state_t s_mesh
Detailed Description
Gestionnaire réseau maillé ESP-NOW — topologie arborescente + AES-128.
Chiffrement applicatif (contrainte +1000 nœuds) : Le LMK ESP-NOW est limité à ~17 pairs simultanés. Chaque payload est chiffré par le nœud émetteur en AES-128-CBC via mbedTLS, indépendamment du chiffrement matériel ESP-NOW. La clé symétrique (16 octets) est stockée en NVS.
Topologie arborescente : Un nœud ROOT (passerelle) est identifié par PIN_ROOT_SEL=LOW. Les nœuds normaux sélectionnent leur parent = pair avec le meilleur RSSI parmi ceux ayant le hop_to_root minimal (découverte par beacon).
Definition in file mesh_manager.c.
Macro Definition Documentation
aes_compat_crypt_cbc
#define aes_compat_crypt_cbc(c, m, l, iv, i, o)
Value:
mbedtls_aes_crypt_cbc(c, m, l, iv, i, o)
Definition at line 49 of file mesh_manager.c.
Referenced by aes_encrypt_payload().
AES_COMPAT_ENCRYPT
#define AES_COMPAT_ENCRYPT MBEDTLS_AES_ENCRYPT
Definition at line 50 of file mesh_manager.c.
Referenced by aes_encrypt_payload().
aes_compat_free
#define aes_compat_free(c)
Value:
mbedtls_aes_free(c)
Definition at line 47 of file mesh_manager.c.
Referenced by aes_encrypt_payload().
aes_compat_init
#define aes_compat_init(c)
Value:
mbedtls_aes_init(c)
Definition at line 46 of file mesh_manager.c.
Referenced by aes_encrypt_payload().
aes_compat_setkey
#define aes_compat_setkey(c, k, b)
Value:
mbedtls_aes_setkey_enc(c, k, b)
Definition at line 48 of file mesh_manager.c.
Referenced by aes_encrypt_payload().
BEACON_INTERVAL_MS
#define BEACON_INTERVAL_MS 5000
Période d'envoi des beacons
Definition at line 73 of file mesh_manager.c.
ESPNOW_CHANNEL
#define ESPNOW_CHANNEL 1
Definition at line 68 of file mesh_manager.c.
Referenced by mesh_manager_init().
ESPNOW_MAX_PEERS
#define ESPNOW_MAX_PEERS 20
Definition at line 69 of file mesh_manager.c.
MESH_TASK_CORE
#define MESH_TASK_CORE (0)
Definition at line 72 of file mesh_manager.c.
Referenced by mesh_task_start().
MESH_TASK_PRIORITY
#define MESH_TASK_PRIORITY (8)
Definition at line 71 of file mesh_manager.c.
Referenced by mesh_task_start().
MESH_TASK_STACK
#define MESH_TASK_STACK (6144)
Definition at line 70 of file mesh_manager.c.
Referenced by mesh_task_start().
Typedef Documentation
aes_compat_ctx_t
typedef mbedtls_aes_context aes_compat_ctx_t
Definition at line 45 of file mesh_manager.c.
Function Documentation
aes_encrypt_payload()
size_t aes_encrypt_payload (const uint8_t * plain, size_t plain_len, uint8_t * cipher, uint8_t * iv) [static]
Definition at line 153 of file mesh_manager.c.
{
    /* Calcul de la longueur paddée (PKCS#7) */
    size_t padded_len = ((plain_len + 15) / 16) * 16;
    if (padded_len > LEXACARE_MAX_PAYLOAD) {
        ESP_LOGE(TAG, "Payload trop grand : %u octets (max %d)",
                 (unsigned)padded_len, LEXACARE_MAX_PAYLOAD);
        return 0;
    }
    /* Buffer temporaire avec padding */
    uint8_t padded[LEXACARE_MAX_PAYLOAD] = {0};
    memcpy(padded, plain, plain_len);
    uint8_t pad_byte = (uint8_t)(padded_len - plain_len);
    for (size_t i = plain_len; i < padded_len; i++) {
        padded[i] = pad_byte;
    }
    /* Génération de l'IV aléatoire */
    esp_fill_random(iv, LEXACARE_AES_IV_LEN);
    /* Chiffrement AES-128-CBC */
    aes_compat_ctx_t aes_ctx;
    aes_compat_init(&aes_ctx);
    uint8_t iv_copy[LEXACARE_AES_IV_LEN];
    memcpy(iv_copy, iv, LEXACARE_AES_IV_LEN); /* L'API AES modifie l'IV en place */
    int ret = aes_compat_setkey(&aes_ctx, s_mesh.aes_key,
                                 LEXACARE_AES_KEY_LEN * 8);
    if (ret != 0) {
        aes_compat_free(&aes_ctx);
        ESP_LOGE(TAG, "AES setkey échoué : %d", ret);
        return 0;
    }
    ret = aes_compat_crypt_cbc(&aes_ctx, AES_COMPAT_ENCRYPT,
                                padded_len, iv_copy, padded, cipher);
    aes_compat_free(&aes_ctx);
    if (ret != 0) {
        ESP_LOGE(TAG, "AES CBC encrypt échoué : %d", ret);
        return 0;
    }
    return padded_len;
}
References aes_compat_crypt_cbc, AES_COMPAT_ENCRYPT, aes_compat_free, aes_compat_init, aes_compat_setkey, LEXACARE_AES_IV_LEN, LEXACARE_AES_KEY_LEN, LEXACARE_MAX_PAYLOAD, s_mesh, and TAG.
Referenced by mesh_build_ai_frame().
crc16_ccitt()
uint16_t crc16_ccitt (const uint8_t * data, size_t length) [static]
Definition at line 124 of file mesh_manager.c.
{
    uint16_t crc = 0xFFFF;
    for (size_t i = 0; i < length; i++) {
        crc ^= (uint16_t)data[i] << 8;
        for (int j = 0; j < 8; j++) {
            if (crc & 0x8000) {
                crc = (uint16_t)((crc << 1) ^ 0x1021);
            } else {
                crc <<= 1;
            }
        }
    }
    return crc;
}
Referenced by mesh_build_ai_frame().
espnow_rx_callback()
void espnow_rx_callback (const esp_now_recv_info_t * recv_info, const uint8_t * data, int data_len) [static]
Definition at line 249 of file mesh_manager.c.
{
    if (data_len < (int)sizeof(lexacare_frame_t)) return;
    const lexacare_frame_t *frame = (const lexacare_frame_t *)data;
    if (frame->magic != LEXACARE_FRAME_MAGIC) {
        ESP_LOGW(TAG, "Trame reçue avec magic invalide : 0x%04X", frame->magic);
        return;
    }
    /* Vérification CRC16 (simplifiée — recomputation sur les champs) */
    ESP_LOGD(TAG, "Trame reçue type=0x%02X, hop=%u, src=" MACSTR,
             frame->type, frame->hop_count,
             MAC2STR(frame->src_mac));
    if (frame->type == FRAME_TYPE_OTA_FRAGMENT) {
        /* Délégation au module OTA */
        /* Déchiffrement du payload avant traitement (non implémenté ici) */
        ESP_LOGI(TAG, "Fragment OTA reçu (%u octets chiffrés)",
                 frame->payload_len);
    }
}
References FRAME_TYPE_OTA_FRAGMENT, lexacare_frame_t::hop_count, LEXACARE_FRAME_MAGIC, lexacare_frame_t::magic, lexacare_frame_t::payload_len, lexacare_frame_t::src_mac, TAG, and lexacare_frame_t::type.
Referenced by mesh_manager_init().
espnow_tx_callback()
void espnow_tx_callback (const uint8_t * mac_addr, esp_now_send_status_t status) [static]
Definition at line 294 of file mesh_manager.c.
{
    ESP_LOGD(TAG, "TX vers " MACSTR " : %s",
             MAC2STR(mac_addr),
             (status == ESP_NOW_SEND_SUCCESS) ? "OK" : "ÉCHEC");
}
References TAG.
Referenced by mesh_manager_init().
mesh_build_ai_frame()
bool mesh_build_ai_frame (const ai_event_t * event, lexacare_frame_t * frame) [static]
Definition at line 210 of file mesh_manager.c.
{
    memset(frame, 0, sizeof(*frame));
    frame->magic = LEXACARE_FRAME_MAGIC;
    frame->type = FRAME_TYPE_AI_EVENT;
    frame->hop_count = 0;
    memcpy(frame->src_mac, s_mesh.own_mac, 6);
    /* Chiffrement du payload */
    size_t enc_len = aes_encrypt_payload((const uint8_t *)event,
                                           sizeof(ai_event_t),
                                           frame->payload,
                                           frame->iv);
    if (enc_len == 0) return false;
    frame->payload_len = (uint16_t)enc_len;
    /* CRC16 sur magic + type + hop + src_mac + iv + payload */
    uint8_t crc_buf[2 + 1 + 1 + 6 + LEXACARE_AES_IV_LEN + LEXACARE_MAX_PAYLOAD];
    size_t crc_len = 0;
    memcpy(crc_buf + crc_len, &frame->magic, 2); crc_len += 2;
    crc_buf[crc_len++] = frame->type;
    crc_buf[crc_len++] = frame->hop_count;
    memcpy(crc_buf + crc_len, frame->src_mac, 6); crc_len += 6;
    memcpy(crc_buf + crc_len, frame->iv, LEXACARE_AES_IV_LEN);
    crc_len += LEXACARE_AES_IV_LEN;
    memcpy(crc_buf + crc_len, frame->payload, enc_len);
    crc_len += enc_len;
    frame->crc16 = crc16_ccitt(crc_buf, crc_len);
    return true;
}
References aes_encrypt_payload(), lexacare_frame_t::crc16, crc16_ccitt(), FRAME_TYPE_AI_EVENT, lexacare_frame_t::hop_count, lexacare_frame_t::iv, LEXACARE_AES_IV_LEN, LEXACARE_FRAME_MAGIC, LEXACARE_MAX_PAYLOAD, lexacare_frame_t::magic, lexacare_frame_t::payload, lexacare_frame_t::payload_len, s_mesh, lexacare_frame_t::src_mac, and lexacare_frame_t::type.
Referenced by task_mesh_com().
mesh_load_aes_key()
void mesh_load_aes_key (void) [static]
Definition at line 307 of file mesh_manager.c.
{
    nvs_handle_t nvs;
    esp_err_t ret = nvs_open("lexacare", NVS_READONLY, &nvs);
    if (ret == ESP_OK) {
        size_t key_len = LEXACARE_AES_KEY_LEN;
        ret = nvs_get_blob(nvs, "aes_key", s_mesh.aes_key, &key_len);
        nvs_close(nvs);
        if (ret == ESP_OK && key_len == LEXACARE_AES_KEY_LEN) {
            ESP_LOGI(TAG, "Clé AES chargée depuis NVS");
            return;
        }
    }
    /* Clé par défaut (avertissement de sécurité) */
    memcpy(s_mesh.aes_key, k_aes_default, LEXACARE_AES_KEY_LEN);
    ESP_LOGW(TAG, "Clé AES par défaut utilisée — NE PAS utiliser en production");
}
References k_aes_default, LEXACARE_AES_KEY_LEN, s_mesh, and TAG.
Referenced by mesh_manager_init().
task_mesh_com()
void task_mesh_com (void * pvParam) [static]
Definition at line 332 of file mesh_manager.c.
{
    mesh_state_t *state = (mesh_state_t *)pvParam;
    ESP_LOGI(TAG, "Task_Mesh_Com démarrée sur Core %d", xPortGetCoreID());
    ai_event_t event;
    lexacare_frame_t frame;
    while (true) {
        /* Attente d'un événement IA (portMAX_DELAY) */
        if (xQueueReceive(state->sys_ctx->ai_to_mesh_queue,
                           &event, portMAX_DELAY) != pdTRUE) {
            continue;
        }
        if (!state->has_parent && !state->sys_ctx->is_root_node) {
            ESP_LOGW(TAG, "Pas de parent — événement non transmis");
            continue;
        }
        /* Construction et chiffrement de la trame */
        if (!mesh_build_ai_frame(&event, &frame)) {
            ESP_LOGE(TAG, "Échec construction trame");
            continue;
        }
        /* Envoi vers le parent (ou broadcast si ROOT) */
        const uint8_t *dest = state->has_parent
                              ? state->parent_mac
                              : k_broadcast_mac;
        esp_err_t send_ret = esp_now_send(dest,
                                           (const uint8_t *)&frame,
                                           sizeof(lexacare_frame_t));
        if (send_ret != ESP_OK) {
            ESP_LOGW(TAG, "esp_now_send échoué : %s", esp_err_to_name(send_ret));
        }
    }
}
References sys_context_t::ai_to_mesh_queue, mesh_state_t::has_parent, sys_context_t::is_root_node, k_broadcast_mac, mesh_build_ai_frame(), mesh_state_t::parent_mac, mesh_state_t::sys_ctx, and TAG.
Referenced by mesh_task_start().
Variable Documentation
k_aes_default
const uint8_t k_aes_default[LEXACARE_AES_KEY_LEN] [static]
Initial value:
= {
    0x4C, 0x65, 0x78, 0x61, 0x63, 0x61, 0x72, 0x65,
    0x41, 0x45, 0x53, 0x31, 0x32, 0x38, 0x4B, 0x65,
}
Definition at line 82 of file mesh_manager.c.
                                                           {
    0x4C, 0x65, 0x78, 0x61, 0x63, 0x61, 0x72, 0x65,
    0x41, 0x45, 0x53, 0x31, 0x32, 0x38, 0x4B, 0x65,
};
Referenced by mesh_load_aes_key().
k_broadcast_mac
const uint8_t k_broadcast_mac[ESP_NOW_ETH_ALEN] [static]
Initial value:
= {
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
}
Definition at line 59 of file mesh_manager.c.
                                                         {
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
};
Referenced by task_mesh_com().
k_pmk
const uint8_t k_pmk[16] [static]
Initial value:
= {
    0x4C, 0x65, 0x78, 0x61, 0x63, 0x61, 0x72, 0x65,
    0x50, 0x4D, 0x4B, 0x30, 0x31, 0x32, 0x33, 0x34,
}
Definition at line 76 of file mesh_manager.c.
                                 {
    0x4C, 0x65, 0x78, 0x61, 0x63, 0x61, 0x72, 0x65,
    0x50, 0x4D, 0x4B, 0x30, 0x31, 0x32, 0x33, 0x34,
};
Referenced by mesh_manager_init().
s_mesh
mesh_state_t s_mesh [static]
Definition at line 114 of file mesh_manager.c.
Referenced by aes_encrypt_payload(), mesh_build_ai_frame(), mesh_load_aes_key(), mesh_manager_init(), and mesh_task_start().
TAG
const char* TAG = "mesh_mgr" [static]
Definition at line 63 of file mesh_manager.c.