components/sensor_acq/uld/platform.h File Reference
Adaptateur plateforme pour l'ULD ST VL53L8CX (STSW-IMG040).
#include <stdint.h>
#include <stddef.h>
#include "vl53l8cx_platform.h"
Macros
#define VL53L8CX_NB_TARGET_PER_ZONE 1
Functions
static void VL53L8CX_SwapBuffer (uint8_t *buffer, uint16_t size)
Swap endianess par mots 32 bits (implémentation typique ST).
Detailed Description
Adaptateur plateforme pour l'ULD ST VL53L8CX (STSW-IMG040).
L'ULD ST inclut un fichier platform.h que le client doit fournir. Dans ce firmware, la couche plateforme (SPI) est implémentée par : components/sensor_acq/include/vl53l8cx_platform.h
Ce fichier fait le lien entre l'ULD (API ST) et l'implémentation ESP-IDF.
Definition in file platform.h.
Macro Definition Documentation
VL53L8CX_NB_TARGET_PER_ZONE
#define VL53L8CX_NB_TARGET_PER_ZONE 1
Definition at line 19 of file platform.h.
Referenced by _vl53l8cx_program_output_config(), lidar_read_sensor(), vl53l8cx_get_ranging_data(), vl53l8cx_init(), and vl53l8cx_start_ranging().
Function Documentation
VL53L8CX_SwapBuffer()
void VL53L8CX_SwapBuffer (uint8_t * buffer, uint16_t size) [inline], [static]
Swap endianess par mots 32 bits (implémentation typique ST).
L'ULD manipule des buffers bruts (endianness capteur) et attend que la plateforme fournisse cette primitive.
Definition at line 34 of file platform.h.
{
    if (!buffer) return;
    /* Swap par blocs de 4 octets (uint32_t) */
    for (uint16_t i = 0; (uint16_t)(i + 3U) < size; i = (uint16_t)(i + 4U)) {
        const uint8_t b0 = buffer[i + 0U];
        const uint8_t b1 = buffer[i + 1U];
        buffer[i + 0U] = buffer[i + 3U];
        buffer[i + 1U] = buffer[i + 2U];
        buffer[i + 2U] = b1;
        buffer[i + 3U] = b0;
    }
}
Referenced by _vl53l8cx_send_offset_data(), _vl53l8cx_send_xtalk_data(), vl53l8cx_dci_read_data(), vl53l8cx_dci_write_data(), vl53l8cx_get_ranging_data(), and vl53l8cx_init().