components/sensor_acq/uld/vl53l8cx_plugin_xtalk.h File Reference
#include "vl53l8cx_api.h"
Macros
#define VL53L8CX_FW_NBTAR_XTALK 2
Inner internal number of targets.
#define VL53L8CX_DCI_CAL_CFG ((uint16_t)0x5470U)
Inner Macro for plugin. Not for user, only for development.
#define VL53L8CX_DCI_XTALK_CFG ((uint16_t)0xAD94U)
Functions
uint8_t vl53l8cx_calibrate_xtalk (VL53L8CX_Configuration *p_dev, uint16_t reflectance_percent, uint8_t nb_samples, uint16_t distance_mm)
This function starts the VL53L8CX sensor in order to calibrate Xtalk. This calibration is recommended is user wants to use a coverglass.
uint8_t vl53l8cx_get_caldata_xtalk (VL53L8CX_Configuration *p_dev, uint8_t *p_xtalk_data)
This function gets the Xtalk buffer. The buffer is available after using the function vl53l8cx_calibrate_xtalk().
uint8_t vl53l8cx_set_caldata_xtalk (VL53L8CX_Configuration *p_dev, uint8_t *p_xtalk_data)
This function sets the Xtalk buffer. This function can be used to override default Xtalk buffer.
uint8_t vl53l8cx_get_xtalk_margin (VL53L8CX_Configuration *p_dev, uint32_t *p_xtalk_margin)
This function gets the Xtalk margin. This margin is used to increase the Xtalk threshold. It can also be used to avoid false positives after the Xtalk calibration. The default value is 50 kcps/spads.
uint8_t vl53l8cx_set_xtalk_margin (VL53L8CX_Configuration *p_dev, uint32_t xtalk_margin)
This function sets the Xtalk margin. This margin is used to increase the Xtalk threshold. It can also be used to avoid false positives after the Xtalk calibration. The default value is 50 kcps/spads.
Variables
static const uint8_t VL53L8CX_GET_XTALK_CMD []
Command used to get Xtalk calibration data.
static const uint8_t VL53L8CX_CALIBRATE_XTALK []
Command used to get run Xtalk calibration.
Macro Definition Documentation
VL53L8CX_DCI_CAL_CFG
#define VL53L8CX_DCI_CAL_CFG ((uint16_t)0x5470U)
Inner Macro for plugin. Not for user, only for development.
Definition at line 32 of file vl53l8cx_plugin_xtalk.h.
Referenced by vl53l8cx_calibrate_xtalk().
VL53L8CX_DCI_XTALK_CFG
#define VL53L8CX_DCI_XTALK_CFG ((uint16_t)0xAD94U)
Definition at line 33 of file vl53l8cx_plugin_xtalk.h.
Referenced by vl53l8cx_get_xtalk_margin(), and vl53l8cx_set_xtalk_margin().
VL53L8CX_FW_NBTAR_XTALK
#define VL53L8CX_FW_NBTAR_XTALK 2
Inner internal number of targets.
Copyright (c) 2021 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition at line 23 of file vl53l8cx_plugin_xtalk.h.
Function Documentation
vl53l8cx_calibrate_xtalk()
uint8_t vl53l8cx_calibrate_xtalk (VL53L8CX_Configuration * p_dev, uint16_t reflectance_percent, uint8_t nb_samples, uint16_t distance_mm)
This function starts the VL53L8CX sensor in order to calibrate Xtalk. This calibration is recommended is user wants to use a coverglass.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint16_t) reflectance_percent : Target reflectance in percent. This value is include between 1 and 99%. For a better efficiency, ST recommends a 3% target reflectance.
(uint8_t) nb_samples : Nb of samples used for calibration. A higher number of samples means a higher accuracy, but it increases the calibration time. Minimum is 1 and maximum is 16.
(uint16_t) distance_mm : Target distance in mm. The minimum allowed distance is 600mm, and maximum is 3000mm. The target must stay in Full FOV, so short distance are easier for calibration.
Returns
(uint8_t) status : 0 if calibration OK, 127 if an argument has an incorrect value, or 255 is something failed.
Definition at line 147 of file vl53l8cx_plugin_xtalk.c.
{
    uint16_t timeout = 0;
    uint8_t cmd[] = {0x00, 0x03, 0x00, 0x00};
    uint8_t footer[] = {0x00, 0x00, 0x00, 0x0F, 0x00, 0x01, 0x03, 0x04};
    uint8_t continue_loop = 1, status = VL53L8CX_STATUS_OK;
    uint8_t resolution, frequency, target_order, sharp_prct, ranging_mode;
    uint32_t integration_time_ms, xtalk_margin;
        
    uint16_t reflectance = reflectance_percent;
    uint8_t samples = nb_samples;
    uint16_t distance = distance_mm;
    uint8_t *default_xtalk_ptr;
    /* Get initial configuration */
    status |= vl53l8cx_get_resolution(p_dev, &resolution);
    status |= vl53l8cx_get_ranging_frequency_hz(p_dev, &frequency);
    status |= vl53l8cx_get_integration_time_ms(p_dev, &integration_time_ms);
    status |= vl53l8cx_get_sharpener_percent(p_dev, &sharp_prct);
    status |= vl53l8cx_get_target_order(p_dev, &target_order);
    status |= vl53l8cx_get_xtalk_margin(p_dev, &xtalk_margin);
    status |= vl53l8cx_get_ranging_mode(p_dev, &ranging_mode);
    /* Check input arguments validity */
    if(((reflectance < (uint16_t)1) || (reflectance > (uint16_t)99))
        || ((distance < (uint16_t)600) || (distance > (uint16_t)3000))
        || ((samples < (uint8_t)1) || (samples > (uint8_t)16)))
    {
        status |= VL53L8CX_STATUS_INVALID_PARAM;
    }
    else
    {
        status |= vl53l8cx_set_resolution(p_dev,
                VL53L8CX_RESOLUTION_8X8);
        /* Send Xtalk calibration buffer */
                (void)memcpy(p_dev->temp_buffer, VL53L8CX_CALIBRATE_XTALK,
                       sizeof(VL53L8CX_CALIBRATE_XTALK));
        status |= VL53L8CX_WrMulti(&(p_dev->platform), 0x2c28,
                p_dev->temp_buffer,
                       (uint16_t)sizeof(VL53L8CX_CALIBRATE_XTALK));
        status |= _vl53l8cx_poll_for_answer(p_dev,
                VL53L8CX_UI_CMD_STATUS, 0x3);
        /* Format input argument */
        reflectance = reflectance * (uint16_t)16;
        distance = distance * (uint16_t)4;
        /* Update required fields */
        status |= vl53l8cx_dci_replace_data(p_dev, p_dev->temp_buffer,
                VL53L8CX_DCI_CAL_CFG, 8,
                                (uint8_t*)&distance, 2, 0x00);
        status |= vl53l8cx_dci_replace_data(p_dev, p_dev->temp_buffer,
                VL53L8CX_DCI_CAL_CFG, 8,
                                (uint8_t*)&reflectance, 2,0x02);
        status |= vl53l8cx_dci_replace_data(p_dev, p_dev->temp_buffer,
                VL53L8CX_DCI_CAL_CFG, 8,
                                (uint8_t*)&samples, 1, 0x04);
        /* Program output for Xtalk calibration */
        status |= _vl53l8cx_program_output_config(p_dev);
        /* Start ranging session */
        status |= VL53L8CX_WrMulti(&(p_dev->platform),
                VL53L8CX_UI_CMD_END - (uint16_t)(4 - 1),
                (uint8_t*)cmd, sizeof(cmd));
        status |= _vl53l8cx_poll_for_answer(p_dev,
                VL53L8CX_UI_CMD_STATUS, 0x3);
        /* Wait for end of calibration */
        do {
            status |= VL53L8CX_RdMulti(&(p_dev->platform),
                                          0x0, p_dev->temp_buffer, 4);
            if(p_dev->temp_buffer[0] != VL53L8CX_STATUS_ERROR)
            {
                /* Coverglass too good for Xtalk calibration */
                if((p_dev->temp_buffer[2] >= (uint8_t)0x7f) &&
                (((uint16_t)(p_dev->temp_buffer[3] &
                                 (uint16_t)0x80) >> 7) == (uint16_t)1))
                {
                    default_xtalk_ptr = p_dev->default_xtalk;
                    (void)memcpy(p_dev->xtalk_data,
                        default_xtalk_ptr,
                        sizeof(p_dev->xtalk_data));
                    status |= VL53L8CX_STATUS_XTALK_FAILED;
                }
                continue_loop = (uint8_t)0;
            }
            else if(timeout >= (uint16_t)400)
            {
                status |= VL53L8CX_STATUS_ERROR;
                continue_loop = (uint8_t)0;
            }
            else
            {
                timeout++;
                status |= VL53L8CX_WaitMs(&(p_dev->platform), 50);
            }
        }while (continue_loop == (uint8_t)1);
    }
    /* Save Xtalk data into the Xtalk buffer */
        (void)memcpy(p_dev->temp_buffer, VL53L8CX_GET_XTALK_CMD,
               sizeof(VL53L8CX_GET_XTALK_CMD));
    status |= VL53L8CX_WrMulti(&(p_dev->platform), 0x2fb8,
            p_dev->temp_buffer,
                        (uint16_t)sizeof(VL53L8CX_GET_XTALK_CMD));
    status |= _vl53l8cx_poll_for_answer(p_dev,VL53L8CX_UI_CMD_STATUS, 0x03);
    status |= VL53L8CX_RdMulti(&(p_dev->platform), VL53L8CX_UI_CMD_START,
            p_dev->temp_buffer,
                        VL53L8CX_XTALK_BUFFER_SIZE + (uint16_t)4);
    (void)memcpy(&(p_dev->xtalk_data[0]), &(p_dev->temp_buffer[8]),
            VL53L8CX_XTALK_BUFFER_SIZE - (uint16_t)8);
    (void)memcpy(&(p_dev->xtalk_data[VL53L8CX_XTALK_BUFFER_SIZE
                       - (uint16_t)8]), footer, sizeof(footer));
    /* Reset default buffer */
    status |= VL53L8CX_WrMulti(&(p_dev->platform), 0x2c34,
            p_dev->default_configuration,
            VL53L8CX_CONFIGURATION_SIZE);
    status |= _vl53l8cx_poll_for_answer(p_dev,VL53L8CX_UI_CMD_STATUS, 0x03);
    /* Reset initial configuration */
    status |= vl53l8cx_set_resolution(p_dev, resolution);
    status |= vl53l8cx_set_ranging_frequency_hz(p_dev, frequency);
    status |= vl53l8cx_set_integration_time_ms(p_dev, integration_time_ms);
    status |= vl53l8cx_set_sharpener_percent(p_dev, sharp_prct);
    status |= vl53l8cx_set_target_order(p_dev, target_order);
    status |= vl53l8cx_set_xtalk_margin(p_dev, xtalk_margin);
    status |= vl53l8cx_set_ranging_mode(p_dev, ranging_mode);
    return status;
}
References _vl53l8cx_poll_for_answer(), _vl53l8cx_program_output_config(), VL53L8CX_Configuration::default_configuration, VL53L8CX_Configuration::default_xtalk, VL53L8CX_Configuration::platform, VL53L8CX_Configuration::temp_buffer, VL53L8CX_CALIBRATE_XTALK, VL53L8CX_CONFIGURATION_SIZE, VL53L8CX_DCI_CAL_CFG, vl53l8cx_dci_replace_data(), vl53l8cx_get_integration_time_ms(), vl53l8cx_get_ranging_frequency_hz(), vl53l8cx_get_ranging_mode(), vl53l8cx_get_resolution(), vl53l8cx_get_sharpener_percent(), vl53l8cx_get_target_order(), VL53L8CX_GET_XTALK_CMD, vl53l8cx_get_xtalk_margin(), VL53L8CX_RdMulti(), VL53L8CX_RESOLUTION_8X8, vl53l8cx_set_integration_time_ms(), vl53l8cx_set_ranging_frequency_hz(), vl53l8cx_set_ranging_mode(), vl53l8cx_set_resolution(), vl53l8cx_set_sharpener_percent(), vl53l8cx_set_target_order(), vl53l8cx_set_xtalk_margin(), VL53L8CX_STATUS_ERROR, VL53L8CX_STATUS_INVALID_PARAM, VL53L8CX_STATUS_OK, VL53L8CX_STATUS_XTALK_FAILED, VL53L8CX_UI_CMD_END, VL53L8CX_UI_CMD_START, VL53L8CX_UI_CMD_STATUS, VL53L8CX_WaitMs(), VL53L8CX_WrMulti(), VL53L8CX_XTALK_BUFFER_SIZE, and VL53L8CX_Configuration::xtalk_data.
vl53l8cx_get_caldata_xtalk()
uint8_t vl53l8cx_get_caldata_xtalk (VL53L8CX_Configuration * p_dev, uint8_t * p_xtalk_data)
This function gets the Xtalk buffer. The buffer is available after using the function vl53l8cx_calibrate_xtalk().
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L5 configuration structure.
(uint8_t) *p_xtalk_data : Buffer with a size defined by macro VL53L8CX_XTALK_SIZE.
Returns
(uint8_t) status : 0 if buffer reading OK
Definition at line 290 of file vl53l8cx_plugin_xtalk.c.
{
    uint8_t status = VL53L8CX_STATUS_OK, resolution;
    uint8_t footer[] = {0x00, 0x00, 0x00, 0x0F, 0x00, 0x01, 0x03, 0x04};
    status |= vl53l8cx_get_resolution(p_dev, &resolution);
    status |= vl53l8cx_set_resolution(p_dev, VL53L8CX_RESOLUTION_8X8);
        (void)memcpy(p_dev->temp_buffer, VL53L8CX_GET_XTALK_CMD,
               sizeof(VL53L8CX_GET_XTALK_CMD));
    status |= VL53L8CX_WrMulti(&(p_dev->platform), 0x2fb8,
            p_dev->temp_buffer, sizeof(VL53L8CX_GET_XTALK_CMD));
    status |= _vl53l8cx_poll_for_answer(p_dev,VL53L8CX_UI_CMD_STATUS, 0x03);
    status |= VL53L8CX_RdMulti(&(p_dev->platform), VL53L8CX_UI_CMD_START,
            p_dev->temp_buffer,
                        VL53L8CX_XTALK_BUFFER_SIZE + (uint16_t)4);
    (void)memcpy(&(p_xtalk_data[0]), &(p_dev->temp_buffer[8]),
            VL53L8CX_XTALK_BUFFER_SIZE-(uint16_t)8);
    (void)memcpy(&(p_xtalk_data[VL53L8CX_XTALK_BUFFER_SIZE - (uint16_t)8]),
            footer, sizeof(footer));
    status |= vl53l8cx_set_resolution(p_dev, resolution);
    return status;
}
References _vl53l8cx_poll_for_answer(), VL53L8CX_Configuration::platform, VL53L8CX_Configuration::temp_buffer, vl53l8cx_get_resolution(), VL53L8CX_GET_XTALK_CMD, VL53L8CX_RdMulti(), VL53L8CX_RESOLUTION_8X8, vl53l8cx_set_resolution(), VL53L8CX_STATUS_OK, VL53L8CX_UI_CMD_START, VL53L8CX_UI_CMD_STATUS, VL53L8CX_WrMulti(), and VL53L8CX_XTALK_BUFFER_SIZE.
vl53l8cx_get_xtalk_margin()
uint8_t vl53l8cx_get_xtalk_margin (VL53L8CX_Configuration * p_dev, uint32_t * p_xtalk_margin)
This function gets the Xtalk margin. This margin is used to increase the Xtalk threshold. It can also be used to avoid false positives after the Xtalk calibration. The default value is 50 kcps/spads.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint32_t) *p_xtalk_margin : Xtalk margin in kcps/spads.
Returns
(uint8_t) status : 0 if reading OK
Definition at line 332 of file vl53l8cx_plugin_xtalk.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    status |= vl53l8cx_dci_read_data(p_dev, (uint8_t*)p_dev->temp_buffer,
            VL53L8CX_DCI_XTALK_CFG, 16);
    (void)memcpy(p_xtalk_margin, p_dev->temp_buffer, 4);
    *p_xtalk_margin = *p_xtalk_margin/(uint32_t)2048;
    return status;
}
References VL53L8CX_Configuration::temp_buffer, vl53l8cx_dci_read_data(), VL53L8CX_DCI_XTALK_CFG, and VL53L8CX_STATUS_OK.
Referenced by vl53l8cx_calibrate_xtalk().
vl53l8cx_set_caldata_xtalk()
uint8_t vl53l8cx_set_caldata_xtalk (VL53L8CX_Configuration * p_dev, uint8_t * p_xtalk_data)
This function sets the Xtalk buffer. This function can be used to override default Xtalk buffer.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L5 configuration structure.
(uint8_t) *p_xtalk_data : Buffer with a size defined by macro VL53L8CX_XTALK_SIZE.
Returns
(uint8_t) status : 0 if buffer OK
Definition at line 319 of file vl53l8cx_plugin_xtalk.c.
{
    uint8_t resolution, status = VL53L8CX_STATUS_OK;
    status |= vl53l8cx_get_resolution(p_dev, &resolution);
    (void)memcpy(p_dev->xtalk_data, p_xtalk_data, VL53L8CX_XTALK_BUFFER_SIZE);
    status |= vl53l8cx_set_resolution(p_dev, resolution);
    return status;
}
References vl53l8cx_get_resolution(), vl53l8cx_set_resolution(), VL53L8CX_STATUS_OK, VL53L8CX_XTALK_BUFFER_SIZE, and VL53L8CX_Configuration::xtalk_data.
vl53l8cx_set_xtalk_margin()
uint8_t vl53l8cx_set_xtalk_margin (VL53L8CX_Configuration * p_dev, uint32_t xtalk_margin)
This function sets the Xtalk margin. This margin is used to increase the Xtalk threshold. It can also be used to avoid false positives after the Xtalk calibration. The default value is 50 kcps/spads.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint32_t) xtalk_margin : New Xtalk margin in kcps/spads. Min value is 0 kcps/spads, and max is 10.000 kcps/spads
Returns
(uint8_t) status : 0 if set margin is OK, or 127 is the margin is invalid.
Definition at line 347 of file vl53l8cx_plugin_xtalk.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
        uint32_t margin_kcps = xtalk_margin;
    if(margin_kcps > (uint32_t)10000)
    {
        status |= VL53L8CX_STATUS_INVALID_PARAM;
    }
    else
    {
        margin_kcps = margin_kcps*(uint32_t)2048;
        status |= vl53l8cx_dci_replace_data(p_dev, p_dev->temp_buffer,
                VL53L8CX_DCI_XTALK_CFG, 16,
                                (uint8_t*)&margin_kcps, 4, 0x00);
    }
    return status;
}
References VL53L8CX_Configuration::temp_buffer, vl53l8cx_dci_replace_data(), VL53L8CX_DCI_XTALK_CFG, VL53L8CX_STATUS_INVALID_PARAM, and VL53L8CX_STATUS_OK.
Referenced by vl53l8cx_calibrate_xtalk().
Variable Documentation
VL53L8CX_CALIBRATE_XTALK
const uint8_t VL53L8CX_CALIBRATE_XTALK[] [static]
Command used to get run Xtalk calibration.
Definition at line 142 of file vl53l8cx_plugin_xtalk.h.
                                                  {
    0x54, 0x50, 0x00, 0x80,
    0x00, 0x04, 0x08, 0x08,
    0x00, 0x00, 0x04, 0x04,
    0xAD, 0x30, 0x00, 0x80,
    0x03, 0x01, 0x06, 0x03,
    0x00, 0x00, 0x01, 0x00,
    0xAD, 0x38, 0x01, 0x00,
    0x01, 0xE0, 0x01, 0x40,
    0x00, 0x10, 0x00, 0x10,
    0x01, 0x00, 0x01, 0x00,
    0x00, 0x00, 0x00, 0x01,
    0x54, 0x58, 0x00, 0x40,
    0x04, 0x1A, 0x02, 0x00,
    0x54, 0x5C, 0x01, 0x40,
    0x00, 0x01, 0x00, 0x51,
    0x00, 0x00, 0x0F, 0xA0,
    0x0F, 0xA0, 0x03, 0xE8,
    0x02, 0x80, 0x1F, 0x40,
    0x00, 0x00, 0x05, 0x00,
    0x54, 0x70, 0x00, 0x80,
    0x03, 0x20, 0x03, 0x20,
    0x00, 0x00, 0x00, 0x08,
    0x54, 0x78, 0x01, 0x00,
    0x01, 0x1B, 0x00, 0x21,
    0x00, 0x33, 0x00, 0x00,
    0x02, 0x00, 0x00, 0x01,
    0x04, 0x01, 0x08, VL53L8CX_FW_NBTAR_XTALK,
    0x54, 0x88, 0x01, 0x40,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x08, 0x00,
    0xAD, 0x48, 0x01, 0x00,
    0x01, 0xF4, 0x00, 0x00,
    0x03, 0x06, 0x00, 0x10,
    0x08, 0x08, 0x08, 0x08,
    0x00, 0x00, 0x00, 0x08,
    0xAD, 0x60, 0x01, 0x00,
    0x00, 0x00, 0x00, 0x80,
    0x00, 0x00, 0x00, 0x00,
    0x20, 0x1F, 0x01, 0xF4,
    0x00, 0x00, 0x1D, 0x0A,
    0xAD, 0x70, 0x00, 0x80,
    0x08, 0x00, 0x1F, 0x40,
    0x00, 0x00, 0x00, 0x01,
    0xAD, 0x78, 0x00, 0x80,
    0x00, 0xA0, 0x03, 0x20,
    0x00, 0x01, 0x01, 0x90,
    0xAD, 0x80, 0x00, 0x40,
    0x00, 0x00, 0x28, 0x00,
    0xAD, 0x84, 0x00, 0x80,
    0x00, 0x00, 0x32, 0x00,
    0x03, 0x20, 0x00, 0x00,
    0xAD, 0x8C, 0x00, 0x80,
    0x02, 0x58, 0xFF, 0x38,
    0x00, 0x00, 0x00, 0x0C,
    0xAD, 0x94, 0x01, 0x00,
    0x00, 0x01, 0x90, 0x00,
    0xFF, 0xFF, 0xFC, 0x00,
    0x00, 0x00, 0x04, 0x00,
    0x00, 0x00, 0x01, 0x00,
    0xAD, 0xA4, 0x00, 0xC0,
    0x04, 0x80, 0x06, 0x1A,
    0x00, 0x80, 0x05, 0x80,
    0x00, 0x00, 0x01, 0x06,
    0xAD, 0xB0, 0x00, 0xC0,
    0x04, 0x80, 0x06, 0x1A,
    0x19, 0x00, 0x05, 0x80,
    0x00, 0x00, 0x01, 0x90,
    0xAD, 0xBC, 0x04, 0x40,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x12, 0x00, 0x25,
    0x00, 0x00, 0x00, 0x06,
    0x00, 0x00, 0x00, 0x05,
    0x00, 0x00, 0x00, 0x05,
    0x00, 0x00, 0x00, 0x06,
    0x00, 0x00, 0x00, 0x04,
    0x00, 0x00, 0x00, 0x0F,
    0x00, 0x00, 0x00, 0x5A,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x09,
    0x0B, 0x0C, 0x0B, 0x0B,
    0x03, 0x03, 0x11, 0x05,
    0x01, 0x01, 0x01, 0x01,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x0D, 0x00, 0x00,
    0xAE, 0x00, 0x01, 0x04,
    0x00, 0x00, 0x00, 0x04,
    0x00, 0x00, 0x00, 0x08,
    0x00, 0x00, 0x00, 0x0A,
    0x00, 0x00, 0x00, 0x0C,
    0x00, 0x00, 0x00, 0x0D,
    0x00, 0x00, 0x00, 0x0E,
    0x00, 0x00, 0x00, 0x08,
    0x00, 0x00, 0x00, 0x08,
    0x00, 0x00, 0x00, 0x10,
    0x00, 0x00, 0x00, 0x10,
    0x00, 0x00, 0x00, 0x20,
    0x00, 0x00, 0x00, 0x20,
    0x00, 0x00, 0x00, 0x06,
    0x00, 0x00, 0x05, 0x0A,
    0x02, 0x00, 0x0C, 0x08,
    0x00, 0x00, 0x00, 0x00,
    0xAE, 0x40, 0x00, 0x40,
    0x00, 0x00, 0x00, 0xFF,
    0xAE, 0x44, 0x00, 0x40,
    0x00, 0x10, 0x04, 0x01,
    0xAE, 0x48, 0x00, 0x40,
    0x00, 0x00, 0x10, 0x00,
    0xAE, 0x4C, 0x00, 0x40,
    0x00, 0x00, 0x00, 0x01,
    0xAE, 0x50, 0x01, 0x40,
    0x00, 0x00, 0x00, 0x14,
    0x04, 0x00, 0x28, 0x00,
    0x03, 0x20, 0x6C, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0xAE, 0x64, 0x00, 0x40,
    0x00, 0x00, 0x00, 0x01,
    0xAE, 0xD8, 0x01, 0x00,
    0x00, 0xC8, 0x05, 0xDC,
    0x00, 0x00, 0x0C, 0xCD,
    0x01, 0x04, 0x00, 0x00,
    0x00, 0x01, 0x26, 0x01,
    0xB5, 0x50, 0x02, 0x82,
    0xA3, 0xE8, 0xA3, 0xB8,
    0xA4, 0x38, 0xA4, 0x28,
    0xA6, 0x48, 0xA4, 0x48,
    0xA7, 0x88, 0xA7, 0x48,
    0xAC, 0x10, 0xA7, 0x90,
    0x99, 0xBC, 0x99, 0xB4,
    0x9A, 0xFC, 0x9A, 0xBC,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0xB5, 0xA0, 0x02, 0x82,
    0x00, 0x88, 0x03, 0x00,
    0x00, 0x82, 0x00, 0x82,
    0x04, 0x04, 0x04, 0x08,
    0x00, 0x80, 0x04, 0x01,
    0x09, 0x02, 0x09, 0x08,
    0x04, 0x04, 0x00, 0x80,
    0x04, 0x01, 0x04, 0x01,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0xB5, 0xF0, 0x00, 0x40,
    0x00, 0x04, 0x00, 0x00,
    0xB3, 0x9C, 0x01, 0x00,
    0x40, 0x00, 0x05, 0x1E,
    0x02, 0x1B, 0x08, 0x7C,
    0x80, 0x00, 0x12, 0x01,
    0x00, 0x01, 0x08, 0x00,
    0xB6, 0xC0, 0x00, 0xC0,
    0x00, 0x00, 0x60, 0x00,
    0x00, 0x00, 0x20, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0xAE, 0xA8, 0x00, 0x40,
    0x00, 0x00, 0x04, 0x05,
    0xAE, 0xAC, 0x00, 0x80,
    0x01, 0x00, 0x01, 0x00,
    0x00, 0x02, 0x00, 0x00,
    0xAE, 0xB4, 0x00, 0x40,
    0x00, 0x00, 0x00, 0x00,
    0xAE, 0xB8, 0x00, 0x81,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0xAE, 0xC0, 0x00, 0x81,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0xAE, 0xC8, 0x00, 0x81,
    0x08, 0x01, 0x01, 0x08,
    0x00, 0x00, 0x00, 0x08,
    0xAE, 0xD0, 0x00, 0x81,
    0x01, 0x08, 0x08, 0x08,
    0x00, 0x00, 0x00, 0x01,
    0xB5, 0xF4, 0x00, 0x80,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0xB5, 0xFC, 0x00, 0x80,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0xB6, 0x04, 0x00, 0x40,
    0x00, 0x00, 0x00, 0x00,
    0xB6, 0x08, 0x00, 0x44,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0xB6, 0x18, 0x00, 0x44,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0xB6, 0x28, 0x00, 0x44,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0xB6, 0x38, 0x00, 0x44,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0xB6, 0x48, 0x01, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0xB6, 0x58, 0x01, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0xB6, 0x68, 0x01, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x54, 0x70, 0x00, 0x80,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x02,
    0x00, 0x00, 0x00, 0x0F,
    0x00, 0x01, 0x03, 0xD4
};
Referenced by vl53l8cx_calibrate_xtalk().
VL53L8CX_GET_XTALK_CMD
const uint8_t VL53L8CX_GET_XTALK_CMD[] [static]
Initial value:
= {
    0x54, 0x00, 0x00, 0x40,
    0x9F, 0xD8, 0x00, 0xC0,
    0x9F, 0xE4, 0x01, 0x40,
    0x9F, 0xF8, 0x00, 0x40,
    0x9F, 0xFC, 0x04, 0x04,
    0xA0, 0xFC, 0x01, 0x00,
    0xA1, 0x0C, 0x01, 0x00,
    0xA1, 0x1C, 0x00, 0xC0,
    0xA1, 0x28, 0x09, 0x02,
    0xA2, 0x48, 0x00, 0x40,
    0xA2, 0x4C, 0x00, 0x81,
    0xA2, 0x54, 0x00, 0x81,
    0xA2, 0x5C, 0x00, 0x81,
    0xA2, 0x64, 0x00, 0x81,
    0xA2, 0x6C, 0x00, 0x84,
    0xA2, 0x8C, 0x00, 0x82,
    0x00, 0x00, 0x00, 0x0F,
    0x07, 0x02, 0x00, 0x44
}
Command used to get Xtalk calibration data.
Definition at line 117 of file vl53l8cx_plugin_xtalk.h.
                                                {
    0x54, 0x00, 0x00, 0x40,
    0x9F, 0xD8, 0x00, 0xC0,
    0x9F, 0xE4, 0x01, 0x40,
    0x9F, 0xF8, 0x00, 0x40,
    0x9F, 0xFC, 0x04, 0x04,
    0xA0, 0xFC, 0x01, 0x00,
    0xA1, 0x0C, 0x01, 0x00,
    0xA1, 0x1C, 0x00, 0xC0,
    0xA1, 0x28, 0x09, 0x02,
    0xA2, 0x48, 0x00, 0x40,
    0xA2, 0x4C, 0x00, 0x81,
    0xA2, 0x54, 0x00, 0x81,
    0xA2, 0x5C, 0x00, 0x81,
    0xA2, 0x64, 0x00, 0x81,
    0xA2, 0x6C, 0x00, 0x84,
    0xA2, 0x8C, 0x00, 0x82,
    0x00, 0x00, 0x00, 0x0F,
    0x07, 0x02, 0x00, 0x44
};
Referenced by vl53l8cx_calibrate_xtalk(), and vl53l8cx_get_caldata_xtalk().