components/sensor_acq/uld/vl53l8cx_plugin_motion_indicator.h File Reference
#include "vl53l8cx_api.h"
Data Structures
struct VL53L8CX_Motion_Configuration
Motion indicator internal configuration structure.
Functions
uint8_t vl53l8cx_motion_indicator_init (VL53L8CX_Configuration *p_dev, VL53L8CX_Motion_Configuration *p_motion_config, uint8_t resolution)
This function is used to initialized the motion indicator. By default, indicator is programmed to monitor movements between 400mm and 1500mm.
uint8_t vl53l8cx_motion_indicator_set_distance_motion (VL53L8CX_Configuration *p_dev, VL53L8CX_Motion_Configuration *p_motion_config, uint16_t distance_min_mm, uint16_t distance_max_mm)
This function can be used to change the working distance of motion indicator. By default, indicator is programmed to monitor movements between 400mm and 1500mm.
uint8_t vl53l8cx_motion_indicator_set_resolution (VL53L8CX_Configuration *p_dev, VL53L8CX_Motion_Configuration *p_motion_config, uint8_t resolution)
This function is used to update the internal motion indicator map.
Function Documentation
vl53l8cx_motion_indicator_init()
uint8_t vl53l8cx_motion_indicator_init (VL53L8CX_Configuration * p_dev, VL53L8CX_Motion_Configuration * p_motion_config, uint8_t resolution)
This function is used to initialized the motion indicator. By default, indicator is programmed to monitor movements between 400mm and 1500mm.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(VL53L8CX_Motion_Configuration) *p_motion_config : Structure containing the initialized motion configuration.
(uint8_t) resolution : Wanted resolution, defined by macros VL53L8CX_RESOLUTION_4X4 or VL53L8CX_RESOLUTION_8X8.
Returns
(uint8_t) status : 0 if OK, or 127 is the resolution is unknown.
Copyright (c) 2021 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition at line 17 of file vl53l8cx_plugin_motion_indicator.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    (void)memset(p_motion_config, 0, sizeof(VL53L8CX_Motion_Configuration));
    p_motion_config->ref_bin_offset = 13633;
    p_motion_config->detection_threshold = 2883584;
    p_motion_config->extra_noise_sigma = 0;
    p_motion_config->null_den_clip_value = 0;
    p_motion_config->mem_update_mode = 6;
    p_motion_config->mem_update_choice = 2;
    p_motion_config->sum_span = 4;
    p_motion_config->feature_length = 9;
    p_motion_config->nb_of_aggregates = 16;
    p_motion_config->nb_of_temporal_accumulations = 16;
    p_motion_config->min_nb_for_global_detection = 1;
    p_motion_config->global_indicator_format_1 = 8;
    p_motion_config->global_indicator_format_2 = 0;
    p_motion_config->spare_1 = 0;
    p_motion_config->spare_2 = 0;
    p_motion_config->spare_3 = 0;
    status |= vl53l8cx_motion_indicator_set_resolution(p_dev,
            p_motion_config, resolution);
    return status;
}
References VL53L8CX_Motion_Configuration::detection_threshold, VL53L8CX_Motion_Configuration::extra_noise_sigma, VL53L8CX_Motion_Configuration::feature_length, VL53L8CX_Motion_Configuration::global_indicator_format_1, VL53L8CX_Motion_Configuration::global_indicator_format_2, VL53L8CX_Motion_Configuration::mem_update_choice, VL53L8CX_Motion_Configuration::mem_update_mode, VL53L8CX_Motion_Configuration::min_nb_for_global_detection, VL53L8CX_Motion_Configuration::nb_of_aggregates, VL53L8CX_Motion_Configuration::nb_of_temporal_accumulations, VL53L8CX_Motion_Configuration::null_den_clip_value, VL53L8CX_Motion_Configuration::ref_bin_offset, VL53L8CX_Motion_Configuration::spare_1, VL53L8CX_Motion_Configuration::spare_2, VL53L8CX_Motion_Configuration::spare_3, VL53L8CX_Motion_Configuration::sum_span, vl53l8cx_motion_indicator_set_resolution(), and VL53L8CX_STATUS_OK.
vl53l8cx_motion_indicator_set_distance_motion()
uint8_t vl53l8cx_motion_indicator_set_distance_motion (VL53L8CX_Configuration * p_dev, VL53L8CX_Motion_Configuration * p_motion_config, uint16_t distance_min_mm, uint16_t distance_max_mm)
This function can be used to change the working distance of motion indicator. By default, indicator is programmed to monitor movements between 400mm and 1500mm.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(VL53L8CX_Motion_Configuration) *p_motion_config : Structure containing the initialized motion configuration.
(uint16_t) distance_min_mm : Minimum distance for indicator (min value 400mm, max 4000mm).
(uint16_t) distance_max_mm : Maximum distance for indicator (min value 400mm, max 4000mm). VL53L8CX_RESOLUTION_4X4 or VL53L8CX_RESOLUTION_8X8.
Returns
(uint8_t) status : 0 if OK, or 127 if an argument is invalid.
Definition at line 49 of file vl53l8cx_plugin_motion_indicator.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    float_t tmp;
    if(((distance_max_mm - distance_min_mm) > (uint16_t)1500)
            || (distance_min_mm < (uint16_t)400)
                        || (distance_max_mm > (uint16_t)4000))
    {
        status |= VL53L8CX_STATUS_INVALID_PARAM;
    }
    else
    {
        tmp = (float_t)((((float_t)distance_min_mm/(float_t)37.5348)
                               -(float_t)4.0)*(float_t)2048.5);
                p_motion_config->ref_bin_offset = (int32_t)tmp;
                
                tmp = (float_t)((((((float_t)distance_max_mm-
            (float_t)distance_min_mm)/(float_t)10.0)+(float_t)30.02784)
            /((float_t)15.01392))+(float_t)0.5);
        p_motion_config->feature_length = (uint8_t)tmp;
        status |= vl53l8cx_dci_write_data(p_dev,
            (uint8_t*)(p_motion_config),
            VL53L8CX_DCI_MOTION_DETECTOR_CFG,
                        (uint16_t)sizeof(*p_motion_config));
    }
    return status;
}
References VL53L8CX_Motion_Configuration::feature_length, VL53L8CX_Motion_Configuration::ref_bin_offset, VL53L8CX_DCI_MOTION_DETECTOR_CFG, vl53l8cx_dci_write_data(), VL53L8CX_STATUS_INVALID_PARAM, and VL53L8CX_STATUS_OK.
vl53l8cx_motion_indicator_set_resolution()
uint8_t vl53l8cx_motion_indicator_set_resolution (VL53L8CX_Configuration * p_dev, VL53L8CX_Motion_Configuration * p_motion_config, uint8_t resolution)
This function is used to update the internal motion indicator map.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(VL53L8CX_Motion_Configuration) *p_motion_config : Structure containing the initialized motion configuration.
(uint8_t) resolution : Wanted SCI resolution, defined by macros VL53L8CX_RESOLUTION_4X4 or VL53L8CX_RESOLUTION_8X8.
Returns
(uint8_t) status : 0 if OK, or 127 is the resolution is unknown.
Definition at line 84 of file vl53l8cx_plugin_motion_indicator.c.
{
    uint8_t i, status = VL53L8CX_STATUS_OK;
    switch(resolution)
    {
        case VL53L8CX_RESOLUTION_4X4:
            for(i = 0; i < (uint8_t)VL53L8CX_RESOLUTION_4X4; i++)
            {
                p_motion_config->map_id[i] = (int8_t)i;
            }
        (void)memset(p_motion_config->map_id + 16, -1, 48);
        break;
        case VL53L8CX_RESOLUTION_8X8:
            for(i = 0; i < (uint8_t)VL53L8CX_RESOLUTION_8X8; i++)
            {
                               p_motion_config->map_id[i] = (int8_t)((((int8_t)
                               i % 8)/2) + (4*((int8_t)i/16)));
            }
        break;
        default:
            status |= VL53L8CX_STATUS_ERROR;
        break;
    }
    if(status == VL53L8CX_STATUS_OK)
    {
        status |= vl53l8cx_dci_write_data(p_dev,
                (uint8_t*)(p_motion_config),
                VL53L8CX_DCI_MOTION_DETECTOR_CFG,
                                (uint16_t)sizeof(*p_motion_config));
    }
    return status;
}
References VL53L8CX_Motion_Configuration::map_id, VL53L8CX_DCI_MOTION_DETECTOR_CFG, vl53l8cx_dci_write_data(), VL53L8CX_RESOLUTION_4X4, VL53L8CX_RESOLUTION_8X8, VL53L8CX_STATUS_ERROR, and VL53L8CX_STATUS_OK.
Referenced by vl53l8cx_motion_indicator_init().