components/sensor_acq/uld/vl53l8cx_api.h File Reference
#include "platform.h"
Data Structures
struct VL53L8CX_Configuration
Structure VL53L8CX_Configuration contains the sensor configuration. User MUST not manually change these field, except for the sensor address.
struct VL53L8CX_ResultsData
Structure VL53L8CX_ResultsData contains the ranging results of VL53L8CX. If user wants more than 1 target per zone, the results can be split into 2 sub-groups :
union Block_header
Macros
#define VL53L8CX_API_REVISION "VL53L8CX_2.0.0"
Current driver version.
#define VL53L8CX_DEFAULT_I2C_ADDRESS ((uint16_t)0x52)
Default I2C address of VL53L8CX sensor. Can be changed using function vl53l8cx_set_i2c_address() function is called.
#define VL53L8CX_RESOLUTION_4X4 ((uint8_t) 16U)
Macro VL53L8CX_RESOLUTION_4X4 or VL53L8CX_RESOLUTION_8X8 allows setting sensor in 4x4 mode or 8x8 mode, using function vl53l8cx_set_resolution().
#define VL53L8CX_RESOLUTION_8X8 ((uint8_t) 64U)
#define VL53L8CX_TARGET_ORDER_CLOSEST ((uint8_t) 1U)
Macro VL53L8CX_TARGET_ORDER_STRONGEST or VL53L8CX_TARGET_ORDER_CLOSEST are used to select the target order for data output.
#define VL53L8CX_TARGET_ORDER_STRONGEST ((uint8_t) 2U)
#define VL53L8CX_RANGING_MODE_CONTINUOUS ((uint8_t) 1U)
Macro VL53L8CX_RANGING_MODE_CONTINUOUS and VL53L8CX_RANGING_MODE_AUTONOMOUS are used to change the ranging mode. Autonomous mode can be used to set a precise integration time, whereas continuous is always maximum.
#define VL53L8CX_RANGING_MODE_AUTONOMOUS ((uint8_t) 3U)
#define VL53L8CX_POWER_MODE_SLEEP ((uint8_t) 0U)
The default power mode is VL53L8CX_POWER_MODE_WAKEUP. User can choose two different modes to save power consumption when is the device is not used:
#define VL53L8CX_POWER_MODE_WAKEUP ((uint8_t) 1U)
#define VL53L8CX_POWER_MODE_DEEP_SLEEP ((uint8_t) 2U)
#define VL53L8CX_STATUS_OK ((uint8_t) 0U)
Macro VL53L8CX_STATUS_OK indicates that VL53L5 sensor has no error. Macro VL53L8CX_STATUS_ERROR indicates that something is wrong (value, I2C access, ...). Macro VL53L8CX_MCU_ERROR is used to indicate a MCU issue.
#define VL53L8CX_STATUS_TIMEOUT_ERROR ((uint8_t) 1U)
#define VL53L8CX_STATUS_CORRUPTED_FRAME ((uint8_t) 2U)
#define VL53L8CX_STATUS_LASER_SAFETY ((uint8_t) 3U)
#define VL53L8CX_STATUS_XTALK_FAILED ((uint8_t) 4U)
#define VL53L8CX_STATUS_FW_CHECKSUM_FAIL ((uint8_t) 5U)
#define VL53L8CX_MCU_ERROR ((uint8_t) 66U)
#define VL53L8CX_STATUS_INVALID_PARAM ((uint8_t) 127U)
#define VL53L8CX_STATUS_ERROR ((uint8_t) 255U)
#define VL53L8CX_START_BH ((uint32_t)0x0000000DU)
Definitions for Range results block headers.
#define VL53L8CX_METADATA_BH ((uint32_t)0x54B400C0U)
#define VL53L8CX_COMMONDATA_BH ((uint32_t)0x54C00040U)
#define VL53L8CX_AMBIENT_RATE_BH ((uint32_t)0x54D00104U)
#define VL53L8CX_SPAD_COUNT_BH ((uint32_t)0x55D00404U)
#define VL53L8CX_NB_TARGET_DETECTED_BH ((uint32_t)0xDB840401U)
#define VL53L8CX_SIGNAL_RATE_BH ((uint32_t)0xDBC40404U)
#define VL53L8CX_RANGE_SIGMA_MM_BH ((uint32_t)0xDEC40402U)
#define VL53L8CX_DISTANCE_BH ((uint32_t)0xDF440402U)
#define VL53L8CX_REFLECTANCE_BH ((uint32_t)0xE0440401U)
#define VL53L8CX_TARGET_STATUS_BH ((uint32_t)0xE0840401U)
#define VL53L8CX_MOTION_DETECT_BH ((uint32_t)0xD85808C0U)
#define VL53L8CX_METADATA_IDX ((uint16_t)0x54B4U)
#define VL53L8CX_SPAD_COUNT_IDX ((uint16_t)0x55D0U)
#define VL53L8CX_AMBIENT_RATE_IDX ((uint16_t)0x54D0U)
#define VL53L8CX_NB_TARGET_DETECTED_IDX ((uint16_t)0xDB84U)
#define VL53L8CX_SIGNAL_RATE_IDX ((uint16_t)0xDBC4U)
#define VL53L8CX_RANGE_SIGMA_MM_IDX ((uint16_t)0xDEC4U)
#define VL53L8CX_DISTANCE_IDX ((uint16_t)0xDF44U)
#define VL53L8CX_REFLECTANCE_EST_PC_IDX ((uint16_t)0xE044U)
#define VL53L8CX_TARGET_STATUS_IDX ((uint16_t)0xE084U)
#define VL53L8CX_MOTION_DETEC_IDX ((uint16_t)0xD858U)
#define VL53L8CX_NVM_DATA_SIZE ((uint16_t)492U)
Inner Macro for API. Not for user, only for development.
#define VL53L8CX_CONFIGURATION_SIZE ((uint16_t)972U)
#define VL53L8CX_OFFSET_BUFFER_SIZE ((uint16_t)488U)
#define VL53L8CX_XTALK_BUFFER_SIZE ((uint16_t)776U)
#define VL53L8CX_DCI_ZONE_CONFIG ((uint16_t)0x5450U)
#define VL53L8CX_DCI_FREQ_HZ ((uint16_t)0x5458U)
#define VL53L8CX_DCI_INT_TIME ((uint16_t)0x545CU)
#define VL53L8CX_DCI_FW_NB_TARGET ((uint16_t)0x5478)
#define VL53L8CX_DCI_RANGING_MODE ((uint16_t)0xAD30U)
#define VL53L8CX_DCI_DSS_CONFIG ((uint16_t)0xAD38U)
#define VL53L8CX_DCI_VHV_CONFIG ((uint16_t)0xAD60U)
#define VL53L8CX_DCI_TARGET_ORDER ((uint16_t)0xAE64U)
#define VL53L8CX_DCI_SHARPENER ((uint16_t)0xAED8U)
#define VL53L8CX_DCI_INTERNAL_CP ((uint16_t)0xB39CU)
#define VL53L8CX_DCI_SYNC_PIN ((uint16_t)0xB5F0U)
#define VL53L8CX_DCI_MOTION_DETECTOR_CFG ((uint16_t)0xBFACU)
#define VL53L8CX_DCI_SINGLE_RANGE ((uint16_t)0xD964U)
#define VL53L8CX_DCI_OUTPUT_CONFIG ((uint16_t)0xD968U)
#define VL53L8CX_DCI_OUTPUT_ENABLES ((uint16_t)0xD970U)
#define VL53L8CX_DCI_OUTPUT_LIST ((uint16_t)0xD980U)
#define VL53L8CX_DCI_PIPE_CONTROL ((uint16_t)0xDB80U)
#define VL53L8CX_UI_CMD_STATUS ((uint16_t)0x2C00U)
#define VL53L8CX_UI_CMD_START ((uint16_t)0x2C04U)
#define VL53L8CX_UI_CMD_END ((uint16_t)0x2FFFU)
#define L5CX_AMB_SIZE 260U
Inner values for API. Max buffer size depends of the selected output.
#define L5CX_SPAD_SIZE 260U
#define L5CX_NTAR_SIZE 68U
#define L5CX_SPS_SIZE ((256U * VL53L8CX_NB_TARGET_PER_ZONE) + 4U)
#define L5CX_SIGR_SIZE ((128U * VL53L8CX_NB_TARGET_PER_ZONE) + 4U)
#define L5CX_DIST_SIZE ((128U * VL53L8CX_NB_TARGET_PER_ZONE) + 4U)
#define L5CX_RFLEST_SIZE ((64U *VL53L8CX_NB_TARGET_PER_ZONE) + 4U)
#define L5CX_STA_SIZE ((64U *VL53L8CX_NB_TARGET_PER_ZONE) + 4U)
#define L5CX_MOT_SIZE 144U
#define VL53L8CX_MAX_RESULTS_SIZE
Macro VL53L8CX_MAX_RESULTS_SIZE indicates the maximum size used by output through I2C. Value 40 corresponds to headers + meta-data + common-data and 20 corresponds to the footer.
#define VL53L8CX_TEMPORARY_BUFFER_SIZE ((uint32_t) VL53L8CX_MAX_RESULTS_SIZE)
Macro VL53L8CX_TEMPORARY_BUFFER_SIZE can be used to know the size of the temporary buffer. The minimum size is 1024, and the maximum depends of the output configuration.
Functions
uint8_t vl53l8cx_is_alive (VL53L8CX_Configuration *p_dev, uint8_t *p_is_alive)
uint8_t vl53l8cx_init (VL53L8CX_Configuration *p_dev)
Mandatory function used to initialize the sensor. This function must be called after a power on, to load the firmware into the VL53L8CX. It takes a few hundred milliseconds.
uint8_t vl53l8cx_set_i2c_address (VL53L8CX_Configuration *p_dev, uint16_t i2c_address)
This function is used to change the I2C address of the sensor. If multiple VL53L5 sensors are connected to the same I2C line, all other LPn pins needs to be set to Low. The default sensor address is 0x52.
uint8_t vl53l8cx_get_power_mode (VL53L8CX_Configuration *p_dev, uint8_t *p_power_mode)
This function is used to get the current sensor power mode.
uint8_t vl53l8cx_set_power_mode (VL53L8CX_Configuration *p_dev, uint8_t power_mode)
This function is used to set the sensor in Low Power mode, for example if the sensor is not used during a long time. The macro VL53L8CX_POWER_MODE_SLEEP can be used to enable the low power mode. When user want to restart the sensor, he can use macro VL53L8CX_POWER_MODE_WAKEUP. Please ensure that the device is not streaming before calling the function.
uint8_t vl53l8cx_start_ranging (VL53L8CX_Configuration *p_dev)
This function starts a ranging session. When the sensor streams, host cannot change settings 'on-the-fly'.
uint8_t vl53l8cx_stop_ranging (VL53L8CX_Configuration *p_dev)
This function stops the ranging session. It must be used when the sensor streams, after calling vl53l8cx_start_ranging().
uint8_t vl53l8cx_check_data_ready (VL53L8CX_Configuration *p_dev, uint8_t *p_isReady)
This function checks if a new data is ready by polling I2C. If a new data is ready, a flag will be raised.
uint8_t vl53l8cx_get_ranging_data (VL53L8CX_Configuration *p_dev, VL53L8CX_ResultsData *p_results)
This function gets the ranging data, using the selected output and the resolution.
uint8_t vl53l8cx_get_resolution (VL53L8CX_Configuration *p_dev, uint8_t *p_resolution)
This function gets the current resolution (4x4 or 8x8).
uint8_t vl53l8cx_set_resolution (VL53L8CX_Configuration *p_dev, uint8_t resolution)
This function sets a new resolution (4x4 or 8x8).
uint8_t vl53l8cx_get_ranging_frequency_hz (VL53L8CX_Configuration *p_dev, uint8_t *p_frequency_hz)
This function gets the current ranging frequency in Hz. Ranging frequency corresponds to the time between each measurement.
uint8_t vl53l8cx_set_ranging_frequency_hz (VL53L8CX_Configuration *p_dev, uint8_t frequency_hz)
This function sets a new ranging frequency in Hz. Ranging frequency corresponds to the measurements frequency. This setting depends of the resolution, so please select your resolution before using this function.
uint8_t vl53l8cx_get_integration_time_ms (VL53L8CX_Configuration *p_dev, uint32_t *p_time_ms)
This function gets the current integration time in ms.
uint8_t vl53l8cx_set_integration_time_ms (VL53L8CX_Configuration *p_dev, uint32_t integration_time_ms)
This function sets a new integration time in ms. Integration time must be computed to be lower than the ranging period, for a selected resolution. Please note that this function has no impact on ranging mode continous.
uint8_t vl53l8cx_get_sharpener_percent (VL53L8CX_Configuration *p_dev, uint8_t *p_sharpener_percent)
This function gets the current sharpener in percent. Sharpener can be changed to blur more or less zones depending of the application.
uint8_t vl53l8cx_set_sharpener_percent (VL53L8CX_Configuration *p_dev, uint8_t sharpener_percent)
This function sets a new sharpener value in percent. Sharpener can be changed to blur more or less zones depending of the application. Min value is 0 (disabled), and max is 99.
uint8_t vl53l8cx_get_target_order (VL53L8CX_Configuration *p_dev, uint8_t *p_target_order)
This function gets the current target order (closest or strongest).
uint8_t vl53l8cx_set_target_order (VL53L8CX_Configuration *p_dev, uint8_t target_order)
This function sets a new target order. Please use macros VL53L8CX_TARGET_ORDER_STRONGEST and VL53L8CX_TARGET_ORDER_CLOSEST to define the new output order. By default, the sensor is configured with the strongest output.
uint8_t vl53l8cx_get_ranging_mode (VL53L8CX_Configuration *p_dev, uint8_t *p_ranging_mode)
This function is used to get the ranging mode. Two modes are available using ULD : Continuous and autonomous. The default mode is Autonomous.
uint8_t vl53l8cx_set_ranging_mode (VL53L8CX_Configuration *p_dev, uint8_t ranging_mode)
This function is used to set the ranging mode. Two modes are available using ULD : Continuous and autonomous. The default mode is Autonomous.
uint8_t vl53l8cx_get_external_sync_pin_enable (VL53L8CX_Configuration *p_dev, uint8_t *p_is_sync_pin_enabled)
This function is used to check if the synchronization pin is enabled or disabled. When it is enabled, the sensor waits an interrupt on B1 pin to start the next measurement. It is useful for multi-devices synchronization. By default the sync pin is disabled.
uint8_t vl53l8cx_set_external_sync_pin_enable (VL53L8CX_Configuration *p_dev, uint8_t enable_sync_pin)
This function is used to enable or disable the synchronization pin. When it is enabled, the sensor waits an interrupt on B1 pin to start the next measurement. It is useful for multi-devices synchronization. By default the sync pin is disabled.
uint8_t vl53l8cx_get_VHV_repeat_count (VL53L8CX_Configuration *p_dev, uint32_t *p_repeat_count)
This function is used to get the number of frames between 2 temperature compensation.
uint8_t vl53l8cx_set_VHV_repeat_count (VL53L8CX_Configuration *p_dev, uint32_t repeat_count)
This function is used to set a periodic temperature compensation. By setting a repeat count different to 0 the firmware automatically runs a temperature calibration every N frames. default the repeat count is set to 0.
uint8_t vl53l8cx_dci_read_data (VL53L8CX_Configuration *p_dev, uint8_t *data, uint32_t index, uint16_t data_size)
This function can be used to read 'extra data' from DCI. Using a known index, the function fills the casted structure passed in argument.
uint8_t vl53l8cx_dci_write_data (VL53L8CX_Configuration *p_dev, uint8_t *data, uint32_t index, uint16_t data_size)
This function can be used to write 'extra data' to DCI. The data can be simple data, or casted structure.
uint8_t vl53l8cx_dci_replace_data (VL53L8CX_Configuration *p_dev, uint8_t *data, uint32_t index, uint16_t data_size, uint8_t *new_data, uint16_t new_data_size, uint16_t new_data_pos)
This function can be used to replace 'extra data' in DCI. The data can be simple data, or casted structure.
Macro Definition Documentation
L5CX_AMB_SIZE
#define L5CX_AMB_SIZE 260U
Inner values for API. Max buffer size depends of the selected output.
Definition at line 190 of file vl53l8cx_api.h.
L5CX_DIST_SIZE
#define L5CX_DIST_SIZE ((128U * VL53L8CX_NB_TARGET_PER_ZONE) + 4U)
Definition at line 220 of file vl53l8cx_api.h.
L5CX_MOT_SIZE
#define L5CX_MOT_SIZE 144U
Definition at line 238 of file vl53l8cx_api.h.
L5CX_NTAR_SIZE
#define L5CX_NTAR_SIZE 68U
Definition at line 202 of file vl53l8cx_api.h.
L5CX_RFLEST_SIZE
#define L5CX_RFLEST_SIZE ((64U *VL53L8CX_NB_TARGET_PER_ZONE) + 4U)
Definition at line 226 of file vl53l8cx_api.h.
L5CX_SIGR_SIZE
#define L5CX_SIGR_SIZE ((128U * VL53L8CX_NB_TARGET_PER_ZONE) + 4U)
Definition at line 214 of file vl53l8cx_api.h.
L5CX_SPAD_SIZE
#define L5CX_SPAD_SIZE 260U
Definition at line 196 of file vl53l8cx_api.h.
L5CX_SPS_SIZE
#define L5CX_SPS_SIZE ((256U * VL53L8CX_NB_TARGET_PER_ZONE) + 4U)
Definition at line 208 of file vl53l8cx_api.h.
L5CX_STA_SIZE
#define L5CX_STA_SIZE ((64U *VL53L8CX_NB_TARGET_PER_ZONE) + 4U)
Definition at line 232 of file vl53l8cx_api.h.
VL53L8CX_AMBIENT_RATE_BH
#define VL53L8CX_AMBIENT_RATE_BH ((uint32_t)0x54D00104U)
Definition at line 106 of file vl53l8cx_api.h.
Referenced by vl53l8cx_start_ranging().
VL53L8CX_AMBIENT_RATE_IDX
#define VL53L8CX_AMBIENT_RATE_IDX ((uint16_t)0x54D0U)
Definition at line 118 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_ranging_data().
VL53L8CX_API_REVISION
#define VL53L8CX_API_REVISION "VL53L8CX_2.0.0"
Current driver version.
Copyright (c) 2021 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition at line 28 of file vl53l8cx_api.h.
VL53L8CX_COMMONDATA_BH
#define VL53L8CX_COMMONDATA_BH ((uint32_t)0x54C00040U)
Definition at line 105 of file vl53l8cx_api.h.
Referenced by vl53l8cx_start_ranging().
VL53L8CX_CONFIGURATION_SIZE
#define VL53L8CX_CONFIGURATION_SIZE ((uint16_t)972U)
Definition at line 159 of file vl53l8cx_api.h.
Referenced by vl53l8cx_calibrate_xtalk().
VL53L8CX_DCI_DSS_CONFIG
#define VL53L8CX_DCI_DSS_CONFIG ((uint16_t)0xAD38U)
Definition at line 168 of file vl53l8cx_api.h.
Referenced by vl53l8cx_set_resolution().
VL53L8CX_DCI_FREQ_HZ
#define VL53L8CX_DCI_FREQ_HZ ((uint16_t)0x5458U)
Definition at line 164 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_ranging_frequency_hz(), and vl53l8cx_set_ranging_frequency_hz().
VL53L8CX_DCI_FW_NB_TARGET
#define VL53L8CX_DCI_FW_NB_TARGET ((uint16_t)0x5478)
Definition at line 166 of file vl53l8cx_api.h.
Referenced by vl53l8cx_init().
VL53L8CX_DCI_INT_TIME
#define VL53L8CX_DCI_INT_TIME ((uint16_t)0x545CU)
Definition at line 165 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_integration_time_ms(), and vl53l8cx_set_integration_time_ms().
VL53L8CX_DCI_INTERNAL_CP
#define VL53L8CX_DCI_INTERNAL_CP ((uint16_t)0xB39CU)
Definition at line 172 of file vl53l8cx_api.h.
VL53L8CX_DCI_MOTION_DETECTOR_CFG
#define VL53L8CX_DCI_MOTION_DETECTOR_CFG ((uint16_t)0xBFACU)
Definition at line 174 of file vl53l8cx_api.h.
Referenced by vl53l8cx_motion_indicator_set_distance_motion(), and vl53l8cx_motion_indicator_set_resolution().
VL53L8CX_DCI_OUTPUT_CONFIG
#define VL53L8CX_DCI_OUTPUT_CONFIG ((uint16_t)0xD968U)
Definition at line 176 of file vl53l8cx_api.h.
Referenced by _vl53l8cx_program_output_config(), and vl53l8cx_start_ranging().
VL53L8CX_DCI_OUTPUT_ENABLES
#define VL53L8CX_DCI_OUTPUT_ENABLES ((uint16_t)0xD970U)
Definition at line 177 of file vl53l8cx_api.h.
Referenced by _vl53l8cx_program_output_config(), and vl53l8cx_start_ranging().
VL53L8CX_DCI_OUTPUT_LIST
#define VL53L8CX_DCI_OUTPUT_LIST ((uint16_t)0xD980U)
Definition at line 178 of file vl53l8cx_api.h.
Referenced by _vl53l8cx_program_output_config(), and vl53l8cx_start_ranging().
VL53L8CX_DCI_PIPE_CONTROL
#define VL53L8CX_DCI_PIPE_CONTROL ((uint16_t)0xDB80U)
Definition at line 179 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_detection_thresholds_auto_stop(), vl53l8cx_init(), and vl53l8cx_set_detection_thresholds_auto_stop().
VL53L8CX_DCI_RANGING_MODE
#define VL53L8CX_DCI_RANGING_MODE ((uint16_t)0xAD30U)
Definition at line 167 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_ranging_mode(), and vl53l8cx_set_ranging_mode().
VL53L8CX_DCI_SHARPENER
#define VL53L8CX_DCI_SHARPENER ((uint16_t)0xAED8U)
Definition at line 171 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_sharpener_percent(), and vl53l8cx_set_sharpener_percent().
VL53L8CX_DCI_SINGLE_RANGE
#define VL53L8CX_DCI_SINGLE_RANGE ((uint16_t)0xD964U)
Definition at line 175 of file vl53l8cx_api.h.
Referenced by vl53l8cx_init(), and vl53l8cx_set_ranging_mode().
VL53L8CX_DCI_SYNC_PIN
#define VL53L8CX_DCI_SYNC_PIN ((uint16_t)0xB5F0U)
Definition at line 173 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_external_sync_pin_enable(), and vl53l8cx_set_external_sync_pin_enable().
VL53L8CX_DCI_TARGET_ORDER
#define VL53L8CX_DCI_TARGET_ORDER ((uint16_t)0xAE64U)
Definition at line 170 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_target_order(), and vl53l8cx_set_target_order().
VL53L8CX_DCI_VHV_CONFIG
#define VL53L8CX_DCI_VHV_CONFIG ((uint16_t)0xAD60U)
Definition at line 169 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_VHV_repeat_count(), and vl53l8cx_set_VHV_repeat_count().
VL53L8CX_DCI_ZONE_CONFIG
#define VL53L8CX_DCI_ZONE_CONFIG ((uint16_t)0x5450U)
Definition at line 163 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_resolution(), and vl53l8cx_set_resolution().
VL53L8CX_DEFAULT_I2C_ADDRESS
#define VL53L8CX_DEFAULT_I2C_ADDRESS ((uint16_t)0x52)
Default I2C address of VL53L8CX sensor. Can be changed using function vl53l8cx_set_i2c_address() function is called.
Definition at line 35 of file vl53l8cx_api.h.
VL53L8CX_DISTANCE_BH
#define VL53L8CX_DISTANCE_BH ((uint32_t)0xDF440402U)
Definition at line 111 of file vl53l8cx_api.h.
Referenced by vl53l8cx_start_ranging().
VL53L8CX_DISTANCE_IDX
#define VL53L8CX_DISTANCE_IDX ((uint16_t)0xDF44U)
Definition at line 122 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_ranging_data().
VL53L8CX_MAX_RESULTS_SIZE
#define VL53L8CX_MAX_RESULTS_SIZE
Value:
    (40U \
    + L5CX_AMB_SIZE + L5CX_SPAD_SIZE + L5CX_NTAR_SIZE + L5CX_SPS_SIZE \
    + L5CX_SIGR_SIZE + L5CX_DIST_SIZE + L5CX_RFLEST_SIZE + L5CX_STA_SIZE \
    + L5CX_MOT_SIZE + 20U)
Macro VL53L8CX_MAX_RESULTS_SIZE indicates the maximum size used by output through I2C. Value 40 corresponds to headers + meta-data + common-data and 20 corresponds to the footer.
Definition at line 249 of file vl53l8cx_api.h.
#define VL53L8CX_MAX_RESULTS_SIZE (40U \
    + L5CX_AMB_SIZE + L5CX_SPAD_SIZE + L5CX_NTAR_SIZE + L5CX_SPS_SIZE \
    + L5CX_SIGR_SIZE + L5CX_DIST_SIZE + L5CX_RFLEST_SIZE + L5CX_STA_SIZE \
    + L5CX_MOT_SIZE + 20U)
VL53L8CX_MCU_ERROR
#define VL53L8CX_MCU_ERROR ((uint8_t) 66U)
Definition at line 93 of file vl53l8cx_api.h.
Referenced by _vl53l8cx_poll_for_answer(), and _vl53l8cx_poll_for_answer().
VL53L8CX_METADATA_BH
#define VL53L8CX_METADATA_BH ((uint32_t)0x54B400C0U)
Definition at line 104 of file vl53l8cx_api.h.
Referenced by vl53l8cx_start_ranging().
VL53L8CX_METADATA_IDX
#define VL53L8CX_METADATA_IDX ((uint16_t)0x54B4U)
Definition at line 116 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_ranging_data().
VL53L8CX_MOTION_DETEC_IDX
#define VL53L8CX_MOTION_DETEC_IDX ((uint16_t)0xD858U)
Definition at line 125 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_ranging_data().
VL53L8CX_MOTION_DETECT_BH
#define VL53L8CX_MOTION_DETECT_BH ((uint32_t)0xD85808C0U)
Definition at line 114 of file vl53l8cx_api.h.
Referenced by vl53l8cx_start_ranging().
VL53L8CX_NB_TARGET_DETECTED_BH
#define VL53L8CX_NB_TARGET_DETECTED_BH ((uint32_t)0xDB840401U)
Definition at line 108 of file vl53l8cx_api.h.
Referenced by vl53l8cx_start_ranging().
VL53L8CX_NB_TARGET_DETECTED_IDX
#define VL53L8CX_NB_TARGET_DETECTED_IDX ((uint16_t)0xDB84U)
Definition at line 119 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_ranging_data().
VL53L8CX_NVM_DATA_SIZE
#define VL53L8CX_NVM_DATA_SIZE ((uint16_t)492U)
Inner Macro for API. Not for user, only for development.
Definition at line 158 of file vl53l8cx_api.h.
Referenced by vl53l8cx_init().
VL53L8CX_OFFSET_BUFFER_SIZE
#define VL53L8CX_OFFSET_BUFFER_SIZE ((uint16_t)488U)
Definition at line 160 of file vl53l8cx_api.h.
Referenced by _vl53l8cx_send_offset_data(), and vl53l8cx_init().
VL53L8CX_POWER_MODE_DEEP_SLEEP
#define VL53L8CX_POWER_MODE_DEEP_SLEEP ((uint8_t) 2U)
Definition at line 79 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_power_mode(), and vl53l8cx_set_power_mode().
VL53L8CX_POWER_MODE_SLEEP
#define VL53L8CX_POWER_MODE_SLEEP ((uint8_t) 0U)
The default power mode is VL53L8CX_POWER_MODE_WAKEUP. User can choose two different modes to save power consumption when is the device is not used:
VL53L8CX_POWER_MODE_SLEEP: This mode retains the firmware and the configuration. It is recommended when the device needs to quickly wake-up.
VL53L8CX_POWER_MODE_DEEP_SLEEP: This mode clears all memory, by consequence the firmware, the configuration and the calibration are lost. It is recommended when the device sleeps during a long time as it consumes a very low current consumption. Both modes can be changed using function vl53l8cx_set_power_mode().
Definition at line 77 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_power_mode(), and vl53l8cx_set_power_mode().
VL53L8CX_POWER_MODE_WAKEUP
#define VL53L8CX_POWER_MODE_WAKEUP ((uint8_t) 1U)
Definition at line 78 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_power_mode(), and vl53l8cx_set_power_mode().
VL53L8CX_RANGE_SIGMA_MM_BH
#define VL53L8CX_RANGE_SIGMA_MM_BH ((uint32_t)0xDEC40402U)
Definition at line 110 of file vl53l8cx_api.h.
Referenced by vl53l8cx_start_ranging().
VL53L8CX_RANGE_SIGMA_MM_IDX
#define VL53L8CX_RANGE_SIGMA_MM_IDX ((uint16_t)0xDEC4U)
Definition at line 121 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_ranging_data().
VL53L8CX_RANGING_MODE_AUTONOMOUS
#define VL53L8CX_RANGING_MODE_AUTONOMOUS ((uint8_t) 3U)
Definition at line 63 of file vl53l8cx_api.h.
Referenced by lidar_init_sensor(), vl53l8cx_get_ranging_mode(), and vl53l8cx_set_ranging_mode().
VL53L8CX_RANGING_MODE_CONTINUOUS
#define VL53L8CX_RANGING_MODE_CONTINUOUS ((uint8_t) 1U)
Macro VL53L8CX_RANGING_MODE_CONTINUOUS and VL53L8CX_RANGING_MODE_AUTONOMOUS are used to change the ranging mode. Autonomous mode can be used to set a precise integration time, whereas continuous is always maximum.
Definition at line 62 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_ranging_mode(), and vl53l8cx_set_ranging_mode().
VL53L8CX_REFLECTANCE_BH
#define VL53L8CX_REFLECTANCE_BH ((uint32_t)0xE0440401U)
Definition at line 112 of file vl53l8cx_api.h.
Referenced by vl53l8cx_start_ranging().
VL53L8CX_REFLECTANCE_EST_PC_IDX
#define VL53L8CX_REFLECTANCE_EST_PC_IDX ((uint16_t)0xE044U)
Definition at line 123 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_ranging_data().
VL53L8CX_RESOLUTION_4X4
#define VL53L8CX_RESOLUTION_4X4 ((uint8_t) 16U)
Macro VL53L8CX_RESOLUTION_4X4 or VL53L8CX_RESOLUTION_8X8 allows setting sensor in 4x4 mode or 8x8 mode, using function vl53l8cx_set_resolution().
Definition at line 43 of file vl53l8cx_api.h.
Referenced by _vl53l8cx_send_offset_data(), _vl53l8cx_send_xtalk_data(), vl53l8cx_init(), vl53l8cx_motion_indicator_set_resolution(), and vl53l8cx_set_resolution().
VL53L8CX_RESOLUTION_8X8
#define VL53L8CX_RESOLUTION_8X8 ((uint8_t) 64U)
Definition at line 44 of file vl53l8cx_api.h.
Referenced by lidar_init_sensor(), vl53l8cx_calibrate_xtalk(), vl53l8cx_get_caldata_xtalk(), vl53l8cx_get_ranging_data(), vl53l8cx_motion_indicator_set_resolution(), and vl53l8cx_set_resolution().
VL53L8CX_SIGNAL_RATE_BH
#define VL53L8CX_SIGNAL_RATE_BH ((uint32_t)0xDBC40404U)
Definition at line 109 of file vl53l8cx_api.h.
Referenced by vl53l8cx_start_ranging().
VL53L8CX_SIGNAL_RATE_IDX
#define VL53L8CX_SIGNAL_RATE_IDX ((uint16_t)0xDBC4U)
Definition at line 120 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_ranging_data().
VL53L8CX_SPAD_COUNT_BH
#define VL53L8CX_SPAD_COUNT_BH ((uint32_t)0x55D00404U)
Definition at line 107 of file vl53l8cx_api.h.
Referenced by vl53l8cx_start_ranging().
VL53L8CX_SPAD_COUNT_IDX
#define VL53L8CX_SPAD_COUNT_IDX ((uint16_t)0x55D0U)
Definition at line 117 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_ranging_data().
VL53L8CX_START_BH
#define VL53L8CX_START_BH ((uint32_t)0x0000000DU)
Definitions for Range results block headers.
Definition at line 103 of file vl53l8cx_api.h.
Referenced by vl53l8cx_start_ranging().
VL53L8CX_STATUS_CORRUPTED_FRAME
#define VL53L8CX_STATUS_CORRUPTED_FRAME ((uint8_t) 2U)
Definition at line 89 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_ranging_data().
VL53L8CX_STATUS_ERROR
#define VL53L8CX_STATUS_ERROR ((uint8_t) 255U)
Definition at line 95 of file vl53l8cx_api.h.
Referenced by vl53l8cx_calibrate_xtalk(), vl53l8cx_dci_read_data(), vl53l8cx_dci_write_data(), vl53l8cx_get_power_mode(), vl53l8cx_motion_indicator_set_resolution(), vl53l8cx_set_power_mode(), and vl53l8cx_start_ranging().
VL53L8CX_STATUS_FW_CHECKSUM_FAIL
#define VL53L8CX_STATUS_FW_CHECKSUM_FAIL ((uint8_t) 5U)
Definition at line 92 of file vl53l8cx_api.h.
Referenced by vl53l8cx_init().
VL53L8CX_STATUS_INVALID_PARAM
#define VL53L8CX_STATUS_INVALID_PARAM ((uint8_t) 127U)
Definition at line 94 of file vl53l8cx_api.h.
Referenced by vl53l8cx_calibrate_xtalk(), vl53l8cx_motion_indicator_set_distance_motion(), vl53l8cx_set_integration_time_ms(), vl53l8cx_set_ranging_mode(), vl53l8cx_set_resolution(), vl53l8cx_set_sharpener_percent(), vl53l8cx_set_target_order(), and vl53l8cx_set_xtalk_margin().
VL53L8CX_STATUS_LASER_SAFETY
#define VL53L8CX_STATUS_LASER_SAFETY ((uint8_t) 3U)
Definition at line 90 of file vl53l8cx_api.h.
Referenced by vl53l8cx_start_ranging().
VL53L8CX_STATUS_OK
#define VL53L8CX_STATUS_OK ((uint8_t) 0U)
Macro VL53L8CX_STATUS_OK indicates that VL53L5 sensor has no error. Macro VL53L8CX_STATUS_ERROR indicates that something is wrong (value, I2C access, ...). Macro VL53L8CX_MCU_ERROR is used to indicate a MCU issue.
Definition at line 87 of file vl53l8cx_api.h.
Referenced by _vl53l8cx_poll_for_answer(), _vl53l8cx_poll_for_answer(), _vl53l8cx_poll_for_mcu_boot(), _vl53l8cx_program_output_config(), _vl53l8cx_send_offset_data(), _vl53l8cx_send_xtalk_data(), lidar_init_sensor(), lidar_read_sensor(), vl53l8cx_calibrate_xtalk(), vl53l8cx_check_data_ready(), vl53l8cx_dci_read_data(), vl53l8cx_dci_replace_data(), vl53l8cx_dci_write_data(), vl53l8cx_get_caldata_xtalk(), vl53l8cx_get_detection_thresholds(), vl53l8cx_get_detection_thresholds_auto_stop(), vl53l8cx_get_detection_thresholds_enable(), vl53l8cx_get_external_sync_pin_enable(), vl53l8cx_get_integration_time_ms(), vl53l8cx_get_power_mode(), vl53l8cx_get_ranging_data(), vl53l8cx_get_ranging_frequency_hz(), vl53l8cx_get_ranging_mode(), vl53l8cx_get_resolution(), vl53l8cx_get_sharpener_percent(), vl53l8cx_get_target_order(), vl53l8cx_get_VHV_repeat_count(), vl53l8cx_get_xtalk_margin(), vl53l8cx_init(), vl53l8cx_is_alive(), vl53l8cx_motion_indicator_init(), vl53l8cx_motion_indicator_set_distance_motion(), vl53l8cx_motion_indicator_set_resolution(), vl53l8cx_set_caldata_xtalk(), vl53l8cx_set_detection_thresholds(), vl53l8cx_set_detection_thresholds_auto_stop(), vl53l8cx_set_detection_thresholds_enable(), vl53l8cx_set_external_sync_pin_enable(), vl53l8cx_set_i2c_address(), vl53l8cx_set_integration_time_ms(), vl53l8cx_set_power_mode(), vl53l8cx_set_ranging_frequency_hz(), vl53l8cx_set_ranging_mode(), vl53l8cx_set_resolution(), vl53l8cx_set_sharpener_percent(), vl53l8cx_set_target_order(), vl53l8cx_set_VHV_repeat_count(), vl53l8cx_set_xtalk_margin(), vl53l8cx_start_ranging(), and vl53l8cx_stop_ranging().
VL53L8CX_STATUS_TIMEOUT_ERROR
#define VL53L8CX_STATUS_TIMEOUT_ERROR ((uint8_t) 1U)
Definition at line 88 of file vl53l8cx_api.h.
Referenced by _vl53l8cx_poll_for_answer().
VL53L8CX_STATUS_XTALK_FAILED
#define VL53L8CX_STATUS_XTALK_FAILED ((uint8_t) 4U)
Definition at line 91 of file vl53l8cx_api.h.
Referenced by vl53l8cx_calibrate_xtalk().
VL53L8CX_TARGET_ORDER_CLOSEST
#define VL53L8CX_TARGET_ORDER_CLOSEST ((uint8_t) 1U)
Macro VL53L8CX_TARGET_ORDER_STRONGEST or VL53L8CX_TARGET_ORDER_CLOSEST are used to select the target order for data output.
Definition at line 52 of file vl53l8cx_api.h.
Referenced by vl53l8cx_set_target_order().
VL53L8CX_TARGET_ORDER_STRONGEST
#define VL53L8CX_TARGET_ORDER_STRONGEST ((uint8_t) 2U)
Definition at line 53 of file vl53l8cx_api.h.
Referenced by vl53l8cx_set_target_order().
VL53L8CX_TARGET_STATUS_BH
#define VL53L8CX_TARGET_STATUS_BH ((uint32_t)0xE0840401U)
Definition at line 113 of file vl53l8cx_api.h.
Referenced by vl53l8cx_start_ranging().
VL53L8CX_TARGET_STATUS_IDX
#define VL53L8CX_TARGET_STATUS_IDX ((uint16_t)0xE084U)
Definition at line 124 of file vl53l8cx_api.h.
Referenced by vl53l8cx_get_ranging_data().
VL53L8CX_TEMPORARY_BUFFER_SIZE
#define VL53L8CX_TEMPORARY_BUFFER_SIZE ((uint32_t) VL53L8CX_MAX_RESULTS_SIZE)
Macro VL53L8CX_TEMPORARY_BUFFER_SIZE can be used to know the size of the temporary buffer. The minimum size is 1024, and the maximum depends of the output configuration.
Definition at line 263 of file vl53l8cx_api.h.
Referenced by vl53l8cx_dci_read_data(), and vl53l8cx_dci_write_data().
VL53L8CX_UI_CMD_END
#define VL53L8CX_UI_CMD_END ((uint16_t)0x2FFFU)
Definition at line 183 of file vl53l8cx_api.h.
Referenced by vl53l8cx_calibrate_xtalk(), vl53l8cx_dci_read_data(), vl53l8cx_dci_write_data(), and vl53l8cx_start_ranging().
VL53L8CX_UI_CMD_START
#define VL53L8CX_UI_CMD_START ((uint16_t)0x2C04U)
Definition at line 182 of file vl53l8cx_api.h.
Referenced by vl53l8cx_calibrate_xtalk(), vl53l8cx_dci_read_data(), vl53l8cx_get_caldata_xtalk(), and vl53l8cx_init().
VL53L8CX_UI_CMD_STATUS
#define VL53L8CX_UI_CMD_STATUS ((uint16_t)0x2C00U)
Definition at line 181 of file vl53l8cx_api.h.
Referenced by _vl53l8cx_send_offset_data(), _vl53l8cx_send_xtalk_data(), vl53l8cx_calibrate_xtalk(), vl53l8cx_dci_read_data(), vl53l8cx_dci_write_data(), vl53l8cx_get_caldata_xtalk(), vl53l8cx_init(), and vl53l8cx_start_ranging().
VL53L8CX_XTALK_BUFFER_SIZE
#define VL53L8CX_XTALK_BUFFER_SIZE ((uint16_t)776U)
Definition at line 161 of file vl53l8cx_api.h.
Referenced by _vl53l8cx_send_xtalk_data(), vl53l8cx_calibrate_xtalk(), vl53l8cx_get_caldata_xtalk(), vl53l8cx_init(), and vl53l8cx_set_caldata_xtalk().
Function Documentation
vl53l8cx_check_data_ready()
uint8_t vl53l8cx_check_data_ready (VL53L8CX_Configuration * p_dev, uint8_t * p_isReady)
This function checks if a new data is ready by polling I2C. If a new data is ready, a flag will be raised.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) *p_isReady : Value of this pointer be updated to 0 if data is not ready, or 1 if a new data is ready.
Returns
(uint8_t) status : 0 if I2C reading is OK
Definition at line 713 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    status |= VL53L8CX_RdMulti(&(p_dev->platform), 0x0, p_dev->temp_buffer, 4);
    if((p_dev->temp_buffer[0] != p_dev->streamcount)
            && (p_dev->temp_buffer[0] != (uint8_t)255)
            && (p_dev->temp_buffer[1] == (uint8_t)0x5)
            && ((p_dev->temp_buffer[2] & (uint8_t)0x5) == (uint8_t)0x5)
            && ((p_dev->temp_buffer[3] & (uint8_t)0x10) ==(uint8_t)0x10)
            )
    {
        *p_isReady = (uint8_t)1;
         p_dev->streamcount = p_dev->temp_buffer[0];
    }
    else
    {
        if ((p_dev->temp_buffer[3] & (uint8_t)0x80) != (uint8_t)0)
        {
            status |= p_dev->temp_buffer[2]; /* Return GO2 error status */
        }
        *p_isReady = 0;
    }
    return status;
}
References VL53L8CX_Configuration::platform, VL53L8CX_Configuration::streamcount, VL53L8CX_Configuration::temp_buffer, VL53L8CX_RdMulti(), and VL53L8CX_STATUS_OK.
Referenced by lidar_read_sensor().
vl53l8cx_dci_read_data()
uint8_t vl53l8cx_dci_read_data (VL53L8CX_Configuration * p_dev, uint8_t * data, uint32_t index, uint16_t data_size)
This function can be used to read 'extra data' from DCI. Using a known index, the function fills the casted structure passed in argument.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) *data : This field can be a casted structure, or a simple array. Please note that the FW only accept data of 32 bits. So field data can only have a size of 32, 64, 96, 128, bits ....
(uint32_t) index : Index of required value.
(uint16_t)*data_size : This field must be the structure or array size (using sizeof() function).
Returns
(uint8_t) status : 0 if OK
Definition at line 1262 of file vl53l8cx_api.c.
{
    int16_t i;
    uint8_t status = VL53L8CX_STATUS_OK;
        uint32_t rd_size = (uint32_t) data_size + (uint32_t)12;
    uint8_t cmd[] = {0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x0f,
            0x00, 0x02, 0x00, 0x08};
    /* Check if tmp buffer is large enough */
    if((data_size + (uint16_t)12)>(uint16_t)VL53L8CX_TEMPORARY_BUFFER_SIZE)
    {
        status |= VL53L8CX_STATUS_ERROR;
    }
    else
    {
        cmd[0] = (uint8_t)(index >> 8);
        cmd[1] = (uint8_t)(index & (uint32_t)0xff);
        cmd[2] = (uint8_t)((data_size & (uint16_t)0xff0) >> 4);
        cmd[3] = (uint8_t)((data_size & (uint16_t)0xf) << 4);
    /* Request data reading from FW */
        status |= VL53L8CX_WrMulti(&(p_dev->platform),
            (VL53L8CX_UI_CMD_END-(uint16_t)11),cmd, sizeof(cmd));
        status |= _vl53l8cx_poll_for_answer(p_dev, 4, 1,
            VL53L8CX_UI_CMD_STATUS,
            0xff, 0x03);
    /* Read new data sent (4 bytes header + data_size + 8 bytes footer) */
        status |= VL53L8CX_RdMulti(&(p_dev->platform), VL53L8CX_UI_CMD_START,
            p_dev->temp_buffer, rd_size);
        VL53L8CX_SwapBuffer(p_dev->temp_buffer, data_size + (uint16_t)12);
    /* Copy data from FW into input structure (-4 bytes to remove header) */
        for(i = 0 ; i < (int16_t)data_size;i++){
            data[i] = p_dev->temp_buffer[i + 4];
        }
    }
    return status;
}
References _vl53l8cx_poll_for_answer(), VL53L8CX_Configuration::platform, VL53L8CX_Configuration::temp_buffer, VL53L8CX_RdMulti(), VL53L8CX_STATUS_ERROR, VL53L8CX_STATUS_OK, VL53L8CX_SwapBuffer(), VL53L8CX_TEMPORARY_BUFFER_SIZE, VL53L8CX_UI_CMD_END, VL53L8CX_UI_CMD_START, VL53L8CX_UI_CMD_STATUS, and VL53L8CX_WrMulti().
Referenced by vl53l8cx_dci_replace_data(), vl53l8cx_get_detection_thresholds(), vl53l8cx_get_detection_thresholds_auto_stop(), vl53l8cx_get_detection_thresholds_enable(), vl53l8cx_get_external_sync_pin_enable(), vl53l8cx_get_integration_time_ms(), vl53l8cx_get_ranging_frequency_hz(), vl53l8cx_get_ranging_mode(), vl53l8cx_get_resolution(), vl53l8cx_get_sharpener_percent(), vl53l8cx_get_target_order(), vl53l8cx_get_VHV_repeat_count(), vl53l8cx_get_xtalk_margin(), vl53l8cx_set_external_sync_pin_enable(), vl53l8cx_set_ranging_mode(), vl53l8cx_set_resolution(), and vl53l8cx_start_ranging().
vl53l8cx_dci_replace_data()
uint8_t vl53l8cx_dci_replace_data (VL53L8CX_Configuration * p_dev, uint8_t * data, uint32_t index, uint16_t data_size, uint8_t * new_data, uint16_t new_data_size, uint16_t new_data_pos)
This function can be used to replace 'extra data' in DCI. The data can be simple data, or casted structure.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) *data : This field can be a casted structure, or a simple array. Please note that the FW only accept data of 32 bits. So field data can only have a size of 32, 64, 96, 128, bits ..
(uint32_t) index : Index of required value.
(uint16_t)*data_size : This field must be the structure or array size (using sizeof() function).
(uint8_t) *new_data : Contains the new fields.
(uint16_t) new_data_size : New data size.
(uint16_t) new_data_pos : New data position into the buffer.
Returns
(uint8_t) status : 0 if OK
Definition at line 1363 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    status |= vl53l8cx_dci_read_data(p_dev, data, index, data_size);
    (void)memcpy(&(data[new_data_pos]), new_data, new_data_size);
    status |= vl53l8cx_dci_write_data(p_dev, data, index, data_size);
    return status;
}
References vl53l8cx_dci_read_data(), vl53l8cx_dci_write_data(), and VL53L8CX_STATUS_OK.
Referenced by vl53l8cx_calibrate_xtalk(), vl53l8cx_init(), vl53l8cx_set_detection_thresholds_auto_stop(), vl53l8cx_set_detection_thresholds_enable(), vl53l8cx_set_integration_time_ms(), vl53l8cx_set_ranging_frequency_hz(), vl53l8cx_set_sharpener_percent(), vl53l8cx_set_target_order(), vl53l8cx_set_VHV_repeat_count(), and vl53l8cx_set_xtalk_margin().
vl53l8cx_dci_write_data()
uint8_t vl53l8cx_dci_write_data (VL53L8CX_Configuration * p_dev, uint8_t * data, uint32_t index, uint16_t data_size)
This function can be used to write 'extra data' to DCI. The data can be simple data, or casted structure.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) *data : This field can be a casted structure, or a simple array. Please note that the FW only accept data of 32 bits. So field data can only have a size of 32, 64, 96, 128, bits ..
(uint32_t) index : Index of required value.
(uint16_t)*data_size : This field must be the structure or array size (using sizeof() function).
Returns
(uint8_t) status : 0 if OK
Definition at line 1308 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    int16_t i;
    uint8_t headers[] = {0x00, 0x00, 0x00, 0x00};
    uint8_t footer[] = {0x00, 0x00, 0x00, 0x0f, 0x05, 0x01,
            (uint8_t)((data_size + (uint16_t)8) >> 8),
            (uint8_t)((data_size + (uint16_t)8) & (uint8_t)0xFF)};
    uint16_t address = (uint16_t)VL53L8CX_UI_CMD_END -
        (data_size + (uint16_t)12) + (uint16_t)1;
    /* Check if cmd buffer is large enough */
    if((data_size + (uint16_t)12)
           > (uint16_t)VL53L8CX_TEMPORARY_BUFFER_SIZE)
    {
        status |= VL53L8CX_STATUS_ERROR;
    }
    else
    {
        headers[0] = (uint8_t)(index >> 8);
        headers[1] = (uint8_t)(index & (uint32_t)0xff);
        headers[2] = (uint8_t)(((data_size & (uint16_t)0xff0) >> 4));
        headers[3] = (uint8_t)((data_size & (uint16_t)0xf) << 4);
    /* Copy data from structure to FW format (+4 bytes to add header) */
        VL53L8CX_SwapBuffer(data, data_size);
        for(i = (int16_t)data_size - (int16_t)1 ; i >= 0; i--)
        {
            p_dev->temp_buffer[i + 4] = data[i];
        }
    /* Add headers and footer */
        (void)memcpy(&p_dev->temp_buffer[0], headers, sizeof(headers));
        (void)memcpy(&p_dev->temp_buffer[data_size + (uint16_t)4],
            footer, sizeof(footer));
    /* Send data to FW */
        status |= VL53L8CX_WrMulti(&(p_dev->platform),address,
            p_dev->temp_buffer,
            (uint32_t)((uint32_t)data_size + (uint32_t)12));
        status |= _vl53l8cx_poll_for_answer(p_dev, 4, 1,
            VL53L8CX_UI_CMD_STATUS, 0xff, 0x03);
        VL53L8CX_SwapBuffer(data, data_size);
    }
    return status;
}
References _vl53l8cx_poll_for_answer(), VL53L8CX_Configuration::platform, VL53L8CX_Configuration::temp_buffer, VL53L8CX_STATUS_ERROR, VL53L8CX_STATUS_OK, VL53L8CX_SwapBuffer(), VL53L8CX_TEMPORARY_BUFFER_SIZE, VL53L8CX_UI_CMD_END, VL53L8CX_UI_CMD_STATUS, and VL53L8CX_WrMulti().
Referenced by _vl53l8cx_program_output_config(), vl53l8cx_dci_replace_data(), vl53l8cx_init(), vl53l8cx_motion_indicator_set_distance_motion(), vl53l8cx_motion_indicator_set_resolution(), vl53l8cx_set_detection_thresholds(), vl53l8cx_set_external_sync_pin_enable(), vl53l8cx_set_ranging_mode(), vl53l8cx_set_resolution(), and vl53l8cx_start_ranging().
vl53l8cx_get_external_sync_pin_enable()
uint8_t vl53l8cx_get_external_sync_pin_enable (VL53L8CX_Configuration * p_dev, uint8_t * p_is_sync_pin_enabled)
This function is used to check if the synchronization pin is enabled or disabled. When it is enabled, the sensor waits an interrupt on B1 pin to start the next measurement. It is useful for multi-devices synchronization. By default the sync pin is disabled.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t*) p_is_sync_pin_enabled : Pointer of sync pin status. Value overridden to 0 if the pin is disabled, or 1 if the pin is enabled.
Returns
(uint8_t) status : 0 if get sync pin OK.
Definition at line 1185 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    status |= vl53l8cx_dci_read_data(p_dev, p_dev->temp_buffer,
            VL53L8CX_DCI_SYNC_PIN, 4);
    /* Check bit 1 value (get sync pause bit) */
    if((p_dev->temp_buffer[3] & (uint8_t)0x2) != (uint8_t)0)
    {
        *p_is_sync_pin_enabled = (uint8_t)1;
    }
    else
    {
        *p_is_sync_pin_enabled = (uint8_t)0;
    }
    return status;
}
References VL53L8CX_Configuration::temp_buffer, vl53l8cx_dci_read_data(), VL53L8CX_DCI_SYNC_PIN, and VL53L8CX_STATUS_OK.
vl53l8cx_get_integration_time_ms()
uint8_t vl53l8cx_get_integration_time_ms (VL53L8CX_Configuration * p_dev, uint32_t * p_time_ms)
This function gets the current integration time in ms.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint32_t) *p_time_ms: Contains integration time in ms.
Returns
(uint8_t) status : 0 if integration time is OK.
Definition at line 1016 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    status |= vl53l8cx_dci_read_data(p_dev, (uint8_t*)p_dev->temp_buffer,
            VL53L8CX_DCI_INT_TIME, 20);
    (void)memcpy(p_time_ms, &(p_dev->temp_buffer[0x0]), 4);
    *p_time_ms /= (uint32_t)1000;
    return status;
}
References VL53L8CX_Configuration::temp_buffer, VL53L8CX_DCI_INT_TIME, vl53l8cx_dci_read_data(), and VL53L8CX_STATUS_OK.
Referenced by vl53l8cx_calibrate_xtalk().
vl53l8cx_get_power_mode()
uint8_t vl53l8cx_get_power_mode (VL53L8CX_Configuration * p_dev, uint8_t * p_power_mode)
This function is used to get the current sensor power mode.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) *p_power_mode : Current power mode. The value of this pointer is equal to 0 if the sensor is in low power, (VL53L8CX_POWER_MODE_SLEEP), or 1 if sensor is in standard mode (VL53L8CX_POWER_MODE_WAKEUP).
Returns
(uint8_t) status : 0 if power mode is OK
Definition at line 425 of file vl53l8cx_api.c.
{
    uint8_t tmp, status = VL53L8CX_STATUS_OK;
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7FFF, 0x00);
    status |= VL53L8CX_RdByte(&(p_dev->platform), 0x009, &tmp);
    switch(tmp)
    {
        case 0x4:
            *p_power_mode = VL53L8CX_POWER_MODE_WAKEUP;
            break;
        case 0x2:
            status |= VL53L8CX_RdByte(&(p_dev->platform), 0x000F, &tmp);
            if(tmp == 0x43)
            {
                *p_power_mode = VL53L8CX_POWER_MODE_DEEP_SLEEP;
            }
            else
            {
                *p_power_mode = VL53L8CX_POWER_MODE_SLEEP;
            }
            break;
        default:
            *p_power_mode = 0;
            status = VL53L8CX_STATUS_ERROR;
            break;
    }
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7FFF, 0x02);
    return status;
}
References VL53L8CX_Configuration::platform, VL53L8CX_POWER_MODE_DEEP_SLEEP, VL53L8CX_POWER_MODE_SLEEP, VL53L8CX_POWER_MODE_WAKEUP, VL53L8CX_RdByte(), VL53L8CX_STATUS_ERROR, VL53L8CX_STATUS_OK, and VL53L8CX_WrByte().
Referenced by vl53l8cx_set_power_mode().
vl53l8cx_get_ranging_data()
uint8_t vl53l8cx_get_ranging_data (VL53L8CX_Configuration * p_dev, VL53L8CX_ResultsData * p_results)
This function gets the ranging data, using the selected output and the resolution.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(VL53L8CX_ResultsData) *p_results : VL53L5 results structure.
Returns
(uint8_t) status : 0 data are successfully get.
Definition at line 744 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    uint16_t header_id, footer_id;
    union Block_header *bh_ptr;
    uint32_t i, j, msize;
    status |= VL53L8CX_RdMulti(&(p_dev->platform), 0x0,
            p_dev->temp_buffer, p_dev->data_read_size);
    p_dev->streamcount = p_dev->temp_buffer[0];
    VL53L8CX_SwapBuffer(p_dev->temp_buffer, (uint16_t)p_dev->data_read_size);
    /* Start conversion at position 16 to avoid headers */
    for (i = (uint32_t)16; i
             < (uint32_t)p_dev->data_read_size; i+=(uint32_t)4)
    {
        bh_ptr = (union Block_header *)&(p_dev->temp_buffer[i]);
        if ((bh_ptr->type > (uint32_t)0x1)
                    && (bh_ptr->type < (uint32_t)0xd))
        {
            msize = bh_ptr->type * bh_ptr->size;
        }
        else
        {
            msize = bh_ptr->size;
        }
        switch(bh_ptr->idx){
            case VL53L8CX_METADATA_IDX:
                p_results->silicon_temp_degc =
                        (int8_t)p_dev->temp_buffer[i + (uint32_t)12];
                break;
#ifndef VL53L8CX_DISABLE_AMBIENT_PER_SPAD
            case VL53L8CX_AMBIENT_RATE_IDX:
                (void)memcpy(p_results->ambient_per_spad,
                &(p_dev->temp_buffer[i + (uint32_t)4]), msize);
                break;
#endif
#ifndef VL53L8CX_DISABLE_NB_SPADS_ENABLED
            case VL53L8CX_SPAD_COUNT_IDX:
                (void)memcpy(p_results->nb_spads_enabled,
                &(p_dev->temp_buffer[i + (uint32_t)4]), msize);
                break;
#endif
#ifndef VL53L8CX_DISABLE_NB_TARGET_DETECTED
            case VL53L8CX_NB_TARGET_DETECTED_IDX:
                (void)memcpy(p_results->nb_target_detected,
                &(p_dev->temp_buffer[i + (uint32_t)4]), msize);
                break;
#endif
#ifndef VL53L8CX_DISABLE_SIGNAL_PER_SPAD
            case VL53L8CX_SIGNAL_RATE_IDX:
                (void)memcpy(p_results->signal_per_spad,
                &(p_dev->temp_buffer[i + (uint32_t)4]), msize);
                break;
#endif
#ifndef VL53L8CX_DISABLE_RANGE_SIGMA_MM
            case VL53L8CX_RANGE_SIGMA_MM_IDX:
                (void)memcpy(p_results->range_sigma_mm,
                &(p_dev->temp_buffer[i + (uint32_t)4]), msize);
                break;
#endif
#ifndef VL53L8CX_DISABLE_DISTANCE_MM
            case VL53L8CX_DISTANCE_IDX:
                (void)memcpy(p_results->distance_mm,
                &(p_dev->temp_buffer[i + (uint32_t)4]), msize);
                break;
#endif
#ifndef VL53L8CX_DISABLE_REFLECTANCE_PERCENT
            case VL53L8CX_REFLECTANCE_EST_PC_IDX:
                (void)memcpy(p_results->reflectance,
                &(p_dev->temp_buffer[i + (uint32_t)4]), msize);
                break;
#endif
#ifndef VL53L8CX_DISABLE_TARGET_STATUS
            case VL53L8CX_TARGET_STATUS_IDX:
                (void)memcpy(p_results->target_status,
                &(p_dev->temp_buffer[i + (uint32_t)4]), msize);
                break;
#endif
#ifndef VL53L8CX_DISABLE_MOTION_INDICATOR
            case VL53L8CX_MOTION_DETEC_IDX:
                (void)memcpy(&p_results->motion_indicator,
                &(p_dev->temp_buffer[i + (uint32_t)4]), msize);
                break;
#endif
            default:
                break;
        }
        i += msize;
    }
#ifndef VL53L8CX_USE_RAW_FORMAT
    /* Convert data into their real format */
#ifndef VL53L8CX_DISABLE_AMBIENT_PER_SPAD
    for(i = 0; i < (uint32_t)VL53L8CX_RESOLUTION_8X8; i++)
    {
        p_results->ambient_per_spad[i] /= (uint32_t)2048;
    }
#endif
    for(i = 0; i < (uint32_t)(VL53L8CX_RESOLUTION_8X8
            *VL53L8CX_NB_TARGET_PER_ZONE); i++)
    {
#ifndef VL53L8CX_DISABLE_DISTANCE_MM
        p_results->distance_mm[i] /= 4;
#endif
#ifndef VL53L8CX_DISABLE_REFLECTANCE_PERCENT
        p_results->reflectance[i] /= (uint8_t)2;
#endif
#ifndef VL53L8CX_DISABLE_RANGE_SIGMA_MM
        p_results->range_sigma_mm[i] /= (uint16_t)128;
#endif
#ifndef VL53L8CX_DISABLE_SIGNAL_PER_SPAD
        p_results->signal_per_spad[i] /= (uint32_t)2048;
#endif
    }
    /* Set target status to 255 if no target is detected for this zone */
#ifndef VL53L8CX_DISABLE_NB_TARGET_DETECTED
    for(i = 0; i < (uint32_t)VL53L8CX_RESOLUTION_8X8; i++)
    {
        if(p_results->nb_target_detected[i] == (uint8_t)0){
            for(j = 0; j < (uint32_t)
                VL53L8CX_NB_TARGET_PER_ZONE; j++)
            {
#ifndef VL53L8CX_DISABLE_TARGET_STATUS
                p_results->target_status
                [((uint32_t)VL53L8CX_NB_TARGET_PER_ZONE
                    *(uint32_t)i) + j]=(uint8_t)255;
#endif
            }
        }
    }
#endif
#ifndef VL53L8CX_DISABLE_MOTION_INDICATOR
    for(i = 0; i < (uint32_t)32; i++)
    {
        p_results->motion_indicator.motion[i] /= (uint32_t)65535;
    }
#endif
#endif
    /* Check if footer id and header id are matching. This allows to detect
     * corrupted frames */
    header_id = ((uint16_t)(p_dev->temp_buffer[0x8])<<8) & 0xFF00U;
    header_id |= ((uint16_t)(p_dev->temp_buffer[0x9])) & 0x00FFU;
    footer_id = ((uint16_t)(p_dev->temp_buffer[p_dev->data_read_size
        - (uint32_t)4]) << 8) & 0xFF00U;
    footer_id |= ((uint16_t)(p_dev->temp_buffer[p_dev->data_read_size
        - (uint32_t)3])) & 0xFFU;
    if(header_id != footer_id)
    {
        status |= VL53L8CX_STATUS_CORRUPTED_FRAME;
    }
    return status;
}
References VL53L8CX_ResultsData::ambient_per_spad, VL53L8CX_Configuration::data_read_size, VL53L8CX_ResultsData::distance_mm, Block_header::idx, VL53L8CX_ResultsData::motion, VL53L8CX_ResultsData::motion_indicator, VL53L8CX_ResultsData::nb_spads_enabled, VL53L8CX_ResultsData::nb_target_detected, VL53L8CX_Configuration::platform, VL53L8CX_ResultsData::range_sigma_mm, VL53L8CX_ResultsData::reflectance, VL53L8CX_ResultsData::signal_per_spad, VL53L8CX_ResultsData::silicon_temp_degc, Block_header::size, VL53L8CX_Configuration::streamcount, VL53L8CX_ResultsData::target_status, VL53L8CX_Configuration::temp_buffer, Block_header::type, VL53L8CX_AMBIENT_RATE_IDX, VL53L8CX_DISTANCE_IDX, VL53L8CX_METADATA_IDX, VL53L8CX_MOTION_DETEC_IDX, VL53L8CX_NB_TARGET_DETECTED_IDX, VL53L8CX_NB_TARGET_PER_ZONE, VL53L8CX_RANGE_SIGMA_MM_IDX, VL53L8CX_RdMulti(), VL53L8CX_REFLECTANCE_EST_PC_IDX, VL53L8CX_RESOLUTION_8X8, VL53L8CX_SIGNAL_RATE_IDX, VL53L8CX_SPAD_COUNT_IDX, VL53L8CX_STATUS_CORRUPTED_FRAME, VL53L8CX_STATUS_OK, VL53L8CX_SwapBuffer(), and VL53L8CX_TARGET_STATUS_IDX.
Referenced by lidar_read_sensor().
vl53l8cx_get_ranging_frequency_hz()
uint8_t vl53l8cx_get_ranging_frequency_hz (VL53L8CX_Configuration * p_dev, uint8_t * p_frequency_hz)
This function gets the current ranging frequency in Hz. Ranging frequency corresponds to the time between each measurement.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) *p_frequency_hz: Contains the ranging frequency in Hz.
Returns
(uint8_t) status : 0 if ranging frequency is OK.
Definition at line 990 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    status |= vl53l8cx_dci_read_data(p_dev, (uint8_t*)p_dev->temp_buffer,
            VL53L8CX_DCI_FREQ_HZ, 4);
    *p_frequency_hz = p_dev->temp_buffer[0x01];
    return status;
}
References VL53L8CX_Configuration::temp_buffer, VL53L8CX_DCI_FREQ_HZ, vl53l8cx_dci_read_data(), and VL53L8CX_STATUS_OK.
Referenced by vl53l8cx_calibrate_xtalk().
vl53l8cx_get_ranging_mode()
uint8_t vl53l8cx_get_ranging_mode (VL53L8CX_Configuration * p_dev, uint8_t * p_ranging_mode)
This function is used to get the ranging mode. Two modes are available using ULD : Continuous and autonomous. The default mode is Autonomous.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) *p_ranging_mode : current ranging mode
Returns
(uint8_t) status : 0 if get ranging mode is OK.
Definition at line 1125 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    status |= vl53l8cx_dci_read_data(p_dev, p_dev->temp_buffer,
            VL53L8CX_DCI_RANGING_MODE, 8);
    if(p_dev->temp_buffer[0x01] == (uint8_t)0x1)
    {
        *p_ranging_mode = VL53L8CX_RANGING_MODE_CONTINUOUS;
    }
    else
    {
        *p_ranging_mode = VL53L8CX_RANGING_MODE_AUTONOMOUS;
    }
    return status;
}
References VL53L8CX_Configuration::temp_buffer, VL53L8CX_DCI_RANGING_MODE, vl53l8cx_dci_read_data(), VL53L8CX_RANGING_MODE_AUTONOMOUS, VL53L8CX_RANGING_MODE_CONTINUOUS, and VL53L8CX_STATUS_OK.
Referenced by vl53l8cx_calibrate_xtalk().
vl53l8cx_get_resolution()
uint8_t vl53l8cx_get_resolution (VL53L8CX_Configuration * p_dev, uint8_t * p_resolution)
This function gets the current resolution (4x4 or 8x8).
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) *p_resolution : Value of this pointer will be equal to 16 for 4x4 mode, and 64 for 8x8 mode.
Returns
(uint8_t) status : 0 if resolution is OK.
Definition at line 910 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    status |= vl53l8cx_dci_read_data(p_dev, p_dev->temp_buffer,
            VL53L8CX_DCI_ZONE_CONFIG, 8);
    *p_resolution = p_dev->temp_buffer[0x00]*p_dev->temp_buffer[0x01];
    return status;
}
References VL53L8CX_Configuration::temp_buffer, vl53l8cx_dci_read_data(), VL53L8CX_DCI_ZONE_CONFIG, and VL53L8CX_STATUS_OK.
Referenced by _vl53l8cx_program_output_config(), vl53l8cx_calibrate_xtalk(), vl53l8cx_get_caldata_xtalk(), vl53l8cx_set_caldata_xtalk(), and vl53l8cx_start_ranging().
vl53l8cx_get_sharpener_percent()
uint8_t vl53l8cx_get_sharpener_percent (VL53L8CX_Configuration * p_dev, uint8_t * p_sharpener_percent)
This function gets the current sharpener in percent. Sharpener can be changed to blur more or less zones depending of the application.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint32_t) *p_sharpener_percent: Contains the sharpener in percent.
Returns
(uint8_t) status : 0 if get sharpener is OK.
Definition at line 1055 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    status |= vl53l8cx_dci_read_data(p_dev,p_dev->temp_buffer,
            VL53L8CX_DCI_SHARPENER, 16);
    *p_sharpener_percent = (p_dev->temp_buffer[0xD]
                                *(uint8_t)100)/(uint8_t)255;
    return status;
}
References VL53L8CX_Configuration::temp_buffer, vl53l8cx_dci_read_data(), VL53L8CX_DCI_SHARPENER, and VL53L8CX_STATUS_OK.
Referenced by vl53l8cx_calibrate_xtalk().
vl53l8cx_get_target_order()
uint8_t vl53l8cx_get_target_order (VL53L8CX_Configuration * p_dev, uint8_t * p_target_order)
This function gets the current target order (closest or strongest).
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) *p_target_order: Contains the target order.
Returns
(uint8_t) status : 0 if get target order is OK.
Definition at line 1092 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    status |= vl53l8cx_dci_read_data(p_dev, (uint8_t*)p_dev->temp_buffer,
            VL53L8CX_DCI_TARGET_ORDER, 4);
    *p_target_order = (uint8_t)p_dev->temp_buffer[0x0];
    return status;
}
References VL53L8CX_Configuration::temp_buffer, vl53l8cx_dci_read_data(), VL53L8CX_DCI_TARGET_ORDER, and VL53L8CX_STATUS_OK.
Referenced by vl53l8cx_calibrate_xtalk().
vl53l8cx_get_VHV_repeat_count()
uint8_t vl53l8cx_get_VHV_repeat_count (VL53L8CX_Configuration * p_dev, uint32_t * p_repeat_count)
This function is used to get the number of frames between 2 temperature compensation.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint32_t) *p_repeat_count : Number of frames before next temperature compensation. Set to 0 to disable the feature (default configuration).
Definition at line 1236 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    status |= vl53l8cx_dci_read_data(p_dev, (uint8_t*)p_dev->temp_buffer,
            VL53L8CX_DCI_VHV_CONFIG, 16);
    *p_repeat_count = ((uint32_t)p_dev->temp_buffer[7] << 24)
            | ((uint32_t)p_dev->temp_buffer[6] << 16)
            | ((uint32_t)p_dev->temp_buffer[5] << 8)
            | (uint32_t)p_dev->temp_buffer[4];
    return status;
}
References VL53L8CX_Configuration::temp_buffer, vl53l8cx_dci_read_data(), VL53L8CX_DCI_VHV_CONFIG, and VL53L8CX_STATUS_OK.
vl53l8cx_init()
uint8_t vl53l8cx_init (VL53L8CX_Configuration * p_dev)
Mandatory function used to initialize the sensor. This function must be called after a power on, to load the firmware into the VL53L8CX. It takes a few hundred milliseconds.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
Returns
(uint8_t) status : 0 if initialization is OK.
Definition at line 243 of file vl53l8cx_api.c.
{
    uint8_t tmp, status = VL53L8CX_STATUS_OK;
    uint8_t pipe_ctrl[] = {VL53L8CX_NB_TARGET_PER_ZONE, 0x00, 0x01, 0x00};
    uint32_t single_range = 0x01;
    uint32_t crc_checksum = 0x00;
    p_dev->default_xtalk = (uint8_t*)VL53L8CX_DEFAULT_XTALK;
    p_dev->default_configuration = (uint8_t*)VL53L8CX_DEFAULT_CONFIGURATION;
    p_dev->is_auto_stop_enabled = (uint8_t)0x0;
    /* SW reboot sequence */
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x0009, 0x04);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x000F, 0x40);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x000A, 0x03);
    status |= VL53L8CX_RdByte(&(p_dev->platform), 0x7FFF, &tmp);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x000C, 0x01);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x0101, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x0102, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x010A, 0x01);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x4002, 0x01);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x4002, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x010A, 0x03);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x0103, 0x01);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x000C, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x000F, 0x43);
    status |= VL53L8CX_WaitMs(&(p_dev->platform), 1);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x000F, 0x40);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x000A, 0x01);
    status |= VL53L8CX_WaitMs(&(p_dev->platform), 100);
    /* Wait for sensor booted (several ms required to get sensor ready) */
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x00);
    status |= _vl53l8cx_poll_for_answer(p_dev, 1, 0, 0x06, 0xff, 1);
    if(status != (uint8_t)0){
        goto exit;
    }
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x000E, 0x01);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x02);
    /* Enable FW access */
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x01);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x06, 0x01);
    status |= _vl53l8cx_poll_for_answer(p_dev, 1, 0, 0x21, 0xFF, 0x4);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x00);
    /* Enable host access to GO1 */
    status |= VL53L8CX_RdByte(&(p_dev->platform), 0x7fff, &tmp);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x0C, 0x01);
    /* Power ON status */
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x101, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x102, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x010A, 0x01);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x4002, 0x01);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x4002, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x010A, 0x03);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x103, 0x01);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x400F, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x21A, 0x43);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x21A, 0x03);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x21A, 0x01);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x21A, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x219, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x21B, 0x00);
    /* Wake up MCU */
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x00);
    status |= VL53L8CX_RdByte(&(p_dev->platform), 0x7fff, &tmp);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x01);
    /* Download FW into VL53L8CX */
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x09);
    status |= VL53L8CX_WrMulti(&(p_dev->platform),0,
        (uint8_t*)&VL53L8CX_FIRMWARE[0],0x8000);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x0a);
    status |= VL53L8CX_WrMulti(&(p_dev->platform),0,
        (uint8_t*)&VL53L8CX_FIRMWARE[0x8000],0x8000);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x0b);
    status |= VL53L8CX_WrMulti(&(p_dev->platform),0,
        (uint8_t*)&VL53L8CX_FIRMWARE[0x10000],0x5000);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x01);
    /* Check if FW correctly downloaded */
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x01);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x06, 0x03);
    status |= VL53L8CX_WaitMs(&(p_dev->platform), 5);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x00);
    status |= VL53L8CX_RdByte(&(p_dev->platform), 0x7fff, &tmp);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x0C, 0x01);
    /* Reset MCU and wait boot */
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7FFF, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x114, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x115, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x116, 0x42);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x117, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x0B, 0x00);
    status |= VL53L8CX_RdByte(&(p_dev->platform), 0x7fff, &tmp);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x0C, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x0B, 0x01);
    status |= _vl53l8cx_poll_for_mcu_boot(p_dev);
    if(status != (uint8_t)0){
        goto exit;
    }
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x02);
    /* Firmware checksum */
    status |= VL53L8CX_RdMulti(&(p_dev->platform), (uint16_t)(0x812FFC & 0xFFFF),
            p_dev->temp_buffer, 4);
    VL53L8CX_SwapBuffer(p_dev->temp_buffer, 4);
    memcpy((uint8_t*)&crc_checksum, &(p_dev->temp_buffer[0]), 4);
    if (crc_checksum != (uint32_t)0xc0b6c9e)
    {
        status |= VL53L8CX_STATUS_FW_CHECKSUM_FAIL;
        goto exit;
    }
    /* Get offset NVM data and store them into the offset buffer */
    status |= VL53L8CX_WrMulti(&(p_dev->platform), 0x2fd8,
        (uint8_t*)VL53L8CX_GET_NVM_CMD, sizeof(VL53L8CX_GET_NVM_CMD));
    status |= _vl53l8cx_poll_for_answer(p_dev, 4, 0,
        VL53L8CX_UI_CMD_STATUS, 0xff, 2);
    status |= VL53L8CX_RdMulti(&(p_dev->platform), VL53L8CX_UI_CMD_START,
        p_dev->temp_buffer, VL53L8CX_NVM_DATA_SIZE);
    (void)memcpy(p_dev->offset_data, p_dev->temp_buffer,
        VL53L8CX_OFFSET_BUFFER_SIZE);
    status |= _vl53l8cx_send_offset_data(p_dev, VL53L8CX_RESOLUTION_4X4);
    /* Set default Xtalk shape. Send Xtalk to sensor */
    (void)memcpy(p_dev->xtalk_data, (uint8_t*)VL53L8CX_DEFAULT_XTALK,
        VL53L8CX_XTALK_BUFFER_SIZE);
    status |= _vl53l8cx_send_xtalk_data(p_dev, VL53L8CX_RESOLUTION_4X4);
    /* Send default configuration to VL53L8CX firmware */
    status |= VL53L8CX_WrMulti(&(p_dev->platform), 0x2c34,
        p_dev->default_configuration,
        sizeof(VL53L8CX_DEFAULT_CONFIGURATION));
    status |= _vl53l8cx_poll_for_answer(p_dev, 4, 1,
        VL53L8CX_UI_CMD_STATUS, 0xff, 0x03);
    status |= vl53l8cx_dci_write_data(p_dev, (uint8_t*)&pipe_ctrl,
        VL53L8CX_DCI_PIPE_CONTROL, (uint16_t)sizeof(pipe_ctrl));
#if VL53L8CX_NB_TARGET_PER_ZONE != 1
    tmp = VL53L8CX_NB_TARGET_PER_ZONE;
    status |= vl53l8cx_dci_replace_data(p_dev, p_dev->temp_buffer,
        VL53L8CX_DCI_FW_NB_TARGET, 16,
    (uint8_t*)&tmp, 1, 0x0C);
#endif
    status |= vl53l8cx_dci_write_data(p_dev, (uint8_t*)&single_range,
            VL53L8CX_DCI_SINGLE_RANGE,
            (uint16_t)sizeof(single_range));
exit:
    return status;
}
References _vl53l8cx_poll_for_answer(), _vl53l8cx_poll_for_mcu_boot(), _vl53l8cx_send_offset_data(), _vl53l8cx_send_xtalk_data(), VL53L8CX_Configuration::default_configuration, VL53L8CX_Configuration::default_xtalk, VL53L8CX_Configuration::is_auto_stop_enabled, VL53L8CX_Configuration::offset_data, VL53L8CX_Configuration::platform, VL53L8CX_Configuration::temp_buffer, VL53L8CX_DCI_FW_NB_TARGET, VL53L8CX_DCI_PIPE_CONTROL, vl53l8cx_dci_replace_data(), VL53L8CX_DCI_SINGLE_RANGE, vl53l8cx_dci_write_data(), VL53L8CX_DEFAULT_CONFIGURATION, VL53L8CX_DEFAULT_XTALK, VL53L8CX_FIRMWARE, VL53L8CX_GET_NVM_CMD, VL53L8CX_NB_TARGET_PER_ZONE, VL53L8CX_NVM_DATA_SIZE, VL53L8CX_OFFSET_BUFFER_SIZE, VL53L8CX_RdByte(), VL53L8CX_RdMulti(), VL53L8CX_RESOLUTION_4X4, VL53L8CX_STATUS_FW_CHECKSUM_FAIL, VL53L8CX_STATUS_OK, VL53L8CX_SwapBuffer(), VL53L8CX_UI_CMD_START, VL53L8CX_UI_CMD_STATUS, VL53L8CX_WaitMs(), VL53L8CX_WrByte(), VL53L8CX_WrMulti(), VL53L8CX_XTALK_BUFFER_SIZE, and VL53L8CX_Configuration::xtalk_data.
Referenced by lidar_init_sensor(), and vl53l8cx_set_power_mode().
vl53l8cx_is_alive()
uint8_t vl53l8cx_is_alive (VL53L8CX_Configuration * p_dev, uint8_t * p_is_alive)
Definition at line 219 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    uint8_t device_id, revision_id;
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x00);
    status |= VL53L8CX_RdByte(&(p_dev->platform), 0, &device_id);
    status |= VL53L8CX_RdByte(&(p_dev->platform), 1, &revision_id);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x02);
    if((device_id == (uint8_t)0xF0) && (revision_id == (uint8_t)0x0C))
    {
        *p_is_alive = 1;
    }
    else
    {
        *p_is_alive = 0;
    }
    return status;
}
References VL53L8CX_Configuration::platform, VL53L8CX_RdByte(), VL53L8CX_STATUS_OK, and VL53L8CX_WrByte().
vl53l8cx_set_external_sync_pin_enable()
uint8_t vl53l8cx_set_external_sync_pin_enable (VL53L8CX_Configuration * p_dev, uint8_t enable_sync_pin)
This function is used to enable or disable the synchronization pin. When it is enabled, the sensor waits an interrupt on B1 pin to start the next measurement. It is useful for multi-devices synchronization. By default the sync pin is disabled.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) enable_sync_pin : Ste the value to 1 to enable the sync pin, or 0 to disable it.
Returns
(uint8_t) status : 0 if set sync pin OK.
Definition at line 1207 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
        uint32_t tmp;
    status |= vl53l8cx_dci_read_data(p_dev, p_dev->temp_buffer,
            VL53L8CX_DCI_SYNC_PIN, 4);
        tmp = (uint32_t)p_dev->temp_buffer[3];
    /* Update bit 1 with mask (set sync pause bit) */
    if(enable_sync_pin == (uint8_t)0)
    {
                tmp &= ~(1UL << 1);
    }
    else
    {
                tmp |= 1UL << 1;
    }
        p_dev->temp_buffer[3] = (uint8_t)tmp;
    status |= vl53l8cx_dci_write_data(p_dev, p_dev->temp_buffer,
            VL53L8CX_DCI_SYNC_PIN, 4);
    return status;
}
References VL53L8CX_Configuration::temp_buffer, vl53l8cx_dci_read_data(), VL53L8CX_DCI_SYNC_PIN, vl53l8cx_dci_write_data(), and VL53L8CX_STATUS_OK.
vl53l8cx_set_i2c_address()
uint8_t vl53l8cx_set_i2c_address (VL53L8CX_Configuration * p_dev, uint16_t i2c_address)
This function is used to change the I2C address of the sensor. If multiple VL53L5 sensors are connected to the same I2C line, all other LPn pins needs to be set to Low. The default sensor address is 0x52.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint16_t) i2c_address : New I2C address.
Returns
(uint8_t) status : 0 if new address is OK
Definition at line 411 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x4, (uint8_t)(i2c_address >> 1));
    p_dev->platform.address = i2c_address;
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x02);
    return status;
}
References VL53L8CX_Platform::address, VL53L8CX_Configuration::platform, VL53L8CX_STATUS_OK, and VL53L8CX_WrByte().
vl53l8cx_set_integration_time_ms()
uint8_t vl53l8cx_set_integration_time_ms (VL53L8CX_Configuration * p_dev, uint32_t integration_time_ms)
This function sets a new integration time in ms. Integration time must be computed to be lower than the ranging period, for a selected resolution. Please note that this function has no impact on ranging mode continous.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint32_t) time_ms : Contains the integration time in ms. For all resolutions and frequency, the minimum value is 2ms, and the maximum is 1000ms.
Returns
(uint8_t) status : 0 if set integration time is OK.
Definition at line 1031 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
        uint32_t integration = integration_time_ms;
    /* Integration time must be between 2ms and 1000ms */
    if((integration < (uint32_t)2)
           || (integration > (uint32_t)1000))
    {
        status |= VL53L8CX_STATUS_INVALID_PARAM;
    }else
    {
        integration *= (uint32_t)1000;
        status |= vl53l8cx_dci_replace_data(p_dev, p_dev->temp_buffer,
                VL53L8CX_DCI_INT_TIME, 20,
                (uint8_t*)&integration, 4, 0x00);
    }
    return status;
}
References VL53L8CX_Configuration::temp_buffer, VL53L8CX_DCI_INT_TIME, vl53l8cx_dci_replace_data(), VL53L8CX_STATUS_INVALID_PARAM, and VL53L8CX_STATUS_OK.
Referenced by vl53l8cx_calibrate_xtalk().
vl53l8cx_set_power_mode()
uint8_t vl53l8cx_set_power_mode (VL53L8CX_Configuration * p_dev, uint8_t power_mode)
This function is used to set the sensor in Low Power mode, for example if the sensor is not used during a long time. The macro VL53L8CX_POWER_MODE_SLEEP can be used to enable the low power mode. When user want to restart the sensor, he can use macro VL53L8CX_POWER_MODE_WAKEUP. Please ensure that the device is not streaming before calling the function.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) power_mode : Selected power mode (VL53L8CX_POWER_MODE_SLEEP or VL53L8CX_POWER_MODE_WAKEUP)
Returns
(uint8_t) status : 0 if power mode is OK, or 127 if power mode requested by user is not valid.
Definition at line 462 of file vl53l8cx_api.c.
{
    uint8_t current_power_mode, stored_mode, status = VL53L8CX_STATUS_OK;
    status |= vl53l8cx_get_power_mode(p_dev, &current_power_mode);
    if(power_mode != current_power_mode)
    {
    switch(power_mode)
    {
        case VL53L8CX_POWER_MODE_WAKEUP:
            status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7FFF, 0x00);
            status |= VL53L8CX_WrByte(&(p_dev->platform), 0x09, 0x04);
            status |= VL53L8CX_RdByte(&(p_dev->platform), 0x000F, &stored_mode);
            if(stored_mode == 0x43) /* Only for deep sleep mode */
            {
                status |= VL53L8CX_WrByte(&(p_dev->platform), 0x000F, 0x40);
            }
            status |= _vl53l8cx_poll_for_answer(
                        p_dev, 1, 0, 0x06, 0x01, 1);
            if(stored_mode == 0x43) /* Only for deep sleep mode */
            {
                status |= vl53l8cx_init(p_dev);
            }
            break;
        case VL53L8CX_POWER_MODE_SLEEP:
            status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7FFF, 0x00);
            status |= VL53L8CX_WrByte(&(p_dev->platform), 0x09, 0x02);
            status |= _vl53l8cx_poll_for_answer(
                        p_dev, 1, 0, 0x06, 0x01, 0);
            break;
        case VL53L8CX_POWER_MODE_DEEP_SLEEP:
            status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7FFF, 0x00);
            status |= VL53L8CX_WrByte(&(p_dev->platform), 0x09, 0x02);
            status |= _vl53l8cx_poll_for_answer(
                    p_dev, 1, 0, 0x06, 0x01, 0);
            status |= VL53L8CX_WrByte(&(p_dev->platform), 0x000F, 0x43);
            break;
        default:
            status = VL53L8CX_STATUS_ERROR;
            break;
        }
        status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7FFF, 0x02);
    }
    return status;
}
References _vl53l8cx_poll_for_answer(), VL53L8CX_Configuration::platform, vl53l8cx_get_power_mode(), vl53l8cx_init(), VL53L8CX_POWER_MODE_DEEP_SLEEP, VL53L8CX_POWER_MODE_SLEEP, VL53L8CX_POWER_MODE_WAKEUP, VL53L8CX_RdByte(), VL53L8CX_STATUS_ERROR, VL53L8CX_STATUS_OK, and VL53L8CX_WrByte().
vl53l8cx_set_ranging_frequency_hz()
uint8_t vl53l8cx_set_ranging_frequency_hz (VL53L8CX_Configuration * p_dev, uint8_t frequency_hz)
This function sets a new ranging frequency in Hz. Ranging frequency corresponds to the measurements frequency. This setting depends of the resolution, so please select your resolution before using this function.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) frequency_hz : Contains the ranging frequency in Hz.
For 4x4, min and max allowed values are : [1;60]
For 8x8, min and max allowed values are : [1;15]
Returns
(uint8_t) status : 0 if ranging frequency is OK, or 127 if the value is not correct.
Definition at line 1003 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    status |= vl53l8cx_dci_replace_data(p_dev, p_dev->temp_buffer,
                    VL53L8CX_DCI_FREQ_HZ, 4,
                    (uint8_t*)&frequency_hz, 1, 0x01);
    return status;
}
References VL53L8CX_Configuration::temp_buffer, VL53L8CX_DCI_FREQ_HZ, vl53l8cx_dci_replace_data(), and VL53L8CX_STATUS_OK.
Referenced by lidar_init_sensor(), and vl53l8cx_calibrate_xtalk().
vl53l8cx_set_ranging_mode()
uint8_t vl53l8cx_set_ranging_mode (VL53L8CX_Configuration * p_dev, uint8_t ranging_mode)
This function is used to set the ranging mode. Two modes are available using ULD : Continuous and autonomous. The default mode is Autonomous.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) ranging_mode : Use macros VL53L8CX_RANGING_MODE_CONTINUOUS, VL53L8CX_RANGING_MODE_CONTINUOUS.
Returns
(uint8_t) status : 0 if set ranging mode is OK.
Definition at line 1146 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    uint32_t single_range = 0x00;
    status |= vl53l8cx_dci_read_data(p_dev, p_dev->temp_buffer,
            VL53L8CX_DCI_RANGING_MODE, 8);
    switch(ranging_mode)
    {
        case VL53L8CX_RANGING_MODE_CONTINUOUS:
            p_dev->temp_buffer[0x01] = 0x1;
            p_dev->temp_buffer[0x03] = 0x3;
            single_range = 0x00;
            break;
        case VL53L8CX_RANGING_MODE_AUTONOMOUS:
            p_dev->temp_buffer[0x01] = 0x3;
            p_dev->temp_buffer[0x03] = 0x2;
            single_range = 0x01;
            break;
        default:
            status = VL53L8CX_STATUS_INVALID_PARAM;
            break;
    }
    status |= vl53l8cx_dci_write_data(p_dev, p_dev->temp_buffer,
            VL53L8CX_DCI_RANGING_MODE, (uint16_t)8);
    status |= vl53l8cx_dci_write_data(p_dev, (uint8_t*)&single_range,
            VL53L8CX_DCI_SINGLE_RANGE,
                        (uint16_t)sizeof(single_range));
    return status;
}
References VL53L8CX_Configuration::temp_buffer, VL53L8CX_DCI_RANGING_MODE, vl53l8cx_dci_read_data(), VL53L8CX_DCI_SINGLE_RANGE, vl53l8cx_dci_write_data(), VL53L8CX_RANGING_MODE_AUTONOMOUS, VL53L8CX_RANGING_MODE_CONTINUOUS, VL53L8CX_STATUS_INVALID_PARAM, and VL53L8CX_STATUS_OK.
Referenced by lidar_init_sensor(), and vl53l8cx_calibrate_xtalk().
vl53l8cx_set_resolution()
uint8_t vl53l8cx_set_resolution (VL53L8CX_Configuration * p_dev, uint8_t resolution)
This function sets a new resolution (4x4 or 8x8).
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) resolution : Use macro VL53L8CX_RESOLUTION_4X4 or VL53L8CX_RESOLUTION_8X8 to set the resolution.
Returns
(uint8_t) status : 0 if set resolution is OK.
Definition at line 925 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    switch(resolution){
        case VL53L8CX_RESOLUTION_4X4:
            status |= vl53l8cx_dci_read_data(p_dev,
                    p_dev->temp_buffer,
                    VL53L8CX_DCI_DSS_CONFIG, 16);
            p_dev->temp_buffer[0x04] = 64;
            p_dev->temp_buffer[0x06] = 64;
            p_dev->temp_buffer[0x09] = 4;
            status |= vl53l8cx_dci_write_data(p_dev,
                    p_dev->temp_buffer,
                    VL53L8CX_DCI_DSS_CONFIG, 16);
            status |= vl53l8cx_dci_read_data(p_dev,
                    p_dev->temp_buffer,
                    VL53L8CX_DCI_ZONE_CONFIG, 8);
            p_dev->temp_buffer[0x00] = 4;
            p_dev->temp_buffer[0x01] = 4;
            p_dev->temp_buffer[0x04] = 8;
            p_dev->temp_buffer[0x05] = 8;
            status |= vl53l8cx_dci_write_data(p_dev,
                    p_dev->temp_buffer,
                    VL53L8CX_DCI_ZONE_CONFIG, 8);
            break;
        case VL53L8CX_RESOLUTION_8X8:
            status |= vl53l8cx_dci_read_data(p_dev,
                    p_dev->temp_buffer,
                    VL53L8CX_DCI_DSS_CONFIG, 16);
            p_dev->temp_buffer[0x04] = 16;
            p_dev->temp_buffer[0x06] = 16;
            p_dev->temp_buffer[0x09] = 1;
            status |= vl53l8cx_dci_write_data(p_dev,
                    p_dev->temp_buffer,
                    VL53L8CX_DCI_DSS_CONFIG, 16);
            status |= vl53l8cx_dci_read_data(p_dev,
                    p_dev->temp_buffer,
                    VL53L8CX_DCI_ZONE_CONFIG, 8);
            p_dev->temp_buffer[0x00] = 8;
            p_dev->temp_buffer[0x01] = 8;
            p_dev->temp_buffer[0x04] = 4;
            p_dev->temp_buffer[0x05] = 4;
            status |= vl53l8cx_dci_write_data(p_dev,
                    p_dev->temp_buffer,
                    VL53L8CX_DCI_ZONE_CONFIG, 8);
            break;
        default:
            status = VL53L8CX_STATUS_INVALID_PARAM;
            break;
        }
    status |= _vl53l8cx_send_offset_data(p_dev, resolution);
    status |= _vl53l8cx_send_xtalk_data(p_dev, resolution);
    return status;
}
References _vl53l8cx_send_offset_data(), _vl53l8cx_send_xtalk_data(), VL53L8CX_Configuration::temp_buffer, VL53L8CX_DCI_DSS_CONFIG, vl53l8cx_dci_read_data(), vl53l8cx_dci_write_data(), VL53L8CX_DCI_ZONE_CONFIG, VL53L8CX_RESOLUTION_4X4, VL53L8CX_RESOLUTION_8X8, VL53L8CX_STATUS_INVALID_PARAM, and VL53L8CX_STATUS_OK.
Referenced by lidar_init_sensor(), vl53l8cx_calibrate_xtalk(), vl53l8cx_get_caldata_xtalk(), and vl53l8cx_set_caldata_xtalk().
vl53l8cx_set_sharpener_percent()
uint8_t vl53l8cx_set_sharpener_percent (VL53L8CX_Configuration * p_dev, uint8_t sharpener_percent)
This function sets a new sharpener value in percent. Sharpener can be changed to blur more or less zones depending of the application. Min value is 0 (disabled), and max is 99.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint32_t) sharpener_percent : Value between 0 (disabled) and 99%.
Returns
(uint8_t) status : 0 if set sharpener is OK.
Definition at line 1070 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
        uint8_t sharpener;
    if(sharpener_percent >= (uint8_t)100)
    {
        status |= VL53L8CX_STATUS_INVALID_PARAM;
    }
    else
    {
        sharpener = (sharpener_percent*(uint8_t)255)/(uint8_t)100;
        status |= vl53l8cx_dci_replace_data(p_dev, p_dev->temp_buffer,
                VL53L8CX_DCI_SHARPENER, 16,
                                (uint8_t*)&sharpener, 1, 0xD);
    }
    return status;
}
References VL53L8CX_Configuration::temp_buffer, vl53l8cx_dci_replace_data(), VL53L8CX_DCI_SHARPENER, VL53L8CX_STATUS_INVALID_PARAM, and VL53L8CX_STATUS_OK.
Referenced by vl53l8cx_calibrate_xtalk().
vl53l8cx_set_target_order()
uint8_t vl53l8cx_set_target_order (VL53L8CX_Configuration * p_dev, uint8_t target_order)
This function sets a new target order. Please use macros VL53L8CX_TARGET_ORDER_STRONGEST and VL53L8CX_TARGET_ORDER_CLOSEST to define the new output order. By default, the sensor is configured with the strongest output.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint8_t) target_order : Required target order.
Returns
(uint8_t) status : 0 if set target order is OK, or 127 if target order is unknown.
Definition at line 1105 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    if((target_order == (uint8_t)VL53L8CX_TARGET_ORDER_CLOSEST)
        || (target_order == (uint8_t)VL53L8CX_TARGET_ORDER_STRONGEST))
    {
        status |= vl53l8cx_dci_replace_data(p_dev, p_dev->temp_buffer,
                VL53L8CX_DCI_TARGET_ORDER, 4,
                                (uint8_t*)&target_order, 1, 0x0);
    }else
    {
        status |= VL53L8CX_STATUS_INVALID_PARAM;
    }
    return status;
}
References VL53L8CX_Configuration::temp_buffer, vl53l8cx_dci_replace_data(), VL53L8CX_DCI_TARGET_ORDER, VL53L8CX_STATUS_INVALID_PARAM, VL53L8CX_STATUS_OK, VL53L8CX_TARGET_ORDER_CLOSEST, and VL53L8CX_TARGET_ORDER_STRONGEST.
Referenced by vl53l8cx_calibrate_xtalk().
vl53l8cx_set_VHV_repeat_count()
uint8_t vl53l8cx_set_VHV_repeat_count (VL53L8CX_Configuration * p_dev, uint32_t repeat_count)
This function is used to set a periodic temperature compensation. By setting a repeat count different to 0 the firmware automatically runs a temperature calibration every N frames. default the repeat count is set to 0.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
(uint32_t) repeat_count : Number of frames between temperature compensation. Set to 0 to disable the feature (default configuration).
Definition at line 1252 of file vl53l8cx_api.c.
{
    uint8_t status = VL53L8CX_STATUS_OK;
    status |= vl53l8cx_dci_replace_data(p_dev, p_dev->temp_buffer,
            VL53L8CX_DCI_VHV_CONFIG, 16, (uint8_t*)&repeat_count, 4, 0x4);
    return status;
}
References VL53L8CX_Configuration::temp_buffer, vl53l8cx_dci_replace_data(), VL53L8CX_DCI_VHV_CONFIG, and VL53L8CX_STATUS_OK.
vl53l8cx_start_ranging()
uint8_t vl53l8cx_start_ranging (VL53L8CX_Configuration * p_dev)
This function starts a ranging session. When the sensor streams, host cannot change settings 'on-the-fly'.
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
Returns
(uint8_t) status : 0 if start is OK.
Definition at line 514 of file vl53l8cx_api.c.
{
    uint8_t resolution, status = VL53L8CX_STATUS_OK;
    uint16_t tmp;
    uint32_t i;
    uint32_t header_config[2] = {0, 0};
    union Block_header *bh_ptr;
    uint8_t cmd[] = {0x00, 0x03, 0x00, 0x00};
    status |= vl53l8cx_get_resolution(p_dev, &resolution);
    p_dev->data_read_size = 0;
    p_dev->streamcount = 255;
    /* Enable mandatory output (meta and common data) */
    uint32_t output_bh_enable[] = {
        0x00000007U,
        0x00000000U,
        0x00000000U,
        0xC0000000U};
    /* Send addresses of possible output */
    uint32_t output[] ={VL53L8CX_START_BH,
        VL53L8CX_METADATA_BH,
        VL53L8CX_COMMONDATA_BH,
        VL53L8CX_AMBIENT_RATE_BH,
        VL53L8CX_SPAD_COUNT_BH,
        VL53L8CX_NB_TARGET_DETECTED_BH,
        VL53L8CX_SIGNAL_RATE_BH,
        VL53L8CX_RANGE_SIGMA_MM_BH,
        VL53L8CX_DISTANCE_BH,
        VL53L8CX_REFLECTANCE_BH,
        VL53L8CX_TARGET_STATUS_BH,
        VL53L8CX_MOTION_DETECT_BH};
    /* Enable selected outputs in the 'platform.h' file */
#ifndef VL53L8CX_DISABLE_AMBIENT_PER_SPAD
    output_bh_enable[0] += (uint32_t)8;
#endif
#ifndef VL53L8CX_DISABLE_NB_SPADS_ENABLED
    output_bh_enable[0] += (uint32_t)16;
#endif
#ifndef VL53L8CX_DISABLE_NB_TARGET_DETECTED
    output_bh_enable[0] += (uint32_t)32;
#endif
#ifndef VL53L8CX_DISABLE_SIGNAL_PER_SPAD
    output_bh_enable[0] += (uint32_t)64;
#endif
#ifndef VL53L8CX_DISABLE_RANGE_SIGMA_MM
    output_bh_enable[0] += (uint32_t)128;
#endif
#ifndef VL53L8CX_DISABLE_DISTANCE_MM
    output_bh_enable[0] += (uint32_t)256;
#endif
#ifndef VL53L8CX_DISABLE_REFLECTANCE_PERCENT
    output_bh_enable[0] += (uint32_t)512;
#endif
#ifndef VL53L8CX_DISABLE_TARGET_STATUS
    output_bh_enable[0] += (uint32_t)1024;
#endif
#ifndef VL53L8CX_DISABLE_MOTION_INDICATOR
    output_bh_enable[0] += (uint32_t)2048;
#endif
    /* Update data size */
    for (i = 0; i < (uint32_t)(sizeof(output)/sizeof(uint32_t)); i++)
    {
        if ((output[i] == (uint8_t)0)
                    || ((output_bh_enable[i/(uint32_t)32]
                         &((uint32_t)1 << (i%(uint32_t)32))) == (uint32_t)0))
        {
            continue;
        }
        bh_ptr = (union Block_header *)&(output[i]);
        if (((uint8_t)bh_ptr->type >= (uint8_t)0x1)
                    && ((uint8_t)bh_ptr->type < (uint8_t)0x0d))
        {
            if ((bh_ptr->idx >= (uint16_t)0x54d0)
                            && (bh_ptr->idx < (uint16_t)(0x54d0 + 960)))
            {
                bh_ptr->size = resolution;
            }
            else
            {
                bh_ptr->size = (uint16_t)((uint16_t)resolution
                                  * (uint16_t)VL53L8CX_NB_TARGET_PER_ZONE);
            }
            p_dev->data_read_size += bh_ptr->type * bh_ptr->size;
        }
        else
        {
            p_dev->data_read_size += bh_ptr->size;
        }
        p_dev->data_read_size += (uint32_t)4;
    }
    p_dev->data_read_size += (uint32_t)24;
    status |= vl53l8cx_dci_write_data(p_dev,
            (uint8_t*)&(output), VL53L8CX_DCI_OUTPUT_LIST,
            (uint16_t)sizeof(output));
    header_config[0] = p_dev->data_read_size;
    header_config[1] = i + (uint32_t)1;
    status |= vl53l8cx_dci_write_data(p_dev,
            (uint8_t*)&(header_config), VL53L8CX_DCI_OUTPUT_CONFIG,
            (uint16_t)sizeof(header_config));
    status |= vl53l8cx_dci_write_data(p_dev,
            (uint8_t*)&(output_bh_enable), VL53L8CX_DCI_OUTPUT_ENABLES,
            (uint16_t)sizeof(output_bh_enable));
    /* Start xshut bypass (interrupt mode) */
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x09, 0x05);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x02);
    /* Start ranging session */
    status |= VL53L8CX_WrMulti(&(p_dev->platform), VL53L8CX_UI_CMD_END -
            (uint16_t)(4 - 1), (uint8_t*)cmd, sizeof(cmd));
    status |= _vl53l8cx_poll_for_answer(p_dev, 4, 1,
            VL53L8CX_UI_CMD_STATUS, 0xff, 0x03);
    /* Read ui range data content and compare if data size is the correct one */
    status |= vl53l8cx_dci_read_data(p_dev,
            (uint8_t*)p_dev->temp_buffer, 0x5440, 12);
    (void)memcpy(&tmp, &(p_dev->temp_buffer[0x8]), sizeof(tmp));
    if(tmp != p_dev->data_read_size)
    {
        status |= VL53L8CX_STATUS_ERROR;
    }
    /* Ensure that there is no laser safety fault */
    status |= vl53l8cx_dci_read_data(p_dev,
            (uint8_t*)p_dev->temp_buffer, 0xE0C4, 8);
    if((uint8_t)p_dev->temp_buffer[0x6] != (uint8_t)0)
    {
        status |= VL53L8CX_STATUS_LASER_SAFETY;
    }
    return status;
}
References _vl53l8cx_poll_for_answer(), VL53L8CX_Configuration::data_read_size, Block_header::idx, VL53L8CX_Configuration::platform, Block_header::size, VL53L8CX_Configuration::streamcount, VL53L8CX_Configuration::temp_buffer, Block_header::type, VL53L8CX_AMBIENT_RATE_BH, VL53L8CX_COMMONDATA_BH, VL53L8CX_DCI_OUTPUT_CONFIG, VL53L8CX_DCI_OUTPUT_ENABLES, VL53L8CX_DCI_OUTPUT_LIST, vl53l8cx_dci_read_data(), vl53l8cx_dci_write_data(), VL53L8CX_DISTANCE_BH, vl53l8cx_get_resolution(), VL53L8CX_METADATA_BH, VL53L8CX_MOTION_DETECT_BH, VL53L8CX_NB_TARGET_DETECTED_BH, VL53L8CX_NB_TARGET_PER_ZONE, VL53L8CX_RANGE_SIGMA_MM_BH, VL53L8CX_REFLECTANCE_BH, VL53L8CX_SIGNAL_RATE_BH, VL53L8CX_SPAD_COUNT_BH, VL53L8CX_START_BH, VL53L8CX_STATUS_ERROR, VL53L8CX_STATUS_LASER_SAFETY, VL53L8CX_STATUS_OK, VL53L8CX_TARGET_STATUS_BH, VL53L8CX_UI_CMD_END, VL53L8CX_UI_CMD_STATUS, VL53L8CX_WrByte(), and VL53L8CX_WrMulti().
Referenced by lidar_init_sensor().
vl53l8cx_stop_ranging()
uint8_t vl53l8cx_stop_ranging (VL53L8CX_Configuration * p_dev)
This function stops the ranging session. It must be used when the sensor streams, after calling vl53l8cx_start_ranging().
Parameters
(VL53L8CX_Configuration) *p_dev : VL53L8CX configuration structure.
Returns
(uint8_t) status : 0 if stop is OK
Definition at line 659 of file vl53l8cx_api.c.
{
    uint8_t tmp = 0, status = VL53L8CX_STATUS_OK;
    uint16_t timeout = 0;
    uint32_t auto_stop_flag = 0;
    status |= VL53L8CX_RdMulti(&(p_dev->platform),
                          0x2FFC, (uint8_t*)&auto_stop_flag, 4);
    if((auto_stop_flag != (uint32_t)0x4FF)
            && (p_dev->is_auto_stop_enabled == (uint8_t)0))
    {
            status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x00);
            /* Provoke MCU stop */
            status |= VL53L8CX_WrByte(&(p_dev->platform), 0x15, 0x16);
            status |= VL53L8CX_WrByte(&(p_dev->platform), 0x14, 0x01);
            /* Poll for G02 status 0 MCU stop */
            while(((tmp & (uint8_t)0x80) >> 7) == (uint8_t)0x00)
            {
                status |= VL53L8CX_RdByte(&(p_dev->platform), 0x6, &tmp);
                status |= VL53L8CX_WaitMs(&(p_dev->platform), 10);
                timeout++; /* Timeout reached after 5 seconds */
                if(timeout > (uint16_t)500)
                {
                    status |= tmp;
                    break;
                }
            }
        }
    /* Check GO2 status 1 if status is still OK */
    status |= VL53L8CX_RdByte(&(p_dev->platform), 0x6, &tmp);
    if((tmp & (uint8_t)0x80) != (uint8_t)0){
        status |= VL53L8CX_RdByte(&(p_dev->platform), 0x7, &tmp);
        if((tmp != (uint8_t)0x84) && (tmp != (uint8_t)0x85)){
           status |= tmp;
        }
    }
    /* Undo MCU stop */
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x14, 0x00);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x15, 0x00);
    /* Stop xshut bypass */
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x09, 0x04);
    status |= VL53L8CX_WrByte(&(p_dev->platform), 0x7fff, 0x02);
    return status;
}
References VL53L8CX_Configuration::is_auto_stop_enabled, VL53L8CX_Configuration::platform, VL53L8CX_RdByte(), VL53L8CX_RdMulti(), VL53L8CX_STATUS_OK, VL53L8CX_WaitMs(), and VL53L8CX_WrByte().