components/sensor_acq/vl53l8cx_platform.c File Reference
Couche plateforme VL53L8CX — implémentation SPI via ESP-IDF.
#include "vl53l8cx_platform.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <stdlib.h>
#include <string.h>
Macros
#define PLATFORM_TIMEOUT_MS 100
#define MAX_SPI_TRANSFER (4096 + 2)
Functions
uint8_t VL53L8CX_PlatformInit (VL53L8CX_Platform *p_platform)
Valide le handle SPI (device déjà ajouté au bus par hw_diag).
static esp_err_t spi_xfer (spi_device_handle_t spi, const uint8_t *tx_buf, uint8_t *rx_buf, size_t length)
uint8_t VL53L8CX_RdMulti (VL53L8CX_Platform *p_platform, uint16_t RegisterAddress, uint8_t *p_values, uint32_t size)
Lit plusieurs octets depuis un registre 16 bits du VL53L8CX.
uint8_t VL53L8CX_WrMulti (VL53L8CX_Platform *p_platform, uint16_t RegisterAddress, uint8_t *p_values, uint32_t size)
Écrit plusieurs octets vers un registre 16 bits du VL53L8CX.
uint8_t VL53L8CX_RdByte (VL53L8CX_Platform *p_platform, uint16_t RegisterAddress, uint8_t *p_value)
Lit un octet depuis un registre 16 bits du VL53L8CX.
uint8_t VL53L8CX_WrByte (VL53L8CX_Platform *p_platform, uint16_t RegisterAddress, uint8_t value)
Écrit un octet dans un registre 16 bits du VL53L8CX.
uint8_t VL53L8CX_WaitMs (VL53L8CX_Platform *p_platform, uint32_t TimeMs)
Attend un délai en millisecondes.
Variables
static const char * TAG = "vl53l8cx_plat"
Detailed Description
Couche plateforme VL53L8CX — implémentation SPI via ESP-IDF.
Protocole SPI VL53L8CX (mode 3, CPOL=1 CPHA=1) : Écriture N octets : TX=[addr_hi & 0x7F][addr_lo][d0..dN-1] Lecture N octets : TX=[addr_hi | 0x80][addr_lo][0x00 × N] RX=[xx][xx][d0..dN-1] (2 premiers octets ignorés)
Les handles SPI sont créés dans hw_diag.c (spi_bus_add_device) et transmis via sys_context_t → VL53L8CX_Platform.spi_dev.
Definition in file vl53l8cx_platform.c.
Macro Definition Documentation
MAX_SPI_TRANSFER
#define MAX_SPI_TRANSFER (4096 + 2)
Definition at line 26 of file vl53l8cx_platform.c.
PLATFORM_TIMEOUT_MS
#define PLATFORM_TIMEOUT_MS 100
Definition at line 24 of file vl53l8cx_platform.c.
Function Documentation
spi_xfer()
esp_err_t spi_xfer (spi_device_handle_t spi, const uint8_t * tx_buf, uint8_t * rx_buf, size_t length) [static]
Definition at line 50 of file vl53l8cx_platform.c.
{
    spi_transaction_t t = {
        .length = length * 8, /* en bits */
        .tx_buffer = tx_buf,
        .rx_buffer = rx_buf,
    };
    return spi_device_polling_transmit(spi, &t);
}
Referenced by VL53L8CX_RdMulti(), and VL53L8CX_WrMulti().
VL53L8CX_PlatformInit()
uint8_t VL53L8CX_PlatformInit (VL53L8CX_Platform * p_platform)
Valide le handle SPI (device déjà ajouté au bus par hw_diag).
Parameters
p_platform Contexte plateforme (contient le handle SPI).
Returns
0 si succès (convention ULD ST).
Definition at line 31 of file vl53l8cx_platform.c.
{
    if (!p_platform->spi_dev) {
        ESP_LOGE(TAG, "PlatformInit : spi_dev NULL");
        return 1;
    }
    return 0;
}
References VL53L8CX_Platform::spi_dev, and TAG.
Referenced by lidar_init_sensor().
VL53L8CX_RdByte()
uint8_t VL53L8CX_RdByte (VL53L8CX_Platform * p_platform, uint16_t RegisterAddress, uint8_t * p_value)
Lit un octet depuis un registre 16 bits du VL53L8CX.
Parameters
p_platform Contexte plateforme.
RegisterAddress Adresse 16 bits du registre.
p_value Valeur lue (1 octet).
Returns
0 si succès (convention ULD ST).
Definition at line 132 of file vl53l8cx_platform.c.
{
    return VL53L8CX_RdMulti(p_platform, RegisterAddress, p_value, 1);
}
References VL53L8CX_RdMulti().
Referenced by _vl53l8cx_poll_for_mcu_boot(), vl53l8cx_get_power_mode(), vl53l8cx_init(), vl53l8cx_is_alive(), vl53l8cx_set_power_mode(), and vl53l8cx_stop_ranging().
VL53L8CX_RdMulti()
uint8_t VL53L8CX_RdMulti (VL53L8CX_Platform * p_platform, uint16_t RegisterAddress, uint8_t * p_values, uint32_t size)
Lit plusieurs octets depuis un registre 16 bits du VL53L8CX.
Parameters
p_platform Contexte plateforme.
RegisterAddress Adresse 16 bits du registre.
p_values Buffer de sortie (taille >= size).
size Nombre d'octets à lire.
Returns
0 si succès (convention ULD ST).
Definition at line 65 of file vl53l8cx_platform.c.
{
    size_t total = 2 + (size_t)size;
    uint8_t *tx = calloc(1, total);
    uint8_t *rx = calloc(1, total);
    if (!tx || !rx) {
        ESP_LOGE(TAG, "RdMulti : malloc(%u) échoué", (unsigned)total);
        free(tx); free(rx);
        return 1;
    }
    /* Header de lecture : bit 15 = 1 */
    tx[0] = (uint8_t)((RegisterAddress >> 8) | 0x80);
    tx[1] = (uint8_t)(RegisterAddress & 0xFF);
    /* Octets restants laissés à 0x00 (dummy pour générer l'horloge) */
    esp_err_t ret = spi_xfer(p_platform->spi_dev, tx, rx, total);
    if (ret == ESP_OK) {
        memcpy(p_values, &rx[2], size); /* Sauter les 2 octets header */
    } else {
        ESP_LOGE(TAG, "RdMulti addr=0x%04X : %s",
                 RegisterAddress, esp_err_to_name(ret));
    }
    free(tx);
    free(rx);
    return (ret == ESP_OK) ? 0 : 1;
}
References VL53L8CX_Platform::spi_dev, spi_xfer(), and TAG.
Referenced by _vl53l8cx_poll_for_answer(), _vl53l8cx_poll_for_answer(), vl53l8cx_calibrate_xtalk(), vl53l8cx_check_data_ready(), vl53l8cx_dci_read_data(), vl53l8cx_get_caldata_xtalk(), vl53l8cx_get_ranging_data(), vl53l8cx_init(), VL53L8CX_RdByte(), and vl53l8cx_stop_ranging().
VL53L8CX_WaitMs()
uint8_t VL53L8CX_WaitMs (VL53L8CX_Platform * p_platform, uint32_t TimeMs)
Attend un délai en millisecondes.
Parameters
p_platform Contexte plateforme (non utilisé, mais imposé par l'ULD).
TimeMs Durée d'attente (ms).
Returns
0 si succès (convention ULD ST).
Definition at line 147 of file vl53l8cx_platform.c.
{
    (void)p_platform;
    vTaskDelay(pdMS_TO_TICKS(TimeMs));
    return 0;
}
Referenced by _vl53l8cx_poll_for_answer(), _vl53l8cx_poll_for_answer(), _vl53l8cx_poll_for_mcu_boot(), vl53l8cx_calibrate_xtalk(), vl53l8cx_init(), and vl53l8cx_stop_ranging().
VL53L8CX_WrByte()
uint8_t VL53L8CX_WrByte (VL53L8CX_Platform * p_platform, uint16_t RegisterAddress, uint8_t value)
Écrit un octet dans un registre 16 bits du VL53L8CX.
Parameters
p_platform Contexte plateforme.
RegisterAddress Adresse 16 bits du registre.
value Octet à écrire.
Returns
0 si succès (convention ULD ST).
Definition at line 138 of file vl53l8cx_platform.c.
{
    return VL53L8CX_WrMulti(p_platform, RegisterAddress, &value, 1);
}
References VL53L8CX_WrMulti().
Referenced by vl53l8cx_get_power_mode(), vl53l8cx_init(), vl53l8cx_is_alive(), vl53l8cx_set_i2c_address(), vl53l8cx_set_power_mode(), vl53l8cx_start_ranging(), and vl53l8cx_stop_ranging().
VL53L8CX_WrMulti()
uint8_t VL53L8CX_WrMulti (VL53L8CX_Platform * p_platform, uint16_t RegisterAddress, uint8_t * p_values, uint32_t size)
Écrit plusieurs octets vers un registre 16 bits du VL53L8CX.
Parameters
p_platform Contexte plateforme.
RegisterAddress Adresse 16 bits du registre.
p_values Données à écrire.
size Nombre d'octets à écrire.
Returns
0 si succès (convention ULD ST).
Definition at line 101 of file vl53l8cx_platform.c.
{
    size_t total = 2 + (size_t)size;
    uint8_t *tx = malloc(total);
    if (!tx) {
        ESP_LOGE(TAG, "WrMulti : malloc(%u) échoué", (unsigned)total);
        return 1;
    }
    /* Header d'écriture : bit 15 = 0 */
    tx[0] = (uint8_t)((RegisterAddress >> 8) & 0x7F);
    tx[1] = (uint8_t)(RegisterAddress & 0xFF);
    memcpy(&tx[2], p_values, size);
    esp_err_t ret = spi_xfer(p_platform->spi_dev, tx, NULL, total);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "WrMulti addr=0x%04X : %s",
                 RegisterAddress, esp_err_to_name(ret));
    }
    free(tx);
    return (ret == ESP_OK) ? 0 : 1;
}
References VL53L8CX_Platform::spi_dev, spi_xfer(), and TAG.
Referenced by _vl53l8cx_send_offset_data(), _vl53l8cx_send_xtalk_data(), vl53l8cx_calibrate_xtalk(), vl53l8cx_dci_read_data(), vl53l8cx_dci_write_data(), vl53l8cx_get_caldata_xtalk(), vl53l8cx_init(), vl53l8cx_start_ranging(), and VL53L8CX_WrByte().
Variable Documentation
TAG
const char* TAG = "vl53l8cx_plat" [static]
Definition at line 22 of file vl53l8cx_platform.c.